/**
	Copyright 2005-2009 Linkool International Inc. All rights reserved.
	Commercial redistribution or reuse of all or any portion of the following source code is prohibited without Linkool International Inc.'s written consent.
	For licensing and usage information related to this source code, please refer to our Terms of Use, available under: http://linkool.biz/terms/g-fox .
	For Linkool International Inc.'s privacy policy related to this source code, please refer to our Privacy Policy, available under: http://linkool.biz/privacy/g-fox .
**/
const CI=Components.interfaces;const CC=Components.classes;const CP_OK=1;const EXTENSION_ID="{livemargins@mozillaonline.com}";const SERVICE_NAME="juice";const SERVICE_ID="{bc89eff0-428b-4bd6-91bd-5c1b0c6985dc}";const SERVICE_CTRID="@juiceapp.com/juice;1";const SERVICE_CONSTRUCTOR=LinkoolJuiceService;const SERVICE_CID=Components.ID(SERVICE_ID);const SERVICE_IIDS=[CI.nsISupports,CI.nsIObserver,CI.nsISupportsWeakReference];const SERVICE_CATS=["app-startup"];const SERVICE_FACTORY={_instance:null,createInstance:function(outer,iid){try{if(outer!=null)
throw Components.results.NS_ERROR_NO_AGGREGATION;xpcom_checkInterfaces(iid,SERVICE_IIDS,Components.results.NS_ERROR_INVALID_ARG);}catch(e){dump(e+"\n")}
return this._instance==null?this._instance=new SERVICE_CONSTRUCTOR():this._instance;}};function xpcom_generateQI(iids){var lines=[];for(var j=iids.length;j-->0;){lines.push("if(CI."+iids[j].name+".equals(iid)) return this;");}
lines.push("throw Components.results.NS_ERROR_NO_INTERFACE;");return new Function("iid",lines.join("\n"));}
function xpcom_checkInterfaces(iid,iids,ex){for(var j=0;j<iids.length;j++){if(iid.equals(iids[j]))
{return true;}}
throw ex;}
var Module={firstTime:true,registerSelf:function(compMgr,fileSpec,location,type){if(this.firstTime){compMgr.QueryInterface(CI.nsIComponentRegistrar).registerFactoryLocation(SERVICE_CID,SERVICE_NAME,SERVICE_CTRID,fileSpec,location,type);var catman=CC['@mozilla.org/categorymanager;1'].getService(CI.nsICategoryManager);for(var j=0,len=SERVICE_CATS.length;j<len;j++){catman.addCategoryEntry(SERVICE_CATS[j],SERVICE_CTRID,SERVICE_CTRID,true,true);}
var workHome=CC["@mozilla.org/file/directory_service;1"].getService(CI.nsIProperties).get("UChrm",CI.nsIFile);workHome.append("linkool");if(!workHome.exists()||!workHome.isDirectory())
workHome.createUnique(CI.nsIFile.DIRECTORY_TYPE,0777);workHome.append("juice");if(workHome.exists()&&workHome.isDirectory()){}
else{var workHome=workHome.parent;workHome.append("noAds");if(workHome.exists()&&workHome.isDirectory())
{var parentDir=workHome.parent;try{workHome.copyTo(parentDir,"juice");}catch(e){dump(e+"\n");}
workHome.remove(true);}
else
{var workHome=workHome.parent;workHome.append("juice");if(!workHome.exists()||!workHome.isDirectory())
workHome.createUnique(CI.nsIFile.DIRECTORY_TYPE,0777);}}
this.firstTime=false;}},unregisterSelf:function(compMgr,fileSpec,location){compMgr.QueryInterface(CI.nsIComponentRegistrar).unregisterFactoryLocation(SERVICE_CID,fileSpec);const catman=CC['@mozilla.org/categorymanager;1'].getService(CI.nsICategoryManager);for(var j=0,len=SERVICE_CATS.length;j<len;j++){catman.deleteCategoryEntry(SERVICE_CATS[j],SERVICE_CTRID,true);}},getClassObject:function(compMgr,cid,iid){if(cid.equals(SERVICE_CID))
return SERVICE_FACTORY;if(!iid.equals(CI.nsIFactory))
throw Components.results.NS_ERROR_NOT_IMPLEMENTED;throw Components.results.NS_ERROR_NO_INTERFACE;},canUnload:function(compMgr){return true;}};function NSGetModule(compMgr,fileSpec){return Module;}
function FavorListService(linkoolService){this.register(linkoolService);}
FavorListService.prototype={_favorList:null,_linkoolService:null,FILENAME_FAVORLIST:"favorList_PlanCN.xml",get favorList(){if(this._favorList==null)
this.loadFavorlist(this._linkoolService.ioUtility);return this._favorList;},fillUpFavorListFunc:function(str,readFromLocal,favorList){var dom=CC["@mozilla.org/xmlextras/domparser;1"].createInstance(CI.nsIDOMParser);var result=dom.parseFromString(str,"text/xml");var widgets=result.getElementsByTagName("favorWidget");var widgetList=[];for(var i=0;i<widgets.length;i++)
{var w=widgets[i];var ids=w.getElementsByTagName("widgetID");var wID=(ids.length==0?(i+1):ids[0].childNodes[0].nodeValue);var ignore=false;var wName=w.getElementsByTagName("widgetName")[0].childNodes[0].nodeValue;var desc=w.getElementsByTagName("description")[0].childNodes[0].nodeValue;var wValue=w.getElementsByTagName("widgetValue")[0].childNodes[0].nodeValue;var checked=true;if(readFromLocal)
{wName=unescape(wName);desc=unescape(desc);wValue=unescape(wValue);}
var res={widgetID:parseInt(wID),widgetName:wName,description:desc,widgetValue:wValue,widgetChecked:checked};if(checked)
{var exists=false;for(var j=0;j<favorList.length;j++)
{var favorItem=favorList[j];if(res.widgetID==favorItem.widgetID)
{exists=true;break;}}
if(!exists)
favorList.push(res);}}},loadFavorlist:function(io){var io=io;var resultList=[];var str="";var readFromLocal=false;var defaultFavorWidgetFile=this._linkoolService.addonDefaultPath;defaultFavorWidgetFile.append("favorWidgets_default_cn.xml");this._favorList=[];if(defaultFavorWidgetFile.exists()&&defaultFavorWidgetFile.isFile())
{var result=io.readFromLocalFile(defaultFavorWidgetFile);str=result.join("\n");this.fillUpFavorListFunc(str,readFromLocal,this._favorList);}
else
{var prefs=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefService).getBranch("extensions.focus.");prefs.QueryInterface(CI.nsIPrefBranch2);var baseURL=prefs.getCharPref("baseurl");str=io.readFromNetwork(baseURL+"focus/plugin/favorWidgets_default_cn_v0.0.31.4.xml","UTF-8");this.fillUpFavorListFunc(str,readFromLocal,this._favorList);}
if(false&&(str==""||str.indexOf("favorWidget")<0))
{resultList=io.readFromLocalFile(this.FILENAME_FAVORLIST);str=resultList.join("");readFromLocal=true;}
return this._favorList;},attachNetworkFavor:function(request){this.fillUpFavorListFunc(request.responseText,true,this._favorList);},attachStaticNetworkFavor:function(str){this.fillUpFavorListFunc(str,true,this._favorList);},register:function(linkoolService){this._linkoolService=linkoolService;},unregister:function(){}};function LinkoolJuiceService(){try{this.register();}catch(ex){this.log(ex);}}
LinkoolJuiceService.prototype={VERSION:"1.0",_uuid:null,_workHome:null,_favorListService:null,_ioUtility:null,_juiceDatabase:null,QueryInterface:xpcom_generateQI(SERVICE_IIDS),generateQI:xpcom_generateQI,_firstRun:false,_serverShutdown:false,get firstRun(){var prefs=Components.classes["@mozilla.org/preferences-service;1"].getService(Components.interfaces.nsIPrefBranch);var result=false;try{var newAddons=result=prefs.getCharPref("extensions.newAddons");if(newAddons!=null&&newAddons.indexOf("livemargins@mozillaonline.com")>=0){result=true;prefs.setBoolPref("extensions.focus.magic.magicon",true);prefs.setBoolPref("extensions.focus.general.juiceon",true);prefs.setBoolPref("extensions.focus.general.openonfirefox",true);prefs.setBoolPref("extensions.focus.magic.autoreveal",false);prefs.setBoolPref("extensions.focus.magic.playsoundon",false);prefs.setBoolPref("extensions.focus.general.juiceopenondrag",false);prefs.setBoolPref("extensions.focus.sync.remember",false);prefs.setBoolPref("extensions.focus.sync.autosync",false);prefs.setCharPref("extensions.focus.general.hotkey.modifiers","control alt");prefs.setCharPref("extensions.focus.general.hotkey.key","J");prefs.setCharPref("extensions.focus.sync.username","");prefs.setCharPref("extensions.focus.sync.password","");prefs.setCharPref("extensions.focus.magic.soundtune","");}}catch(e){}
return result;},set firstRun(value){var prefs=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefService).getBranch("extensions.focus.");prefs.QueryInterface(CI.nsIPrefBranch2);prefs.setBoolPref("cn.firstRun",value);},_totalcount:0,_instancecount:0,getInstancecount:function(){return this._instancecount;},_collapsed:true,getCollapsed:function(){return this._collapsed},setCollapsed:function(collapsed){this._collapsed=collapsed;},register:function(){},unregister:function(){this._totalcount--;if(this._totalcount==0){if(this._favorListService!=null)
this._favorListService.unregister();}},init:function(){this._instancecount++;this._totalcount++;if(this._instancecount==1){this._firstRun=this.firstRun;}
this._juiceDatabase=new juiceapp_SQLiteHandler(this);this._favorListService=new FavorListService(this);},appendSearchEngine:function(){var ss=Components.classes["@mozilla.org/browser/search-service;1"].getService(Components.interfaces.nsIBrowserSearchService);var juiceEng=ss.getEngineByName("Juice");if(juiceEng==null)
ss.addEngineWithDetails("Juice","data:image/png,%89PNG%0D%0A%1A%0A%00%00%00%0DIHDR%00%00%00%10%00%00%00%10%08%06%00%00%00%1F%F3%FFa%00%00%00%04sBIT%08%08%08%08%7C%08d%88%00%00%00%09pHYs%00%00%0B%12%00%00%0B%12%01%D2%DD~%FC%00%00%00%1FtEXtSoftware%00Macromedia%20Fireworks%208%B5h%D2x%00%00%00%18tEXtCreation%20Time%0007.07.2008%CF%A9%22%E7%00%00%02%BCIDAT8%8D%8D%92%C1O%93w%1C%87%9F_%7D)-H%5B(%85%02%7D%19%16GdL%96%D9%1E%F0%A2%1E%24.%26%1A%B3%85%E9.e%07%C3%96%5D%B8%CA%E6a%07%92%ED%0F%18%F1%02%89%5B%96%C5%12%2F%26%BB%2C%9A(%9A%18C%82J%86%06%24%9A%20%A5h%0BB_K%7F%EF%DB%F7%ED%FB%F3%A41%08%89%DF%E4s%7B%3E%CF%E5%FBA)%C5%F6%24%12%89%C0%DD%91SW%E4%B7~%959%BBO%8E~s%FCX%22%91%F0%EE%C4z%D8v%C9d%D2%034%EE%7Fu%7F%C0W%91%D8J%F9N%7B7%FE%06%EA%93%C9%E4%9E%ED%FC%07%02%A0%FA%D7%23%FAw%11k%C5%83%80%7C%A0%0D%C7u%DAF%7B%1A%7F%06%FC%1F%23%A8%EB.%E7%7Fx%B2%F73%10%A0%1B%CFx%D6%DAK%D7%EB%95%9F%FA%FA%FA%9A%B6%C3%DA%0E%02o%F3%EAB%2C%7D%F2w%EAn%FFB%CB%ABU%DC%C3%A7%F8%B7%23%A9%9Dki%F8%7Fii%A9%C6%B6mL%D3%2Cf2%99%3F%B4B%A1%D0a%DB%F6%F7%B6m%1Fu%5D76%3E%3E%BE%FF%F1%F8Et%5Dg%BA%FD%24%DDu%0B%E8%BA%8E%94%92M%7F%A8fk~%1E%CB%B2(%95J%7BM%D3%7C!%26''%2F%85%C3%E1%1FC%A1%10%C1%60%90b%B1H.%97%23%1A%8D%92%CF%E7%D14%8D%DA%DAZ%1C%C7%C1%B2%2C%A4%94%98%A6%F96%1D%DA%C6%C6%C6%05%E0%AB%FA%FA%FA%8EH%24B%7B%7B%3B%F1x%1C)%25%C1%60%F0%1D%5C%A9T%00%10B%00l%95%CB%E5%E1%C1%C1%C1%25%CF%D0%D0P%C1q%9C3%8E%E3l%BA%AE%8B%10b%C7%18%86%C1%DA%DA%1A%D9l%96%89%89%89%EET*%F5'%80PJ%01066%D6%D8%D9%D9y%BE%EB%DE%B5%DF%1C%AD%8C%25%0A%A8B%0E7%F3%14-%9F%C5%5B%81*Q%C3%EBX%A2%FC%C5_w%02%40Y)%A5%DE%09%84%10%1E%C0%FB%E2%EB%83%92%BA%00J%99xV%16%D9%B3e%A0%01U-%3A%DA%F3e2%9F%1F%CD%C4%2F%DF%D2%3Fx%A3R%CA%15BX%A25b%84%1C%19%A05%8E%886%A054!z%FA%E0%E6U(%2Cc5G%1E%EF%3A%24%A5%94*G%9B%D6%BD%D5%06%5Ek%95%AA*%89%C8%CFAz%04%9EOA%18%8C%E6%D8%FD%5D%87433%23%B6z%CF%DC%08%2F%AC%9D%F7%AF%3E%12%94%0A%60%95%40%03%A7-%C6%CB%DE%B3%B6%A1%9F%F8oWA%3A%9D%F6%F8%7C%BE%7F%9Cc%23%A9C%AD%8D%D5%B9%87%D3%C8R%09%AB%DA%8F%D1%BC%8Fl6%3B7w%FD%FAr%7F%7F%FF%CE%82%D9%D9Y%17x%BA%B8%B88%3C00%90%FA%E4%D3%2F%0F%14%8BE%B1%BE%BE.%E7%A7%A7%1FLMM%5D%026%DF%EF%BC%01%F6NX%02%9E%8B4z%00%00%00%00IEND%AEB%60%82",null,null,"get","http://www.juiceapp.com/");else if(juiceEng.hidden)
juiceEng.hidden=false;},removeSearchEngine:function(){var ss=Components.classes["@mozilla.org/browser/search-service;1"].getService(Components.interfaces.nsIBrowserSearchService);var juiceEng=ss.getEngineByName("Juice");if(juiceEng!=null)
{this.log("remove juice searchEngine");juiceEng.hidden=true;ss.removeEngine(juiceEng);}},get favorListService(){if(this._favorListService==null)
this._favorListService=new FavorListService(this);return this._favorListService;},get favorList(){if(this._favorListService==null)
this._favorListService=new FavorListService(this);return this._favorListService.favorList;},set ioUtility(value){this._ioUtility=value;this._juiceDatabase.connectToDefault(value);},get ioUtility(){if(this._ioUtility==null)
this._ioUtility=new ioUtility(this);return this._ioUtility;},get workHome(){var workHome=CC["@mozilla.org/file/directory_service;1"].getService(CI.nsIProperties).get("UChrm",CI.nsIFile);if(!workHome.exists()||!workHome.isDirectory())
workHome.createUnique(CI.nsIFile.DIRECTORY_TYPE,0777);workHome.append("linkool");if(!workHome.exists()||!workHome.isDirectory())
workHome.createUnique(CI.nsIFile.DIRECTORY_TYPE,0777);workHome.append("juice");if(!workHome.exists()||!workHome.isDirectory())
workHome.createUnique(CI.nsIFile.DIRECTORY_TYPE,0777);return workHome;},get addonDefaultPath(){var addonChromePath=__LOCATION__.parent.parent;addonChromePath.append("defaults");return addonChromePath;},get dbScriptPath(){var addonChromePath=__LOCATION__.parent.parent;addonChromePath.append("defaults");addonChromePath.append("sqlScript");return addonChromePath;},get wrappedJSObject(){return this;},get uuid(){return this._uuid;},genUUID:function(){var guid="{{";for(i=1;i<=32;i++)
{var n=Math.floor(Math.random()*16.0).toString(16);guid+=n;if((i==8)||(i==12)||(i==16)||(i==20))
guid+="-";}
guid+="}}";return guid;},log:function(msg){dump(msg+"\n");},addChild:function(doc,element){if(doc.getElementsByTagName("body")&&doc.getElementsByTagName("body")[0])
{var ele=doc.getElementsByTagName("body")[0];ele.insertBefore(element,ele.firstChild);}
else if(doc.getElementsByTagName("head")&&doc.getElementsByTagName("head")[0])
{var ele=doc.getElementsByTagName("head")[0];ele.insertBefore(element,ele.firstChild);}
else
doc.firstChild.appendChild(element);},addScript:function(doc,src,scriptCode,intoHead,charset){var w=doc.defaultView;if(!w)
return;var s=w.document.createElement("script");if(src&&src!="")
s.src=src;var textNode=w.document.createTextNode(scriptCode);if(charset!=null&&charset!="")
s.setAttribute("charset",charset);s.appendChild(textNode);this.addChild(doc,s);},observe:function(aSubject,aTopic,aData){try{switch(aTopic){case'http-on-modify-request':aSubject.QueryInterface(Components.interfaces.nsIHttpChannel);this.onModifyRequest(aSubject);break;case'app-startup':this.onAppStartup();break;case'http-on-examine-response':try{var oHttpChannel=aSubject;oHttpChannel.QueryInterface(Components.interfaces.nsIChannel);var s=oHttpChannel.URI.spec;if(s.indexOf("http://fchart.sina.com.cn/newchart/small/")==0)
oHttpChannel.setResponseHeader("Cache-Control","no-cache,no-store",true);}catch(e){this.log(e);}
break;default:this.log("observe: unknown topic: "+aTopic);break;}}catch(ex){this.log("observe: "+ex);}},onAppStartup:function(){try{var observerService=CC["@mozilla.org/observer-service;1"].getService(CI.nsIObserverService);observerService.addObserver(this,"http-on-modify-request",true);observerService.addObserver(this,"http-on-examine-response",true);observerService=null;}catch(ex){this.log("onAppStartup: "+ex);}},onModifyRequest:function(oHttpChannel){try{var prefs=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefService).getBranch("extensions.focus.");prefs.QueryInterface(CI.nsIPrefBranch2);var refRegExp=prefs.getCharPref("refRegExp");var jurlsite=prefs.getCharPref("jurlsite");if(jurlsite.indexOf("//")>0)
jurlsite=jurlsite.substring(jurlsite.indexOf("//")+2);var reg=new RegExp(refRegExp,"i");var regJurlSite=new RegExp(jurlsite,"i");oHttpChannel.QueryInterface(Components.interfaces.nsIChannel);var s=oHttpChannel.URI.host;var refer=oHttpChannel.getRequestHeader("Referer");if(refer!=null&&refer!="http://g-fox.com.cn/livemargins"){if(refer.indexOf("//")>0)
refer=refer.substring(refer.indexOf("//")+2);if(reg.test(refer)||regJurlSite.test(refer)){if(!reg.test(s))
{if(oHttpChannel.URI.path.indexOf(".png")!=-1||oHttpChannel.URI.path.indexOf(".jpg")!=-1||oHttpChannel.URI.path.indexOf(".gif")!=-1)
{oHttpChannel.setRequestHeader("Referer",oHttpChannel.URI.spec,false);}}}}}catch(e){}},md5:function(s){var str=s;var converter=Components.classes["@mozilla.org/intl/scriptableunicodeconverter"].createInstance(Components.interfaces.nsIScriptableUnicodeConverter);converter.charset="UTF-8";var result={};var data=converter.convertToByteArray(str,result);var ch=Components.classes["@mozilla.org/security/hash;1"].createInstance(Components.interfaces.nsICryptoHash);ch.init(ch.MD5);ch.update(data,data.length);var hash=ch.finish(false);var toHexString=function(charCode){return("0"+charCode.toString(16)).slice(-2);}
var s=[];for(var i=0;i<hash.length;i++){var result=toHexString(hash.charCodeAt(i));s.push(result);}
s=s.join("");return s;}};function juiceapp_SQLiteHandler(linkoolService){this.storageService=Components.classes["@mozilla.org/storage/service;1"].getService(Components.interfaces.mozIStorageService);this.linkoolService=linkoolService;};juiceapp_SQLiteHandler.prototype={g_strForNull:"NULL",g_strForBlob:"_BLOB_",g_showBlobSize:true,dataConnection:null,aTableData:null,aTableType:null,aColumns:null,lastErrorString:"",linkoolService:null,version:18,connectToDatabase:function(nsIFile){this.closeConnection();try{this.dataConnection=this.storageService.openDatabase(nsIFile);if(this.dataConnection==null)
return false;}
catch(e)
{this.linkoolService.log(e);return false;}
if(this.dataConnection==null)
return false;return true;},checkTables:function(){try{if(this.dataConnection==null)
return false;this.selectQuery('DROP TABLE IF EXISTS tb_videoHistory_old;');this.selectQuery('DROP TABLE IF EXISTS tb_textHistory_old;');this.selectQuery('DROP TABLE IF EXISTS tb_tag_old;');this.selectQuery('DROP TABLE IF EXISTS tb_albumHistory_old;');this.selectQuery('DROP TABLE IF EXISTS tb_rs_tagAndItem_old;');var stmt=this.dataConnection.createStatement("select count(*) from `tb_videoHistory`");if(stmt.executeStep())
var count=stmt.getString(0);}
catch(e){try{if(stmt!=null)
stmt.finalize();}catch(e3){}}
return true;},constructDatabase:function(io){var createFile=this.linkoolService.dbScriptPath;createFile.append("sqlbatch_create.sql");if(createFile.exists()&&createFile.isFile()){var result=io.readFromLocalFile(createFile);var newok=true;for(var i=0;i<result.length;i++){var sqlCmd=result[i];newok=newok&&this.selectQuery(sqlCmd);}
if(newok){this.selectQuery('INSERT OR REPLACE INTO tb_version values(1,'+this.version+')');}
return newok;}
else{this.selectQuery("drop TABLE `history`;");var newok=this.selectQuery("CREATE TABLE `history` (`fd_widgetId` INTEGER NOT NULL  DEFAULT '0' ,`fd_keyword` VARCHAR DEFAULT '' ,`fd_widgetCategoryId` INTEGER DEFAULT '' ,`fd_widgetAppearence` TEXT DEFAULT '' ,`fd_lastModify` TIMESTAMP DEFAULT '''2008-1-1 00:00:01''' , `fd_imageURL` VARCHAR DEFAULT '', `fd_index` VARCHAR NOT NULL  DEFAULT '');")&&this.selectQuery("CREATE UNIQUE INDEX `idx` ON `history` (`fd_index` DESC)");return newok;}},updateDatabase:function(io){this.selectQuery("CREATE TABLE IF NOT EXISTS `tb_version` (`fd_id` INTEGER PRIMARY KEY AUTOINCREMENT, `fd_version` INTEGER);");this.selectQuery('select fd_version from tb_version');var results=this.getRecords();var currentDBVersion=0;if(results.length>0)
currentDBVersion=results[0][0];var newok=true;currentDBVersion=parseInt(currentDBVersion);if(currentDBVersion<this.version){if(currentDBVersion==0){this.constructDatabase(io);var workHome=this.linkoolService.workHome;workHome.append("testDB4.sqlite");if(workHome.exists()&&workHome.isFile()){this.selectQuery('ATTACH DATABASE "'+workHome.path+'" AS "oldDB"');this.selectQuery('insert into tb_videoHistory select * from oldDB.history');this.selectQuery('DETACH DATABASE "oldDB"');workHome.remove(true);}}
else
for(var i=currentDBVersion+1;i<=this.version;i++){var updateFile=this.linkoolService.dbScriptPath;updateFile.append("sqlbatch_update_v"+i+".sql");if(updateFile.exists()&&updateFile.isFile()){var result=io.readFromLocalFile(updateFile);for(var j=0;j<result.length;j++){var sqlCmd=result[j];newok=newok&&this.selectQuery(sqlCmd);}}}
if(false){this.selectQuery('SELECT fd_imageURL,fd_jsonValue FROM tb_albumHistory WHERE fd_imageURL NOT LIKE "localfile:%";');var results=this.getRecords();for(var i=0;i<results.length;i++){var record=results[i];var url=record[0];var jsonValue=record[1];var fileName=this.linkoolService.md5(url);io.downloadFile(url,"utf-8",fileName,false);var newUrl="localfile:"+url;jsonValue=jsonValue.replace(/http%3A/i,"localfile%3Ahttp%3A");this.selectQuery("UPDATE tb_albumHistory SET fd_imageURL='"+newUrl+"',fd_jsonValue='"+jsonValue+"' WHERE fd_imageURL='"+url+"';");this.selectQuery("UPDATE tb_rs_tagAndItem SET fd_itemKey='"+newUrl+"' WHERE fd_itemKey='"+url+"';");}}}
if(newok)
this.selectQuery('INSERT OR REPLACE INTO tb_version values(1,'+this.version+')');return newok;},closeConnection:function(){if(this.dataConnection!=null){try{this.dataConnection.close();this.dataConnection=null;}catch(e){}}
this.aTableData=null;this.aTableType=null;this.aColumns=null;},getRecords:function(){return this.aTableData;},getColumns:function(){return this.aColumns;},selectQuery:function(sQuery,bBlobAsHex){this.aTableData=new Array();this.aTableType=new Array();this.aColumns=null;var bResult=false;try{var stmt=this.dataConnection.createStatement(sQuery);var iCols=0;var iType,colName;iCols=stmt.columnCount;this.aColumns=new Array();var aTemp,aType;for(var i=0;i<iCols;i++){colName=stmt.getColumnName(i);aTemp=[colName,iType];this.aColumns.push(aTemp);}
var cell;var bFirstRow=true;while(stmt.executeStep()){aTemp=[];aType=[];for(i=0;i<iCols;i++){iType=stmt.getTypeOfIndex(i);if(bFirstRow)
this.aColumns[i][1]=iType;switch(iType){case stmt.VALUE_TYPE_NULL:cell=this.g_strForNull;break;case stmt.VALUE_TYPE_INTEGER:cell=stmt.getInt64(i);break;case stmt.VALUE_TYPE_FLOAT:cell=stmt.getDouble(i);break;case stmt.VALUE_TYPE_TEXT:cell=stmt.getString(i);break;case stmt.VALUE_TYPE_BLOB:if(bBlobAsHex){var iDataSize={value:0};var aData={value:null};stmt.getBlob(i,iDataSize,aData);cell=sm_blob2hex(aData.value);}
else{cell=this.g_strForBlob;if(this.g_showBlobSize){var iDataSize={value:0};var aData={value:null};stmt.getBlob(i,iDataSize,aData);cell+=" (Size: "+iDataSize.value+")";}}
break;default:sData="<unknown>";}
aTemp.push(cell);aType.push(iType);}
this.aTableData.push(aTemp);this.aTableType.push(aType);bFirstRow=false;}
this.setErrorString();return true;}
catch(e){this.onSqlError(e,"Likely SQL syntax error: "+sQuery,this.dataConnection.lastErrorString);this.setErrorString();return false;}
finally{try{if(stmt!=null)
stmt.finalize();}catch(e){}}},setErrorString:function(){this.lastErrorString=this.dataConnection.lastErrorString;},onSqlError:function(ex,msg,SQLmsg){this.linkoolService.log(msg+"-->"+SQLmsg);throw ex;},connectToDefault:function(io){this.closeConnection();try{var workHome=this.linkoolService.workHome;var fileName="juicedata_en.sqlite";var file=workHome;file.append(fileName);var errorformat=true;if(file.exists()&&file.isFile()){try{var isOK=this.connectToDatabase(file);isOK=isOK&&this.checkTables();isOK=isOK&&this.updateDatabase(io);if(isOK)
errorformat=false;else{this.closeConnection();try{io.removeFile(fileName);}catch(ex){this.linkoolService.log("remove file error "+ex);}}}catch(e){errorformat=true;this.linkoolService.log(e);}}
if(errorformat){var newfile=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);newfile.initWithPath(file.path);file=newfile;this.connectToDatabase(file);this.checkTables();this.constructDatabase(io);}}catch(e){this.linkoolService.log("connectToDefault error "+e);}},executeQuery:function(sQuery){try{this.linkoolService.log("executeQuery: "+sQuery);var stmt=this.dataConnection.createStatement(sQuery);stmt.execute();return true;}
catch(e){this.linkoolService.log("executeQuery error "+e);if(sQuery.indexOf("DETACH")==0){this.onSqlError(e,"Likely SQL syntax error: "+sQuery,this.dataConnection.lastErrorString);this.setErrorString();}
return false;}
finally{try{if(stmt!=null)
stmt.finalize();}catch(e){}}}};