/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */var EbayCompanion={init:function(){try{this._importModule("helpers/logger.js");this._importModule("helpers/observers.js");this._importModule("datasource.js");this._importModule("constants.js");this._observers=new EbayCompanion.Observers;let that=this;this.userIsAway=true;let setUpdateLoginBroadcaster=function(connected){document.getElementById("ec-ebaybutton-broadcaster").setAttribute("connected",connected);that.updateButtonTooltip();}
this._observers.add(function()setUpdateLoginBroadcaster(true),"ebay-account-logged-in");this._observers.add(function()setUpdateLoginBroadcaster(false),"ebay-account-logged-out");this._observers.add(function(info){let account=info.object;let currentAccount=EbayCompanion.Datasource.activeAccount();if(currentAccount&&currentAccount.get("userId").toLowerCase()==account.get("userId").toLowerCase()){let notifyFeedbackEnabled=EbayCompanion.Constants.prefBranch.get("notifyFeedback");let preventNotificationDisplay=EbayCompanion.Constants.prefBranch.get("prevent.first.feedback.score.notification");if(notifyFeedbackEnabled&&!preventNotificationDisplay){let delta=account.get("feedbackRating")-
info.originalObject.get("feedbackRating");that._showFeedbackChangedNotification(delta);}
that._updateSidebarFeedbackScore(currentAccount.get("feedbackRating"));}},"ebay-account-feedback-changed");this._observers.add(function(info){let account=info.object;let currentAccount=EbayCompanion.Datasource.activeAccount();let notifyNewMessagesEnabled=EbayCompanion.Constants.prefBranch.get("notifyNewMessages");if(notifyNewMessagesEnabled&&currentAccount&&currentAccount.get("userId").toLowerCase()==account.get("userId").toLowerCase()){that.showNewMessagesNotification(currentAccount.get("numUnreadMessages"));}},"ebay-account-unread-messages-changed");let connected=EbayCompanion.Datasource.activeAccount()!=null;setUpdateLoginBroadcaster(connected);let content=document.getElementById("content");this.addManagedEventListener(content,"DOMContentLoaded",function(event)that._onContentLoaded(event),false);this.addManagedEventListener(window,"mousemove",function(event)that._onMouseMove(),false);this.addManagedEventListener(window,"focus",function(event)that._onFocus(),true);this._initeBayButton();EbayCompanion.Alerts.init();EbayCompanion.BrowserContextMenu.init();EbayCompanion.Constants.getVersion(that._startupChecks);if(EbayCompanion.Constants.prefBranch.get("firstSignIn")){this._showTermsNotification();}
let ebayArgumentsHandler=Cc["@mozilla.org/commandlinehandler/general-startup;1?type=ebayarghandler"].getService(Ci.ecIEbayArgumentsHandler);let shortcut=ebayArgumentsHandler.startedUsingShortcut;if(0!=shortcut&&!EbayCompanion.Constants.shortcutParameterRead){window.setTimeout(function(){if(1==shortcut){that.openPage(null,'desktopShortcut','homePage');}else if(2==shortcut){that.openPage(null,'installerShortcut','homePage');}
if(!EbayCompanion.Constants.prefBranch.get("SanDiskBuild")){that.openSidebar();}
EbayCompanion.Constants.shortcutParameterRead=true;},500);}
window.setTimeout(function(){that._importModule("uninstallManager.js");},1000)}
catch(e){EbayCompanion.Logger.exception(e);}},uninit:function(){try{EbayCompanion.Alerts.uninit();EbayCompanion.BrowserContextMenu.uninit();this._observers.removeAll();this.removeAllManagedEventListeners();}
catch(e){EbayCompanion.Logger.exception(e);}},_startupChecks:function(aVersion){let upgrade=false;let termsChanged=false;let reportUpgrade=EbayCompanion.Constants.prefBranch.get("reportUpgrade");let currentVersion=EbayCompanion.Constants.prefBranch.get("version");if(currentVersion&&currentVersion.match(/^1\.(.)*$/g)){upgrade=true;termsChanged=true;reportUpgrade=true;}
if(!reportUpgrade&&currentVersion&&currentVersion!=aVersion){if(aVersion=="2.0.3"){termsChanged=true;}
reportUpgrade=true;window.setTimeout(function(){EbayCompanion.openSidebar();},2000);}
EbayCompanion.Constants.prefBranch.set("reportUpgrade",reportUpgrade);EbayCompanion.Constants.prefBranch.set("version",aVersion);if(EbayCompanion.Constants.prefBranch.get("firstRun")||upgrade||termsChanged){window.setTimeout(function(){EbayCompanion._firstRun(upgrade,termsChanged);EbayCompanion.Constants.prefBranch.set("firstRun",false);},2000);}},_firstRun:function(aUpgrade,aTermsChanged){try{if(aUpgrade){this._extractAccountInfoFromPasswordManager();}
this.showLicence(aTermsChanged);this.openSidebar();EbayCompanion.Datasource.requestTrackingPixel(false);if(EbayCompanion.Constants.prefBranch.get("common.icon")){this._importModule("helpers/shortcutHelper.js");EbayCompanion.ShortcutHelper.createShortcut();}
this._setDefaultWebSite();this._openFirstRunPage();}
catch(e){EbayCompanion.Logger.exception(e);}},_extractAccountInfoFromPasswordManager:function(){let tokenContainer=this._getTokenFromPasswordManager();const EBAYCOMP_DAYS_BEOFRE_TOKEN_EXPIRE=7;if(tokenContainer){let tokenArray=tokenContainer.tokenString.split("&");if(tokenArray.length>=3){let dateObject=EbayCompanion.Constants.dateFromIso8601(tokenArray[1]);if(dateObject){let currDateObject=new Date();let timeDiffObject=EbayCompanion.Constants.timeDifference(currDateObject.getTime(),dateObject.getTime())
if(EBAYCOMP_DAYS_BEOFRE_TOKEN_EXPIRE>=timeDiffObject.days){this._removeTokenFromPasswordManager();}else{let activeAccount=new EbayCompanion.Account(tokenContainer.username,false);activeAccount.set("token",tokenArray[0]);activeAccount.set("registrationSite",EbayCompanion.Constants.prefBranch.get("chosenSite"));activeAccount.set("feedbackRating",0);activeAccount.set("numUnreadMessages",0);EbayCompanion.Constants.prefBranch.set("prevent.first.feedback.score.notification",true);EbayCompanion.Datasource.setActiveAccount(activeAccount);EbayCompanion.Datasource.tryAutomaticConnect();return true;}}}}
return false;},_getTokenFromPasswordManager:function(){let tokenContainer={username:null,tokenString:null};let ret;let loginManagerService;let passwordManagerService;{let loginManagerClass=Cc["@mozilla.org/login-manager;1"];let passwordManagerClass=Cc["@mozilla.org/passwordmanager;1"];if(loginManagerClass){loginManagerService=loginManagerClass.getService(Ci.nsILoginManager);}else{passwordManagerService=passwordManagerClass.getService(Ci.nsIPasswordManager);}}
const EBAY_HOST_FOR_PASSWORD_MANAGER="eBay.companion";if(loginManagerService){const hostName=EBAY_HOST_FOR_PASSWORD_MANAGER;const formSubmitURL=EBAY_HOST_FOR_PASSWORD_MANAGER;const httpRealm=null;let logins;logins=loginManagerService.findLogins({},hostName,formSubmitURL,httpRealm);if(logins&&logins[0]){tokenContainer.username=logins[0].username;tokenContainer.tokenString=logins[0].password;ret=tokenContainer;}}else{let passwords=passwordManagerService.enumerator;while(!ret&&passwords.hasMoreElements()){let entry=passwords.getNext().QueryInterface(Ci.nsIPassword);if(entry.host==EBAY_HOST_FOR_PASSWORD_MANAGER){tokenContainer.username=entry.user;tokenContainer.tokenString=entry.password;ret=tokenContainer;}}}
return ret;},_removeTokenFromPasswordManager:function(){let loginManagerService;let passwordManagerService;{let loginManagerClass=Cc["@mozilla.org/login-manager;1"];let passwordManagerClass=Cc["@mozilla.org/passwordmanager;1"];if(loginManagerClass){loginManagerService=loginManagerClass.getService(Ci.nsILoginManager);}else{passwordManagerService=passwordManagerClass.getService(Ci.nsIPasswordManager);}}
const EBAY_HOST_FOR_PASSWORD_MANAGER="eBay.companion";if(loginManagerService){const hostName=EBAY_HOST_FOR_PASSWORD_MANAGER;const formSubmitURL=EBAY_HOST_FOR_PASSWORD_MANAGER;const httpRealm=null;let logins;logins=loginManagerService.findLogins({},hostName,formSubmitURL,httpRealm);if(logins&&logins[0]){loginManagerService.removeLogin(logins[0]);}}else{let passwords=passwordManagerService.enumerator;while(passwords.hasMoreElements()){let pass=passwords.getNext().QueryInterface(Components.interfaces.nsIPassword);if(pass.host==EBAY_HOST_FOR_PASSWORD_MANAGER){passwordManagerService.removeUser(EBAY_HOST_FOR_PASSWORD_MANAGER,pass.user);}}}},isSidebarOpen:function(){let sidebar=document.getElementById("ec-toggleSidebar-broadcaster");return sidebar.getAttribute("checked");},openSidebar:function(){window.setTimeout(function(){toggleSidebar("ec-toggleSidebar-broadcaster",true);},0);},closeSidebar:function(){toggleSidebar();},openCloseSidebar:function(){if(this.isSidebarOpen()){this.closeSidebar();}else{this.openSidebar();}},updateButtonTooltip:function(){try{let buttonBroadcaster=document.getElementById("ec-ebaybutton-broadcaster");let tooltipStringID;let tooltip;if(this.isSidebarOpen()){tooltipStringID="ecBrowser.toolbarbutton.sidebarclose.tooltip";}else{if("true"==buttonBroadcaster.getAttribute("connected")){tooltipStringID="ecBrowser.toolbarbutton.sidebaropen.tooltip";if("true"==buttonBroadcaster.getAttribute("glowing")){tooltipStringID="ecBrowser.toolbarbutton.sidebarupdate.tooltip";}}else{tooltipStringID="ecBrowser.toolbarbutton.sidebarconnect.tooltip";}}
tooltip=EbayCompanion.Constants.stringBundle.getString(tooltipStringID);buttonBroadcaster.setAttribute("tooltiptext",tooltip);}
catch(e){EbayCompanion.Logger.exception(e);}},itemButtonClick:function(aEvent,aArea,aButtonAction,aItem){try{let button=aEvent.button;if(button!=2){let itemId=null;let userId=EbayCompanion.Datasource.activeAccount().get("userId");let redirectURL;let url;let args;if(aItem){itemId=aItem.get("itemId");}
switch(aButtonAction){case"raise":args={itemid:itemId};url=EbayCompanion.Constants.getUrl(aArea,"bid",args);break;case"pay":args={itemid:itemId};url=EbayCompanion.Constants.getUrl(aArea,aButtonAction,args);if(aItem.transaction){url+="&transactionId="+aItem.transaction.get("transactionId");}
break;case"relist":case"similar":case"makeOffer":case"reviewOffers":case"reviewOffer":args={itemid:itemId};url=EbayCompanion.Constants.getUrl(aArea,aButtonAction,args);break;case"view":case"bid":case"bin":args={itemid:itemId};url=EbayCompanion.Constants.getUrl(aArea,"listing",args);break;case"paid":redirectURL=EbayCompanion.Constants.getUrl("postLogin","listing",{itemid:itemId});args={itemid:itemId,ru:encodeURIComponent(redirectURL)};url=EbayCompanion.Constants.getUrl(aArea,aButtonAction,args);url+="&ssPageName=MPR";if(aItem.transaction){url+="&transId="+aItem.transaction.get("transactionId");}
break;case"sent":redirectURL=EbayCompanion.Constants.getUrl("postLogin","listing",{itemid:itemId});args={itemid:itemId,ru:encodeURIComponent(redirectURL)};url=EbayCompanion.Constants.getUrl(aArea,aButtonAction,args);url+="&ssPageName=SHP";if(aItem.transaction){url+="&transId="+aItem.transaction.get("transactionId");}
break;case"feedback":if(aItem.get("sellerUserId").toLowerCase()==userId.toLowerCase()){args={itemid:itemId,useridto:aItem.transaction.get("buyerUserId"),useridfrom:userId};}else{args={itemid:itemId,useridto:aItem.get("sellerUserId"),useridfrom:userId};}
url=EbayCompanion.Constants.getUrl(aArea,aButtonAction,args);break;case"find":args={itemid:itemId,query:escape(aItem.get("title"))};url=EbayCompanion.Constants.getUrl(aArea,aButtonAction,args);break;case"viewFeedback":args={userid:userId};url=EbayCompanion.Constants.getUrl(aArea,"userFeedback",args);break;}
EbayCompanion.openRawURL(url,aEvent);}}catch(e){EbayCompanion.Logger.exception(e);}},showLicence:function(aUpgrade){try{if(aUpgrade){this._showUpgradeNotification();}}catch(e){EbayCompanion.Logger.exception(e);}},_showUpgradeNotification:function(){if(typeof(EbayCompanion.Notification)=="undefined"){this._importModule("objects/notification.js");}
if(typeof(EbayCompanion.InformationNotificationHelper)=="undefined"){this._importModule("helpers/informationNotificationHelper.js");}
let notification=new EbayCompanion.Notification(EbayCompanion.InformationNotificationHelper.TERMS_CONDITIONS_CHANGED_NOTIFICATION);notification.addLinkCallback(0,function(aEvent){EbayCompanion.showOptionsPanel(true);EbayCompanion.InformationNotificationHelper.dismissNotification(EbayCompanion.InformationNotificationHelper.TERMS_CONDITIONS_CHANGED_NOTIFICATION);});notification.set("content",EbayCompanion.Constants.stringBundle.getString("ecSidebar.notification.message.extensionUpdated"));notification.set("priority",1);EbayCompanion.InformationNotificationHelper.queueNotification(notification);},_showTermsNotification:function(){if(typeof(EbayCompanion.Notification)=="undefined"){this._importModule("objects/notification.js");}
if(typeof(EbayCompanion.InformationNotificationHelper)=="undefined"){this._importModule("helpers/informationNotificationHelper.js");}
let notification=new EbayCompanion.Notification(EbayCompanion.InformationNotificationHelper.TERMS_CONDITIONS_NOTIFICATION);notification.addLinkCallback(0,function(aEvent){EbayCompanion.showOptionsPanel(true,"terms");});notification.addLinkCallback(1,function(aEvent){EbayCompanion.showOptionsPanel(true,"privacy");});notification.set("content",EbayCompanion.Constants.stringBundle.getString("ecSidebar.notification.message.acceptTermsConditions"));notification.set("priority",1);EbayCompanion.InformationNotificationHelper.queueNotification(notification);},showOptionsPanel:function(showNewLegalTerms,goTo){var windowMediator=Cc["@mozilla.org/appshell/window-mediator;1"].getService(Ci.nsIWindowMediator);var optionsPanel=windowMediator.getMostRecentWindow("ebayComp:options");if(optionsPanel){optionsPanel.focus();if(showNewLegalTerms){optionsPanel.Options.showNewLegalTerms(goTo);}}else{let params={};if(showNewLegalTerms){params.showNewLegalTerms=true;if(goTo){params.goTo=goTo;}}
window.openDialog("chrome://ebaycompanion/content/options/options.xul","eBay-Options","chrome,titlebar,toolbar,centerscreen,"+
"dialog=no,resizable=yes",params);}},showNewMessagesNotification:function(aMessagesNumber){let stringBundle=EbayCompanion.Constants.stringBundle;if(aMessagesNumber>0){let message=(aMessagesNumber==1)?stringBundle.getString("ecSidebar.notification.message.email",[aMessagesNumber]):stringBundle.getString("ecSidebar.notification.message.email.plural",[aMessagesNumber]);if(typeof(EbayCompanion.Notification)=="undefined"){this._importModule("objects/notification.js");}
if(typeof(EbayCompanion.InformationNotificationHelper)=="undefined"){this._importModule("helpers/informationNotificationHelper.js");}
let notification=new EbayCompanion.Notification(EbayCompanion.InformationNotificationHelper.NEW_MESSAGES_NOTIFICATION);notification.addLinkCallback(0,function(aEvent){EbayCompanion.openPage(aEvent,"sidebarNotification","myMessages",{});EbayCompanion.InformationNotificationHelper.dismissNotification(EbayCompanion.InformationNotificationHelper.NEW_MESSAGES_NOTIFICATION);});notification.set("content",message);notification.set("priority",3);EbayCompanion.InformationNotificationHelper.queueNotification(notification);}},_showFeedbackChangedNotification:function(aDelta){let stringBundle=EbayCompanion.Constants.stringBundle;let deltaString=aDelta>0?"+"+aDelta:aDelta;let message=stringBundle.getString("ecSidebar.notification.message.feedback",[deltaString]);if(typeof(EbayCompanion.Notification)=="undefined"){this._importModule("objects/notification.js");}
if(typeof(EbayCompanion.InformationNotificationHelper)=="undefined"){this._importModule("helpers/informationNotificationHelper.js");}
let notification=new EbayCompanion.Notification(EbayCompanion.InformationNotificationHelper.FEEDBACK_NOTIFICATION);notification.addLinkCallback(0,function(aEvent){EbayCompanion.openPage(aEvent,"sidebarNotification","userFeedback",{userid:EbayCompanion.Datasource.activeAccount().get('userId')});EbayCompanion.InformationNotificationHelper.dismissNotification(EbayCompanion.InformationNotificationHelper.FEEDBACK_NOTIFICATION);});notification.set("content",message);notification.set("priority",3);EbayCompanion.InformationNotificationHelper.queueNotification(notification);},_updateSidebarFeedbackScore:function(aValue){if(this.isSidebarOpen()){let greetingWidget=document.getElementById("sidebar").contentDocument.getElementById("greeting-widget");greetingWidget.setAttribute("feedbackscore",aValue);}},openFeedbackPage:function(aEvent){let feedbackUrl="chrome://ebaycompanion/content/options/feedback/feedbackPane.html";this.openRawURL(feedbackUrl,aEvent);},openPage:function(aEvent,areaName,pageTemplateName,args){try{let url=null;let that=this;if(areaName=="ebayButton"){let toolbarbuttonActive=document.getElementById("ebayCompanionToolbarItem")!=undefined;areaName=toolbarbuttonActive?"toolbarButton":"statusbarButton";}
let reuseLoginTab=true;switch(pageTemplateName){case"loginPage":case"sandboxLoginPage":let useSandbox=pageTemplateName.indexOf("sandboxLoginPage")!=-1;let generateUrlCallback=function(aUrl){that.openAndReuseLoginTab(aUrl);};this.Datasource.generateLoginUrl(areaName,useSandbox,generateUrlCallback);break;default:url=EbayCompanion.Constants.getUrl(areaName,pageTemplateName,args);reuseLoginTab=false;break;}
if(url){if(!reuseLoginTab){this.openRawURL(url,aEvent);}}}catch(e){EbayCompanion.Logger.exception(e);}},openAndReuseLoginTab:function(url){var wm=Cc["@mozilla.org/appshell/window-mediator;1"]
.getService(Ci.nsIWindowMediator);var browserEnumerator=wm.getEnumerator("navigator:browser");var found=false;while(!found&&browserEnumerator.hasMoreElements()){var browserWin=browserEnumerator.getNext();var tabbrowser=browserWin.gBrowser;var numTabs=tabbrowser.browsers.length;for(var index=0;index<numTabs;index++){var currentBrowser=tabbrowser.getBrowserAtIndex(index);var checkUrl=EbayCompanion.Constants.isAuthAuthURL(currentBrowser.currentURI.spec);if(checkUrl==0||checkUrl==2){tabbrowser.selectedTab=tabbrowser.tabContainer.childNodes[index];browserWin.focus();currentBrowser.loadURI(url);found=true;break;}}}
if(!found){var recentWindow=wm.getMostRecentWindow("navigator:browser");if(recentWindow){recentWindow.delayedOpenTab(url,null,null,null,null);}
else{window.open(url);}}},openRawURL:function(aURL,aEvent,aForceNewTab){if(!aURL){EbayCompanion.Logger.error("Empty URL passed to openRawURL",EbayCompanion.Logger.DUMP_STACK);return;}
if(EbayCompanion.Constants.prefBranch.get("openPagesInNewTab")||aForceNewTab){window.openUILinkIn(aURL,"tab");}else{window.openUILink(aURL,aEvent);}
if(null!=aEvent){aEvent.stopPropagation();}},openSearchQuery:function(aEvent){let url=EbayCompanion.Constants.getUrl("searchBox","search",{query:getBrowserSelection()});if(aEvent.button==1){window.openUILinkIn(url,"tab");}else if(aEvent.button!=2){window.openUILinkIn(url,"tabshifted");}},_setDefaultWebSite:function(){let set=false;let chosenSite;try{chosenSite=EbayCompanion.Constants.prefBranch.get("chosenSite");if(chosenSite){set=true;}}catch(e){set=false;}
if(!set){try{let prefService=EbayCompanion.Constants.rootPrefService;let language=prefService.getCharPref("general.useragent.locale").toUpperCase();chosenSite=EbayCompanion.Constants.localeSiteDataSelector[language];if(!chosenSite){let languageArray=language.split("-");language=languageArray[0];chosenSite=EbayCompanion.Constants.localeSiteDataSelector[language];}
if(!chosenSite){chosenSite="US";}
EbayCompanion.Constants.prefBranch.set("chosenSite",chosenSite);}catch(e){EbayCompanion.Logger.error(e);EbayCompanion.Constants.prefBranch.set("chosenSite","US");}}},_openFirstRunPage:function(){this.openPage(null,'firstRun','firstRun',null);},_initeBayButton:function(){this._overwriteCustomizeDone();this._afterCustomizeDone();},_overwriteCustomizeDone:function(){let that=this;let originalCustomizeDone=BrowserToolboxCustomizeDone;BrowserToolboxCustomizeDone=function(toolboxChanged){originalCustomizeDone(toolboxChanged);that._afterCustomizeDone();};},_afterCustomizeDone:function(){let firefox4=EbayCompanion.Constants.isFirefox4;let toolbarButton=document.getElementById("ebayCompanionToolbarItem");let buttonInToolbar=EbayCompanion.Constants.prefBranch.get("buttonInToolbar");let buttonAddedToFF4Pref=EbayCompanion.Constants.prefBranch.get("buttonAddedToFF4");let buttonAddedToFF4=(buttonAddedToFF4Pref!=null&&true==buttonAddedToFF4Pref);if(null==toolbarButton){if(null==buttonInToolbar||(firefox4&&!buttonAddedToFF4)){this.showToolbarButton();if(firefox4){EbayCompanion.Constants.prefBranch.set("buttonAddedToFF4",true);}}else{EbayCompanion.Constants.prefBranch.set("buttonInToolbar",false);if(firefox4){this._showAddonBarButton();this._showStatusbarButton(false);}else{this._showStatusbarButton(true);}}}else{if(this._isButtonInMainToolbar()){EbayCompanion.Constants.prefBranch.set("buttonInToolbar",true);}else if(null==buttonInToolbar||buttonInToolbar){this.removeAddonBarButton();this.showToolbarButton();}else{if(firefox4){this._showAddonBarButton();this._showStatusbarButton(false);}else{this._showStatusbarButton(true);}}
this._showStatusbarButton(false);}
if(firefox4){let toolbarButtonBinding=document.getElementById("ec-toolbar-button");if(toolbarButtonBinding){toolbarButtonBinding.setAttribute("class","ec-toolbar-button-ff4");}}},_isButtonInMainToolbar:function(){let toolbar=document.getElementById("nav-bar");return(-1!=toolbar.currentSet.indexOf("ebayCompanionToolbarItem"));},showToolbarButton:function(){let toolbar=document.getElementById("nav-bar");if(-1==toolbar.currentSet.indexOf("ebayCompanionToolbarItem")){let newCurrentSet=null;if(-1!=toolbar.currentSet.indexOf("urlbar-container")){newCurrentSet=toolbar.currentSet.replace(/urlbar-container/,"ebayCompanionToolbarItem,urlbar-container");}else{newCurrentSet=toolbar.currentSet+",ebayCompanionToolbarItem";}
toolbar.setAttribute("currentset",newCurrentSet);toolbar.currentSet=newCurrentSet;document.persist("nav-bar","currentset");EbayCompanion.Constants.prefBranch.set("buttonInToolbar",true);try{BrowserToolboxCustomizeDone(true);}catch(e){}}},_showAddonBarButton:function(){let addonbar=document.getElementById("addon-bar");if(addonbar&&-1==addonbar.currentSet.indexOf("ebayCompanionToolbarItem")){let newCurrentSet=null;if(-1!=addonbar.currentSet.indexOf("urlbar-container")){newCurrentSet=addonbar.currentSet.replace(/urlbar-container/,"ebayCompanionToolbarItem,urlbar-container");}else{newCurrentSet=addonbar.currentSet+",ebayCompanionToolbarItem";}
addonbar.setAttribute("currentset",newCurrentSet);addonbar.currentSet=newCurrentSet;document.persist("addon-bar","currentset");EbayCompanion.Constants.prefBranch.set("buttonInToolbar",false);try{BrowserToolboxCustomizeDone(true);}catch(e){}
if(addonbar.collapsed){addonbar.collapsed=false;}}},removeAddonBarButton:function(){let addonbar=document.getElementById("addon-bar");if(addonbar&&-1!=addonbar.currentSet.indexOf("ebayCompanionToolbarItem")){let newCurrentSet=addonbar.currentSet.replace(/,?ebayCompanionToolbarItem/,"");addonbar.setAttribute("currentset",newCurrentSet);addonbar.currentSet=newCurrentSet;document.persist("addon-bar","currentset");if(""==addonbar.currentSet){addonbar.collapsed=true;}}},_showStatusbarButton:function(aValue){let statusbarButton=document.getElementById("gs-ebay-statusbar-panel");if(null!=statusbarButton){statusbarButton.hidden=!aValue;}},populateSellersMenu:function(){let menu=document.getElementById("ec-sellers-menu");let connected=EbayCompanion.Datasource.activeAccount()!=null;let signedOutItem=document.getElementById("ec-sellers-menu-signed-out");let noSellersItem=document.getElementById("ec-sellers-menu-sellers-null");let moreItem=document.getElementById("ec-sellers-menu-more");while(menu.firstChild!=signedOutItem){menu.removeChild(menu.firstChild);}
if(!connected){signedOutItem.removeAttribute("hidden");noSellersItem.setAttribute("hidden",true);moreItem.setAttribute("hidden",true);}else{signedOutItem.setAttribute("hidden",true);let favoriteSellers=EbayCompanion.Datasource.favoriteSellers();if(favoriteSellers.length==0){noSellersItem.removeAttribute("hidden");}else{noSellersItem.setAttribute("hidden",true);if(favoriteSellers.length<7){moreItem.setAttribute("hidden",true);}else{moreItem.removeAttribute("hidden");}
let seller;let sellerItem;let label;let sellerId;let storeName;for(let i=0;i<6&&i<favoriteSellers.length;i++){seller=favoriteSellers[i];sellerId=seller.get("sellerId");sellerItem=document.createElement("menuitem");sellerItem.setAttribute("sellerId",sellerId);let sellerCommand=function(event){EbayCompanion.openPage(event,'ebayButton','merchant',{userid:event.target.getAttribute("sellerId")});};sellerItem.addEventListener("command",sellerCommand,false);sellerItem.addEventListener("click",function(event){if(event.button==1){sellerCommand(event);closeMenus(sellerItem);}},false);label=sellerId
storeName=EbayCompanion.Constants.getUTF8(seller.get("storeName"));if(storeName&&storeName.length>0){label+=" ("+storeName+")";}
sellerItem.setAttribute("label",label);menu.insertBefore(sellerItem,signedOutItem);}}}},_onContentLoaded:function(event){const AUTH_URL_LOGIN=0;const AUTH_URL_INTERMEDIATE=1;const AUTH_URL_ACCEPT=2;const AUTH_URL_CANCEL=3;const REGULAR_URL_LOGIN=4;const ITEM_LISTED_URL=5;const ITEM_PURCHASED_URL=6;const EBAY_HOMEPAGE=7;const ITEM_OFFER_PLACED_URL=8;try{let url=String(event.target.location);let resultPageNum=EbayCompanion.Constants.isAuthAuthURL(url);let loginBrowser;switch(resultPageNum){case AUTH_URL_LOGIN:if(EbayCompanion.Datasource.activeAccount()&&this.isSidebarOpen()){if(url.indexOf("runame=")==-1||url.indexOf("runame=&")!=-1){let sidebar=document.getElementById("sidebar");let stringBundle=EbayCompanion.Constants.stringBundle;if(sidebar.contentDocument.getElementById("ebayCompanionSidebar")){if(typeof(EbayCompanion.Notification)=="undefined"){this._importModule("objects/notification.js");}
if(typeof(EbayCompanion.InformationNotificationHelper)=="undefined"){this._importModule("helpers/informationNotificationHelper.js");}
let notification=new EbayCompanion.Notification(EbayCompanion.InformationNotificationHelper.LOGIN_EXPLAIN_NOTIFICATION);notification.set("content",stringBundle.getString("ecSidebar.notification.message.security"));notification.set("priority",1);EbayCompanion.InformationNotificationHelper.queueNotification(notification);window.setTimeout(function(){EbayCompanion.InformationNotificationHelper.dismissNotification(notification.get("type"));},10000);}}}else if(this.isSidebarOpen()&&url.indexOf("errmsg")!=-1){EbayCompanion.Observers.notify(null,"ebay-sign-in-stop",null);}
break;case AUTH_URL_INTERMEDIATE:break;case AUTH_URL_ACCEPT:let username=EbayCompanion.Datasource.latestUsername();EbayCompanion.Logger.log("Signing in with the username: "+username+"\n");if(!username){EbayCompanion.Logger.error("Can't find username in Auth & Auth success URL: "+url);return;}
loginBrowser=gBrowser.getBrowserForDocument(event.target);let postLogin=function(){if(loginBrowser.contentDocument){let url=EbayCompanion.Constants.getUrl("postLogin","homePage");loginBrowser.contentDocument.location=url;}}
let isSandboxAccount=url.indexOf("sandbox")!=-1;let success=EbayCompanion.Datasource.loginUser(username,isSandboxAccount,postLogin);if(success){EbayCompanion.Observers.notify(null,"ebay-sign-in-start",null);loginBrowser.contentDocument.location="about:blank";}else{EbayCompanion.openPage(null,'ebayButton','loginPage',{});}
break;case AUTH_URL_CANCEL:window.getWebNavigation().stop(nsIWebNavigation.STOP_ALL);loginBrowser=gBrowser.getBrowserForDocument(event.target);if(loginBrowser.contentDocument){let url=EbayCompanion.Constants.getUrl("postLogin","homePage");loginBrowser.contentDocument.location=url;}
EbayCompanion.Observers.notify(null,"ebay-sign-in-stop",null);break;case REGULAR_URL_LOGIN:if(typeof(EbayCompanion.InformationNotificationHelper)=="undefined"){this._importModule("helpers/informationNotificationHelper.js");}
EbayCompanion.InformationNotificationHelper.dismissNotification(EbayCompanion.InformationNotificationHelper.LOGIN_EXPLAIN_NOTIFICATION);break;case ITEM_LISTED_URL:if(EbayCompanion.Datasource.activeAccount()){loginBrowser=gBrowser.getBrowserForDocument(event.target);if(loginBrowser&&loginBrowser.contentDocument){let loadedDoc=loginBrowser.contentDocument;let itemListedCongratsNodes=loadedDoc.evaluate("//form[@name='ListItemForSale']",loadedDoc,null,XPathResult.ANY_TYPE,null);let congratsNode=itemListedCongratsNodes.iterateNext();if(congratsNode){window.setTimeout(function(){if(typeof(EbayCompanion.ApiCoordinator)=="undefined"){EbayCompanion._importModule("apiCoordinator.js");}
EbayCompanion.ApiCoordinator.hardUpdate();},3000);}}}
break;case ITEM_PURCHASED_URL:if(EbayCompanion.Datasource.activeAccount()){loginBrowser=gBrowser.getBrowserForDocument(event.target);if(loginBrowser&&loginBrowser.contentDocument){let loadedDoc=loginBrowser.contentDocument;let itemPurchasedCheckoutFormNodes=loadedDoc.evaluate("//form[@name='CheckoutForm2']",loadedDoc,null,XPathResult.ANY_TYPE,null);let checkoutForm=itemPurchasedCheckoutFormNodes.iterateNext();if(checkoutForm){window.setTimeout(function(){if(typeof(EbayCompanion.ApiCoordinator)=="undefined"){EbayCompanion._importModule("apiCoordinator.js");}
EbayCompanion.ApiCoordinator.hardUpdate();},3000);}
let bidPlacedOutbidFormNodes=loadedDoc.evaluate("//form[@name='OutbidForm']",loadedDoc,null,XPathResult.ANY_TYPE,null);let outbidForm=bidPlacedOutbidFormNodes.iterateNext();if(outbidForm){window.setTimeout(function(){if(typeof(EbayCompanion.ApiCoordinator)=="undefined"){EbayCompanion._importModule("apiCoordinator.js");}
EbayCompanion.ApiCoordinator.clientAlertsUpdate();},10000);}}}
break;case EBAY_HOMEPAGE:if(EbayCompanion.Datasource.activeAccount()){window.setTimeout(function(){if(typeof(EbayCompanion.ApiCoordinator)=="undefined"){EbayCompanion._importModule("apiCoordinator.js");}
EbayCompanion.ApiCoordinator.clientAlertsUpdate();},5000);}
break;case ITEM_OFFER_PLACED_URL:window.setTimeout(function(){if(typeof(EbayCompanion.ApiCoordinator)=="undefined"){EbayCompanion._importModule("apiCoordinator.js");}
EbayCompanion.ApiCoordinator.hardUpdate();},3000);break;}}
catch(e){EbayCompanion.Logger.exception(e);}},_onMouseMove:function(aEvent){const AWAY_DETECTION_TIMEOUT=20*1000;if(this._mouseMoveTimeout){window.clearTimeout(this._mouseMoveTimeout);}
this.userIsAway=false;this._mouseMoveTimeout=window.setTimeout(let(that=this)function(){that.userIsAway=true;},AWAY_DETECTION_TIMEOUT);},_onFocus:function(aEvent){if(typeof(EbayCompanion.AlertsService)=="undefined"){this._importModule("alertsService.js");}
EbayCompanion.AlertsService.showCurrentAlerts();},addManagedEventListener:function(target,event,handler,useCapture){if(!this._latestManagedEventListenerId){this._latestManagedEventListenerId=0;}
if(!this._managedEventListeners){this._managedEventListeners=[];}
this._managedEventListeners[++this._latestManagedEventListenerId]={target:target,event:event,handler:handler,useCapture:useCapture};target.addEventListener(event,handler,useCapture);return this._latestManagedEventListenerId;},removeManagedEventListener:function(index){if(!this._managedEventListeners||!this._managedEventListeners[index]){EbayCompanion.Logger.error("Invalid managed event listener index",EbayCompanion.Logger.DUMP_STACK);return;}
let eventListener=this._managedEventListeners[index];eventListener.target.removeEventListener(eventListener.event,eventListener.handler,eventListener.useCapture);delete this._managedEventListeners[index];},removeAllManagedEventListeners:function(){if(!this._managedEventListeners){return;}
for each(let[index,]in Iterator(this._managedEventListeners)){this.removeManagedEventListener(index);}},_importModule:function(moduleName){try{Cu.import("resource://ebaycompanion/"+moduleName,EbayCompanion);}
catch(e){EbayCompanion.Logger.error("Unable to load module \""+moduleName+"\"");}}}
window.addEventListener("load",function(){EbayCompanion.init();},false);window.addEventListener("unload",function(){EbayCompanion.uninit();},false);