
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var yahooCI=Components.interfaces;var yahooCC=Components.classes;var loader=yahooCC["@mozilla.org/moz/jssubscript-loader;1"].getService(yahooCI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");loader.loadSubScript("chrome://ytoolbar/content/utils.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(yahooCI.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooPluginManager(){try{yahooDebug("loading YahooPluginManager()......");this.yLocalStorage=yahooCC["@yahoo.com/localstorage;1"].getService(yahooCI.nsIYahooLocalStorage);this.yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);this.yConfMgr=yahooCC["@yahoo.com/configmanager;1"].getService(yahooCI.nsIYahooConfigManager);this.yPluginCallback=yahooCC["@yahoo.com/yplugincallback;1"].getService(yahooCI.nsIYahooPluginCallback);this.yCache=yahooCC["@yahoo.com/ycache;1"].getService(yahooCI.nsIYahooCache);this.headerInfo="";this.Init();}catch(e){yahooError(e);}}
YahooPluginManager.prototype={plugInMap:[],headerInfo:"",attributeMap:"",buttonMap:"",plugIns:[],bWaiting:false,lastxmlResponse:"",lastURL:"",Init:function(){try{yahooDebug("Initializing YahooPluginManager()......");this.yObsSvc.addObserver(this,"yahoo-feed-updated",false);this.yObsSvc.addObserver(this,"yahoo-partner-update-call",false);this.yObsSvc.addObserver(this,"yahoo-browser_navigation-cancelled",false);this.yObsSvc.addObserver(this,"http-on-modify-request",false);this.headerInfo="<? xml version='1.0' encoding='UTF-8'?>";this.headerInfo+="<YTBRoot id='ytbHeader' version='1.0'><YTBHeader>";this.headerInfo+="<BrowserInfo><browser>FF</browser><version>3.1</version></BrowserInfo>";this.headerInfo+="<TBInfo><tbversion>"+this.yConfMgr.getCharValue("installer.version.simple")+"</tbversion>";this.headerInfo+="<country>"+this.yConfMgr.getCharValue("installer.country")+"</country>";this.headerInfo+="<language>"+this.yConfMgr.getCharValue("installer.language")+"</language>";this.headerInfo+="</TBInfo></YTBHeader></YTBRoot>";this.loadUnloadPartners();}catch(e){yahooError("YahooPluginManager::Init()::"+e);}},observe:function(aSubject,aTopic,aData){try{if(aTopic==="yahoo-feed-updated"){var thisPluginMgr=this;yahooUtils.setTimeout(function(){thisPluginMgr.loadUnloadPartners();},50);}
else if(aTopic==="yahoo-partner-update-call"){this.refreshPartnerButtons(aData)}
else if(aTopic==="yahoo-browser_navigation-cancelled"){this.onNavigationCancelled();}
else if(aTopic=="http-on-modify-request"){aSubject.QueryInterface(Components.interfaces.nsIHttpChannel);if(!(aSubject.loadFlags&aSubject.LOAD_INITIAL_DOCUMENT_URI))return;var url=aSubject.URI.spec;yahooDebug("requesting url = "+url);var bNavigate=this.onBeforeNavigate(url);if(!bNavigate){aSubject.cancel(Components.results.NS_BINDING_ABORTED);}}}catch(e){yahooError("YahooPluginManager::observe::"+e);}},loadPartnerPlugIn:function(CLSID){var _partnerBridge=null;try{_partnerBridge=yahooCC["@yahoo.com/ytbxpcom;1"].createInstance(yahooCI.nsIYTBXPCOM);if(_partnerBridge!=null){_partnerBridge.Init(CLSID,this.yPluginCallback);this.plugIns.push(_partnerBridge);}}catch(e){yahooError("YahooPluginManager::loadPartnerPlugIn::"+e);}
return _partnerBridge;},loadUnloadPartners:function(){try{yahooDebug("PlugInManager.loadUnloadPartners()................");if(this.yConfMgr.getCharValue("ypluginids")!=""){yahooDebug("Found PluginIDs "+this.yConfMgr.getCharValue("ypluginids"));this.plugInMap=this.yConfMgr.getCharValue("ypluginids").split(",");}
try{for(var idx=0;idx<this.plugInMap.length;idx++){if(!this.isPartnerLoaded(this.plugInMap[idx])){var _partnerBridge=yahooCC["@yahoo.com/ytbxpcom;1"].createInstance(yahooCI.nsIYTBXPCOM);yahooDebug("*****Created a new XPCOM bridge for Partner.");if(_partnerBridge!=null){yahooDebug("***** Loading and initializing Partner Plugin with CLSID: "+this.plugInMap[idx]);_partnerBridge.Init(this.plugInMap[idx],this.yPluginCallback);this.plugIns.push(_partnerBridge);yahooDebug("***** Partner Plugin with CLSID: "+this.plugInMap[idx]+" initialized successfully.");}else{yahooDebug("Failed to create XPCOM Bridge...");}}}}catch(e){yahooError("YahooPluginManager::loadUnloadPartners.PartnerBridge().Init()"+e);}
this.unloadPartners(false);this.refreshAllPartners();}catch(e){yahooError("YahooPluginManager::loadUnloadPartners()"+e);}},unloadPartners:function(bAllPartners)
{try{if(bAllPartners){for(var idx=0;idx<this.plugIns.length;idx++){this.plugIns[idx].Destroy();}}}catch(e){yahooError(e);}},isPartnerLoaded:function(CLSID){try{yahooDebug("isPartnerLoaded() CLSID : "+CLSID);var isLoaded=false;for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();try{this.plugIns[idx].GetPartnerID(this_clsid);if(this_clsid.value===CLSID){yahooDebug("Partner with CLSID = "+CLSID+" is already loaded.");isLoaded=true;break;}}catch(e1){yahooError(e1);}}}catch(e){yahooError(e);}
return isLoaded;},getPlugIn:function(CLSID){var oPlugIn=null;try{for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();try{this.plugIns[idx].GetPartnerID(this_clsid);if(this_clsid.value===CLSID){oPlugIn=this.plugIns[idx];}}catch(e1){yahooError(e1);}}}catch(e){yahooError(e);}
return oPlugIn;},refreshPartnerButtons:function(CLSID){try{yahooDebug("PlugInManager:refreshPartnerButtons()...with CLSID = "+CLSID);this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){var buttonData=new Object();var this_clsid=new Object();oPlugIn.GetPartnerID(this_clsid);var buttoninfo=this.getPartnerButtonXML(this_clsid.value);oPlugIn.GetData(this.headerInfo,buttoninfo,buttonData);this.lastxmlResponse=buttonData.value;this.saveButtonXML("");this.parseData(CLSID,buttonData.value);}
this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);if(this.buttonMap.length<=18){yahooDebug("No Buttons found....");}else{yahooDebug("Notifying observers about 'yahoo-partner-ui-updated'");yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},5);}}catch(e){yahooError(e);}},refreshAllPartners:function(){try{yahooDebug("PlugInManager:refreshAllPartners()................");var key="";this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";if(this.plugIns.length<=0){yahooDebug("No Partner Plug-ins are loaded in memory...exiting...");return;}
for(var idx=0;idx<this.plugIns.length;idx++){yahooDebug("retrieving Partner data from Partner PlugIn.....");try{var buttonData=new Object();var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var buttoninfo=this.getPartnerButtonXML(this_clsid.value);this.plugIns[idx].GetData(this.headerInfo,buttoninfo,buttonData);this.lastxmlResponse=buttonData.value;this.saveButtonXML("");this.parseData(this_clsid.value,buttonData.value);}catch(e1){yahooError(e1);}}
this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);if(this.buttonMap.length<=18){yahooDebug("No Buttons found....");}else{yahooDebug("Notifying observers about 'yahoo-partner-ui-updated'");yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},5);}}catch(e){yahooError(e);}},parseData:function(CLSID,buttonXML){try{yahooDebug("YahooPluginManager::praseData().......");var xmlParser=yahooCC["@mozilla.org/xmlextras/domparser;1"].createInstance(yahooCI.nsIDOMParser);var xmlButton=xmlParser.parseFromString(buttonXML,"text/xml");if(xmlButton.tagName==="parserError"){yahooDebug("Error in parsing Button XML");return;}
var buttons=xmlButton.getElementsByTagName("YButton");for(var idx=0;idx<buttons.length;idx++)
{var button=buttons[idx];this.addToAttributeMap(CLSID,button);var menus=button.getElementsByTagName("YMenu");for(var idxMenu=0;idxMenu<menus.length;idxMenu++){var menu=menus[idxMenu];var parentId=menu.parentNode.getAttribute("id");this.buttonMap+="{ \"id\" : \"yahoo-toolbar-"+parentId+"\" , \"childNodes\" : [";var menuitems=menu.getElementsByTagName("YMenuItem");var menuitemIds="";for(var idy=0;idy<menuitems.length;idy++){var menuitem=menuitems[idy];if(parentId==menuitem.parentNode.parentNode.getAttribute("id")){if(idy>0)menuitemIds+=",";var mType=menuitem.getAttribute("type");if(mType==null||mType==""){mType="item";}
menuitemIds+="\""+mType+"&&"+"yahoo-toolbar-"+menuitem.getAttribute("id")+"\"";this.addToAttributeMap(CLSID,menuitem);}}
menuitemIds=(menuitemIds!="")?menuitemIds:"\"null\"";this.buttonMap+=menuitemIds+"]},";}}}catch(e){yahooError(e);}},addToAttributeMap:function(CLSID,node){var attMap="";var yURL="";var yFunc="31";var yEvent="";var yTrack="";try{if(node.tagName=="YButton"||node.tagName=="YMenuItem"){attMap="{ \"id\" : \"yahoo-toolbar-"+node.getAttribute("id")+"\" , \"attmap\" : [";attMap+="\""+"image"+"%%"+node.getAttribute("icon")+"\"";attMap+=",\""+"label"+"%%"+node.getAttribute("text")+"\"";attMap+=",\""+"tooltiptext"+"%%"+node.getAttribute("tooltip")+"\"";attMap+=",\""+"visible"+"%%"+node.getAttribute("visible")+"\"";if(node.getAttribute("icon")){this.yCache.prefetchURI(node.getAttribute("icon"),true);}
var handler=node.getElementsByTagName("YTBEvent")[0];if(handler){var type=handler.getElementsByTagName("eventType")[0];var handlerType="";if(type){handlerType=type.firstChild.nodeValue}
if(handlerType=="YTB"){yFunc="36";}else if(handlerType=="YAF"){yFunc="502";}else{yFunc="31";}
var customArgs="";var eventArgs=handler.getElementsByTagName("eventArgs")[0];if(eventArgs){var Args=eventArgs.getElementsByTagName("Arg");for(var idx=0;idx<Args.length;idx++){var Arg=Args[idx];customArgs+=Arg.getAttribute("name")+"^";customArgs+=Arg.getAttribute("value")+"^^";if(Arg.getAttribute("name")=="url"){yURL=Arg.getAttribute("value");}}
customArgs=customArgs.substr(0,customArgs.length-2);attMap+=",\""+"yevntArgs"+"%%"+customArgs+"\"";}}else{}
yTrack="178060853/"+node.getAttribute("id");yEvent=","+yFunc+","+yTrack+","+yURL;attMap+=",\""+"oncommand"+"%%"+"yahooButtonHandler(event);"+"\"";attMap+=",\""+"yevent"+"%%"+yEvent+"\"";attMap+=",\""+"ytrack"+"%%"+yTrack+"\"";attMap+=",\""+"yurl"+"%%"+yURL+"\"";attMap+=",\""+"yfunc"+"%%"+yFunc+"\"";attMap+=",\""+"yplgin"+"%%"+CLSID+"\"";attMap+="]},";this.attributeMap+=attMap;}}catch(e){yahooError(e);}},getInterface:function(InterfaceID){var XPCOMObject=null;try{yahooDebug("Interface requested by bridge:"+InterfaceID);var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);yahooDebug("created a nsIWindowMediator");var navWin=null;var navNav=null;switch(InterfaceID)
{case"nsIDOMWindowInternal":navWin=wm.getMostRecentWindow("navigator:browser");XPCOMObject=navWin;break;case"nsIDOMWindow":navWin=wm.getMostRecentWindow("navigator:browser");if(navWin.top==null){yahooDebug("got a null nsIDOMWindow");}
XPCOMObject=navWin.top;break;case"nsIWebNavigation":navWin=wm.getMostRecentWindow("navigator:browser");navNav=navWin.QueryInterface(nsIInterfaceRequestor).getInterface(nsIWebNavigation);XPCOMObject=navNav;break;default:XPCOMObject=null;break;}}catch(e){yahooError(e);}
return XPCOMObject;},handleAction:function(EventSource,CLSID,EventArgs){try{var xmlEventArgs="";EventSource=EventSource.replace("yahoo-toolbar-","");xmlEventArgs+="<?xml version='1.0' encoding='UTF-8'?>";xmlEventArgs+="<YTBRoot id='EventArgs' version='1.0'>";xmlEventArgs+="<YTBEvent>";xmlEventArgs+="<eventSource>"+EventSource+"</eventSource>";xmlEventArgs+="<eventType>UI</eventType>";xmlEventArgs+="<eventID>ONCLICK</eventID>";if(EventArgs!==null&&EventArgs!==""){xmlEventArgs+="<eventArgs>";var customArgs=EventArgs.split("^^");for(idx=0;idx<customArgs.length;idx++){xmlEventArgs+="<Arg name='"+customArgs[idx].split("^")[0]+"' value='"+customArgs[idx].split("^")[1]+"' />"}
xmlEventArgs+="</eventArgs>";}
xmlEventArgs+="</YTBEvent></YTBRoot>";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){yahooDebug("passing event to Partner Plugin with data :"+xmlEventArgs);var retVal=oPlugIn.HandleAction("ONCLICK",xmlEventArgs);}}catch(e){yahooError(e);}},onBrowserEvents:function(EventID,CLSID,EventArgs){var bretVal=true;try{var xmlEventArgs="";xmlEventArgs+="<?xml version='1.0' encoding='UTF-8'?>";xmlEventArgs+="<YTBRoot id='EventArgs' version='1.0'>";xmlEventArgs+="<YTBEvent>";xmlEventArgs+="<eventSource>BROWSER</eventSource>";xmlEventArgs+="<eventType>BROWSER</eventType>";xmlEventArgs+="<eventID>"+EventID+"</eventID>";if(EventArgs!==null&&EventArgs!==""){xmlEventArgs+="<eventArgs>";var customArgs=EventArgs.split("^^");for(idx=0;idx<customArgs.length;idx++){xmlEventArgs+="<Arg name='"+customArgs[idx].split("^")[0]+"' value='"+customArgs[idx].split("^")[1]+"' />"}
xmlEventArgs+="</eventArgs>";}
xmlEventArgs+="</YTBEvent></YTBRoot>";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){yahooDebug("Bubbling up EventID = "+EventID+" EventArgs = "+xmlEventArgs+" to Plugin("+CLSID+")");try{var retVal=oPlugIn.HandleAction(EventID,xmlEventArgs);}catch(e1){yahooDebug(e1);bretVal=false;}}else{yahooDebug("CLSID "+CLSID+" not found...");}}catch(e){yahooError(e);}
return bretVal;},onBeforeNavigate:function(URL){try{var retVal=true;if(URL==="about:blank"){URL=this.yPluginCallback.getValue("url");}
yahooDebug("PluginManager.onBeforeNavigate().....URL = "+URL);this.lastURL=URL;for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var key=this_clsid.value+"_BROWSEREVENTS";var browser_events=(this.yLocalStorage.getString(key)==null)?false:this.yLocalStorage.getString(key);browser_events=true;if(browser_events&&!this.bWaiting){this.bWaiting=true;var EventArgs="url^"+URL;retVal=this.onBrowserEvents("BEFORENAVIGATE",this_clsid.value,EventArgs);this.bWaiting=false;}
if(!retVal){yahooDebug("Navigation stopped by partner...");break;}}
if(!retVal){yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-browser_navigation-cancelled",null);},50);}
return retVal;}catch(e){yahooError(e);}},onNavigationCancelled:function(){try{yahooDebug("PluginManager.onNavigationCancelled() event.....");for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var key=this_clsid.value+"_BROWSEREVENTS";var browser_events=(this.yLocalStorage.getString(key)==null)?false:this.yLocalStorage.getString(key);browser_events=true;if(browser_events){var retVal=this.onBrowserEvents("BEFORENAVIGATECANCELLED",this_clsid.value,null);}}}catch(e){yahooError(e);}},onTabChange:function(){try{yahooDebug("PluginManager::onTabChange");var pluginID=this.yConfMgr.getCharValue("ypluginids").split(",")[0];var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var navWin=wm.getMostRecentWindow("navigator:browser");var topWinBrowser=navWin.getBrowser();var partnerxml=topWinBrowser.getBrowserForTab(topWinBrowser.selectedTab).getAttribute("ytbPartnerxml");yahooDebug("found partner xml = "+partnerxml);if(partnerxml&&partnerxml!==""){if(pluginID!==""){this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";this.parseData(pluginID,partnerxml);this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);if(this.buttonMap.length<=18){}else{yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},5);}}}}catch(e){yahooError(e);}},addToPlugInMap:function(ButtonID,ButtonHash){try{var key="";var oBtnHash=yahooUtils.JSON.parse(ButtonHash);var _clsID=oBtnHash.partner_clsid.replace(/%2D/g,"-");var pluginIDs=this.yConfMgr.getCharValue("ypluginids");if(pluginIDs!=""){if(!(pluginIDs.indexOf(_clsID)>-1))
pluginIDs+=","+_clsID;}else{pluginIDs+=_clsID;}
this.yConfMgr.setCharValue("ypluginids",pluginIDs,true);var _interfaces=(this.yLocalStorage.getString(_clsID)==null)?"":this.yLocalStorage.getString(_clsID);if(oBtnHash.yinterface){_interfaces+=","+oBtnHash.yinterface;this.yLocalStorage.putString(_clsID,_interfaces);}
this.yConfMgr.setCharValue("partner.hash",ButtonHash,true);var key=ButtonID+"^"+_clsID;this.yObsSvc.notifyObservers(null,"yahoo-partner-ui-found",key);}catch(e){yahooError(e);}},getPartnerButtonXML:function(CLSID){try{var key="toolbar."+CLSID;return this.yConfMgr.getCharValue(key);}catch(e){yahooError(e);}},refreshDOM:function(xmlData){try{yahooDebug("PlugInManager:testFunction()");this.attributeMap="{ \"buttons\" : [";this.buttonMap="{ \"buttonMap\" : [";this.parseData("{E5C3862E-5A85-4BFB-8926-8C09F22B7AD7}",xmlData);this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);yahooDebug("Attribute MAP : "+this.attributeMap);yahooDebug("Button MAP : "+this.buttonMap);if(this.buttonMap.length<=18){yahooDebug("No Buttons found....");}else{yahooDebug("Notifying observers about 'yahoo-partner-ui-updated'");yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},500);}}catch(e){yahooError(e);}},saveButtonXML:function(URL){try{var bTabFound=false;var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var browserEnumerator=wm.getEnumerator("navigator:browser");while(browserEnumerator.hasMoreElements()){var browserWindow=browserEnumerator.getNext();var browserInstance=browserWindow.getBrowser();var numTabs=browserInstance.tabContainer.childNodes.length;for(var index=0;index<numTabs;index++){var currentUrl=browserInstance.getBrowserAtIndex(index).currentURI.spec;if(currentUrl==this.lastURL){browserInstance.getBrowserAtIndex(index).setAttribute("ytbPartnerxml",this.lastxmlResponse);bTabFound=true;}}}
if(!bTabFound){var navWin=wm.getMostRecentWindow("navigator:browser");var topWinBrowser=navWin.getBrowser();var urlAddrBar=navWin.document.getElementById("urlbar").value;if(this.lastURL.indexOf(urlAddrBar)>=0){topWinBrowser.getBrowserForTab(topWinBrowser.selectedTab).setAttribute("ytbPartnerxml",this.lastxmlResponse);}}}catch(e){yahooError(e);}},isURLOpenInTab:function(URL){var isOpen=false;try{var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var browserEnumerator=wm.getEnumerator("navigator:browser");while(browserEnumerator.hasMoreElements()){var browserWindow=browserEnumerator.getNext();var browserInstance=browserWindow.getBrowser();var numTabs=browserInstance.tabContainer.childNodes.length;for(var index=0;index<numTabs;index++){var currentUrl=browserInstance.getBrowserAtIndex(index).currentURI.spec;if(currentUrl==URL){isOpen=true;}}}}catch(e){yahooError(e);}
return isOpen;},classID:Components.ID("{E6CB70A7-53C7-49F0-81B7-08D08220B362}"),contractID:"@yahoo.com/ypluginmanager;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIYahooPluginManager])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([YahooPluginManager]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([YahooPluginManager]);