/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */const Cc=Components.classes;const Ci=Components.interfaces;const Ce=Components.Exception;const Cr=Components.results;const Cu=Components.utils;var Options={init:function(){try{Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/constants.js");Cu.import("resource://ebaycompanion/datasource.js");this._populateSites();this._populatePreferenceNames();this._populateRegistrationSiteLabel();this._initLinkLabels();this._syncAlertEnabledBroadcasters();let platformIsMac=navigator.platform.match(/mac/i);if(platformIsMac){let prefWindow=document.getElementById("ebayOptions");this._macHackRequired=(prefWindow.currentPane.id!="licence-pane");if(this._macHackRequired){this._sizeWindowToContent();}}
if(window.arguments&&window.arguments[0].showNewLegalTerms){let goTo=window.arguments&&window.arguments[0].goTo;this.showNewLegalTerms(goTo);}}
catch(e){Logger.exception(e);}},uninit:function(){},resetAlerts:function(){try{let alertPreferences=document.getElementById("alert-preferences");let alertPrefCount=alertPreferences.childNodes.length;for(let i=0;i<alertPrefCount;i++){let pref=alertPreferences.childNodes[i];pref.value=pref.defaultValue;}
this._syncAlertEnabledBroadcasters();}
catch(e){Logger.exception(e);}},_syncAlertEnabledBroadcasters:function(){let alertPrefs=document.getElementById("alert-preferences");for(let i=0;i<alertPrefs.childNodes.length;i++){let prefElement=alertPrefs.childNodes[i];if(prefElement.id.indexOf("isEnabled")!=-1){this.setAlertRowEnabled(prefElement.value,prefElement.id);}}},alertEnabledClick:function(event){try{let checkbox=event.target;let alertEnabled=checkbox.checked;let prefName=checkbox.getAttribute("preference");this.setAlertRowEnabled(alertEnabled,prefName);}
catch(e){Logger.exception(e);}},setAlertRowEnabled:function(isEnabled,prefName){let broadcasterName=prefName.replace("alerts.","").replace(".isEnabled","").replace(".","-")+"-broadcaster";let broadcaster=document.getElementById(broadcasterName);if(!broadcaster){Logger.error("Preference '"+prefName+"' has no corresponding "+
"broadcaster (should be '"+broadcasterName+"')");}
broadcaster.setAttribute("disabled",!isEnabled);},_sizeWindowToContent:function(){if(this._macHackRequired){let licenceFrame=document.getElementById("licence-frame");licenceFrame.style.minHeight="0px";window.sizeToContent();licenceFrame.style.minHeight=null;}else{window.sizeToContent();}},showNewLegalTerms:function(goTo){let prefWindow=document.getElementById("ebayOptions");let licencePane=document.getElementById("licence-pane");prefWindow.showPane(licencePane);let newTermsBox=document.getElementById("licence-newTerms-box");newTermsBox.hidden=false;this._sizeWindowToContent();let goToSection=let(that=this)function(id){let licenceFrame=document.getElementById("licence-frame");let elem=licenceFrame.contentDocument.getElementById(id);elem.scrollIntoView(true);}
if(goTo){goToSection(goTo);}},_populatePreferenceNames:function(){let prefElements=document.getElementsByTagName("preference");let prefRoot=Constants.prefBranch.branchName();for(let i=0;i<prefElements.length;i++){let prefElement=prefElements[i];let shortName=prefElement.id;let fullName=prefRoot+shortName;prefElement.name=fullName;prefElement.value=prefElement.valueFromPreferences;prefElement.updateElements();}},_populateRegistrationSiteLabel:function(){let siteNameLabel=document.getElementById("preferredsite-regsitename");if(Datasource.activeAccount()){let label=siteNameLabel.value;let userId=Datasource.activeAccount().get("userId");let regSite=Datasource.activeAccount().get("registrationSite");let regSiteName=Constants.stringBundle.getString("ecOptions.general.country."+regSite);let newLabel=label.replace("#1",userId).replace("#2",regSiteName);siteNameLabel.value=newLabel;siteNameLabel.removeAttribute("hidden");}else{siteNameLabel.setAttribute("hidden",true);}},_populateSites:function(){let menulist=document.getElementById("preferredsite-menulist");let supportedSites=Constants.supportedSites();for(let i=0;i<supportedSites.length;i++){let siteName=Constants.stringBundle.getString("ecOptions.general.country."+supportedSites[i]);menulist.appendItem(siteName,supportedSites[i]);}},_initLinkLabels:function(){let label=document.getElementById("licence-info-label");let goToSection=let(that=this)function(id){let licenceFrame=document.getElementById("licence-frame");let elem=licenceFrame.contentDocument.getElementById(id);elem.scrollIntoView(true);}
let termsAction=let(that=this)function(event)goToSection("terms");let privacyAction=let(that=this)function(event)goToSection("privacy");this._explodeLabelWithLinks(label,[termsAction,privacyAction]);label=document.getElementById("licence-newTerms-label");let uninstallAction=let(that=this)function(event)goToSection("uninstall");this._explodeLabelWithLinks(label,[uninstallAction]);},_explodeLabelWithLinks:function(label,callbacks){let text=label.value;while(text.length>0){let element=label.cloneNode(false);if(text.charAt(0)=="["){let endIndex=text.indexOf("]");let left=text.slice(0,endIndex+1);let linkRe=/\[(\d+) (.*?)\]/g;linkRe.lastIndex=0;let results=linkRe.exec(left);let index=results[1];element.value=results[2];element.setAttribute("class","link");let callback=callbacks[index-1];if(callback){element.onclick=callback;}
text=text.slice(endIndex+1);}else{let endIndex=text.indexOf("[");if(endIndex==-1){endIndex=text.length;}
element.value=text.slice(0,endIndex);text=text.slice(endIndex);}
label.parentNode.appendChild(element);}
label.parentNode.removeChild(label);},printLicence:function(){let licenceFrame=document.getElementById("licence-frame");licenceFrame.contentWindow.print();},copySelectedLicenceText:function(event){try{let frame=document.getElementById("licence-frame");let text=frame.contentWindow.getSelection().toString();if(text==""){text=frame.contentDocument.body.textContent;}
let clipboard=Cc["@mozilla.org/widget/clipboardhelper;1"].getService(Ci.nsIClipboardHelper);clipboard.copyString(text);}
catch(e){Logger.exception(e);}}}
window.addEventListener("load",function(){Options.init();},false);window.addEventListener("unload",function(){Options.uninit();},false);