
var loader=Components.classes["@mozilla.org/moz/jssubscript-loader;1"].getService(Components.interfaces.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");const MAX_ERROR_PAGE_SIZE=512;var Yahoo404Converter={streamConverterlistener:null,errorUrl:null,navAssistBaseUrl:null,navAssistShown:false,errorPageSize:0,asyncConvertData:function(aFromType,aToType,aListener,aCtxt){this.streamConverterlistener=aListener;},convert:function(aFromStream,aFromType,aToType,aCtxt){return aFromStream;},onDataAvailable:function(aRequest,aContext,aInputStream,aOffset,aCount){try{this.errorPageSize=aOffset+aCount;if(this.navAssistShown===false&&(aOffset+aCount)<=MAX_ERROR_PAGE_SIZE){var sis=Components.classes["@mozilla.org/io/string-input-stream;1"].createInstance(Components.interfaces.nsIStringInputStream);var targetDocument=this.getNavAssistDocument();sis.setData(targetDocument,targetDocument.length);this.navAssistShown=true;this.streamConverterlistener.onDataAvailable(aRequest,aContext,sis,0,targetDocument.length);}
if(this.navAssistShown===false&&(aOffset+aCount)>MAX_ERROR_PAGE_SIZE)
this.streamConverterlistener.onDataAvailable(aRequest,aContext,aInputStream,aOffset,aCount);}
catch(e){yahooError(e);}},onStartRequest:function(aRequest,aContext){try{this.navAssistShown=false;this.errorPageSize=0;this.errorUrl=encodeURIComponent(aRequest.QueryInterface(Components.interfaces.nsIChannel).URI.spec);aRequest.contentType="text/html;charset=utf-8";this.streamConverterlistener.onStartRequest(aRequest,aContext);}
catch(e){yahooError(e);}},onStopRequest:function(aRequest,aContext,aStatusCode){try{if(this.errorPageSize<=MAX_ERROR_PAGE_SIZE&&this.navAssistShown===false){var sis=Components.classes["@mozilla.org/io/string-input-stream;1"].createInstance(Components.interfaces.nsIStringInputStream);var targetDocument=this.getNavAssistDocument();sis.setData(targetDocument,targetDocument.length);this.navAssistShown=true;this.streamConverterlistener.onDataAvailable(aRequest,aContext,sis,0,targetDocument.length);}
this.streamConverterlistener.onStopRequest(aRequest,aContext,aStatusCode);}
catch(e){yahooError(e);}},observe:function(aSubject,aTopic,aData){try{if(aTopic=="nsPref:changed"){var yconfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);if(yconfMgr.getBoolValue("general.navassist")){Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService).addObserver(ResponseContentTypeModifer,"http-on-examine-response",false);}
else{Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService).removeObserver(ResponseContentTypeModifer,"http-on-examine-response");}}
if(aTopic=="yahoo-feed-updated"){var yconfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var yahooLocalStorage=Components.classes["@yahoo.com/localstorage;1"].getService(Components.interfaces.nsIYahooLocalStorage);var navAssistParams=yahooLocalStorage.getObject("yahoo-toolbar-epa.yhash");if(navAssistParams){ResponseContentTypeModifer.errorsToTrap.splice(0,ResponseContentTypeModifer.errorsToTrap.length);navAssistParams=navAssistParams.wrappedJSObject.object;navAssistParams.errs=navAssistParams.errs.split("|");navAssistParams.errs.forEach(function(err){ResponseContentTypeModifer.errorsToTrap.push(parseInt(err));},this);var intl=yconfMgr.getCharValue("installer.language");if(!intl)intl='us';this.navAssistBaseUrl=navAssistParams.server;this.navAssistBaseUrl=this.navAssistBaseUrl.replace("__Domain_Prefix__",intl);this.navAssistBaseUrl=this.navAssistBaseUrl.replace(/\x01\$REG_sc\x01/,yconfMgr.getCharValue("toolbar.sc"));this.navAssistBaseUrl=this.navAssistBaseUrl.replace(/\x01\$REG_tc\x01/,yconfMgr.getCharValue("toolbar.tc"));this.navAssistBaseUrl=this.navAssistBaseUrl+"&.intl="+intl+"&.cv="+yconfMgr.getCharValue("installer.version");this.navAssistBaseUrl=unescape(this.navAssistBaseUrl);}}}
catch(e){yahooError(e);}},initialize:function(){try{var obsService=Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService);var yconfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var yahooLocalStorage=Components.classes["@yahoo.com/localstorage;1"].getService(Components.interfaces.nsIYahooLocalStorage);yconfMgr.addOnChangeListener("general.navassist",this);var intl=yconfMgr.getCharValue("installer.language");if(!intl)intl='us';ResponseContentTypeModifer.errorsToTrap.push(404);ResponseContentTypeModifer.errorsToTrap.push(512);this.navAssistBaseUrl="http://"+yahooLocalStorage.getString("yahoo.ytff.dataserver.url")+"/bh/v2/epa/?.sc="
+yconfMgr.getCharValue('toolbar.sc')
+"&.tc="+yconfMgr.getCharValue('toolbar.tc');+"&.intl="+intl;+"&.cv="+yconfMgr.getCharValue("installer.version");obsService.addObserver(this,"yahoo-feed-updated",false);if(yconfMgr.getBoolValue("general.navassist")){obsService.addObserver(ResponseContentTypeModifer,"http-on-examine-response",false);}}
catch(e){yahooError(e);}},uninitialize:function(){try{var obsService=Components.classes['@mozilla.org/observer-service;1'].getService(Components.interfaces.nsIObserverService);var yconfMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);obsService.removeObserver(this,"yahoo-feed-updated");if(yconfMgr.getBoolValue("general.navassist"))
obsService.removeObserver(this,"http-on-examine-response");}
catch(e){yahooError(e);}},getNavAssistDocument:function(){var retVal="";try{var iosvc=Components.classes["@mozilla.org/network/io-service;1"].getService(Components.interfaces.nsIIOService);var navAssistServerUrl=this.navAssistBaseUrl+"&url="+this.errorUrl+"&error="+ResponseContentTypeModifer.lastErr;var channel=iosvc.newChannel(navAssistServerUrl,0,null);var inputStream=channel.open();var sStream=Components.classes["@mozilla.org/scriptableinputstream;1"].createInstance(Components.interfaces.nsIScriptableInputStream);var size=0;sStream.init(inputStream);while((size=inputStream.available())){retVal+=sStream.read(size);}
sStream.close();}
catch(e){yahooError(e);}
return retVal;},QueryInterface:function(iid){if(iid.equals(Components.interfaces.nsISupports)||iid.equals(Components.interfaces.nsIYahooNavAssist)||iid.equals(Components.interfaces.nsIObserver)||iid.equals(Components.interfaces.nsIStreamConverter)||iid.equals(Components.interfaces.nsIStreamListener)||iid.equals(Components.interfaces.nsIRequestObserver)){return this;}
throw Components.results.NS_ERROR_NO_INTERFACE;}};var ResponseContentTypeModifer={errorsToTrap:[],lastErr:null,observe:function(aSubject,aTopic,aData){try{aSubject=aSubject.QueryInterface(Components.interfaces.nsIHttpChannel);this.errorsToTrap.forEach(function(err){if(aSubject.responseStatus==err){aSubject.contentType="text/y404";this.lastErr=err;}},this);}
catch(e){yahooError(e);}},QueryInterface:function(iid){if(iid.equals(Components.interfaces.nsISupports)||iid.equals(Components.interfaces.nsIObserver)){return this;}
throw Components.results.NS_ERROR_NO_INTERFACE;}};const YAHOO_404_CONVERSION="?from=text/y404&to=*/*";var NavAssistModule={YAHOO_404_CONVERTER_CONTRACTID:"@mozilla.org/streamconv;1"+YAHOO_404_CONVERSION,mCID:Components.ID("{2c5b1520-ec6d-11dd-ba2f-0800200c9a66}"),mFactory:{createInstance:function(outer,iid){if(outer!=null){throw Components.results.NS_ERROR_NO_AGGREGATION;}
if(iid.equals(Components.interfaces.nsISupports)||iid.equals(Components.interfaces.nsIYahooNavAssist)||iid.equals(Components.interfaces.nsIStreamConverter)||iid.equals(Components.interfaces.nsIStreamListener)||iid.equals(Components.interfaces.nsIRequestObserver)){return Yahoo404Converter;}
throw Components.results.NS_ERROR_INVALID_ARG;}},registerSelf:function(compMgr,fileSpec,location,type){var compMgr=compMgr.QueryInterface(Components.interfaces.nsIComponentRegistrar);compMgr.registerFactoryLocation(NavAssistModule.mCID,"Yahoo 404 Assist",NavAssistModule.YAHOO_404_CONVERTER_CONTRACTID,fileSpec,location,type);var catMgr=Components.classes["@mozilla.org/categorymanager;1"].getService(Components.interfaces.nsICategoryManager);catMgr.addCategoryEntry("@mozilla.org/streamconv;1",YAHOO_404_CONVERSION,NavAssistModule.YAHOO_404_CONVERTER_CONTRACTID,true,true);},unregisterSelf:function(compMgr,fileSpec,location){var catMgr=Components.classes['@mozilla.org/categorymanager;1'].getService(Components.interfaces.nsICategoryManager);catMgr.deleteCategoryEntry("@mozilla.org/streamconv;1",YAHOO_404_CONVERSION,true);},getClassObject:function(compMgr,cid,iid){if(!cid.equals(NavAssistModule.mCID))
throw Components.results.NS_ERROR_NO_INTERFACE;if(!iid.equals(Components.interfaces.nsIFactory))
throw Components.results.NS_ERROR_NOT_IMPLEMENTED;return NavAssistModule.mFactory;},canUnload:function(compMgr){return true;}}
function NSGetModule(compMgr,fileSpec){return NavAssistModule;}