
var yahooCI=Components.interfaces;var yahooCC=Components.classes;var loader=yahooCC["@mozilla.org/moz/jssubscript-loader;1"].getService(yahooCI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");loader.loadSubScript("chrome://ytoolbar/content/utils.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(yahooCI.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooPluginManager(){try{yahooDebug("loading YahooPluginManager()......");this.yLocalStorage=yahooCC["@yahoo.com/localstorage;1"].getService(yahooCI.nsIYahooLocalStorage);this.yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);this.yConfMgr=yahooCC["@yahoo.com/configmanager;1"].getService(yahooCI.nsIYahooConfigManager);this.yPluginCallback=yahooCC["@yahoo.com/yplugincallback;1"].getService(yahooCI.nsIYahooPluginCallback);this.headerInfo="";this.Init();}catch(e){yahooError(e);}}
YahooPluginManager.prototype={plugInMap:[],headerInfo:"",attributeMap:"",buttonMap:"",plugIns:[],Init:function(){try{yahooDebug("Initializing YahooPluginManager()......");this.yObsSvc.addObserver(this,"yahoo-feed-updated",false);this.yObsSvc.addObserver(this,"yahoo-partner-update-call",false);this.headerInfo="<? xml version='1.0' encoding='UTF-8'?>";this.headerInfo+="<YTBRoot id='ytbHeader' version='1.0'><YTBHeader>";this.headerInfo+="<BrowserInfo><browser>FF</browser><version>3.1 </version></BrowserInfo>";this.headerInfo+="<TBInfo><tbversion>"+this.yConfMgr.getCharValue("installer.version.simple")+"</tbversion>";this.headerInfo+="<country>"+this.yConfMgr.getCharValue("installer.country")+"</country>";this.headerInfo+="<language>"+this.yConfMgr.getCharValue("installer.language")+"</language>";this.headerInfo+="</TBInfo></YTBHeader></YTBRoot>";}catch(e){yahooError("YahooPluginManager::Init()::"+e);}},observe:function(aSubject,aTopic,aData){try{if(aTopic==="yahoo-feed-updated"){var thisPluginMgr=this;yahooDebug(" 'yahoo-feed-updated' event caught by Plugin Manager ");yahooUtils.setTimeout(function(){thisPluginMgr.loadUnloadPartners();},2000);}
else if(aTopic==="yahoo-partner-update-call"){yahooDebug(" 'yahoo-partner-update-call' event caught by Plugin Manager with CLSID: "+aData);this.refreshPartnerButtons(aData)}}catch(e){yahooError("YahooPluginManager::observe::"+e);}},loadUnloadPartners:function(){try{yahooDebug("PlugInManager.loadUnloadPartners()................");for(var idx=0;idx<this.plugInMap.length;idx++){if(!this.isPartnerLoaded(this.plugInMap[idx])){var _partnerBridge=yahooCC["@yahoo.com/ytbxpcom;1"].createInstance(yahooCI.nsIYTBXPCOM);if(_partnerBridge!=null){yahooDebug("***** Loading and Initializing Partner with CLSID: "+this.plugInMap[idx]);_partnerBridge.Init(this.plugInMap[idx],this.yPluginCallback);this.plugIns.push(_partnerBridge);}}}
this.unloadPartners(false);this.refreshAllPartners();}catch(e){yahooError(e);}},unloadPartners:function(bAllPartners)
{try{if(bAllPartners){for(var idx=0;idx<this.plugIns.length;idx++){this.plugIns[idx].Destroy();}}}catch(e){yahooError(e);}},isPartnerLoaded:function(CLSID){try{yahooDebug("isPartnerLoaded() CLSID : "+CLSID);var isLoaded=false;for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();try{this.plugIns[idx].GetPartnerID(this_clsid);if(this_clsid.value===CLSID){yahooDebug("Partner with CLSID = "+CLSID+" is already loaded.");isLoaded=true;break;}}catch(e1){yahooError(e1);}}}catch(e){yahooError(e);}
return isLoaded;},getPlugIn:function(CLSID){var oPlugIn=null;try{for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();try{this.plugIns[idx].GetPartnerID(this_clsid);if(this_clsid.value===CLSID){oPlugIn=this.plugIns[idx];}}catch(e1){yahooError(e1);}}}catch(e){yahooError(e);}
return oPlugIn;},refreshPartnerButtons:function(CLSID){try{yahooDebug("PlugInManager:refreshPartnerButtons()...with CLSID = "+CLSID);this.attributeMap="{ 'buttons' : [";this.buttonMap="{ 'buttonMap' : [";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){var buttonData=new Object();oPlugIn.GetData(this.headerInfo,"buttoninfo",buttonData);this.parseData(CLSID,buttonData.value);}
this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);yahooDebug("Attribute MAP : "+this.attributeMap);yahooDebug("Button MAP : "+this.buttonMap);yahooDebug("Notifying observers about 'yahoo-partner-ui-updated'");yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},500);}catch(e){yahooError(e);}},refreshAllPartners:function(){try{yahooDebug("PlugInManager:refreshAllPartners()................");this.attributeMap="{ 'buttons' : [";this.buttonMap="{ 'buttonMap' : [";for(var idx=0;idx<this.plugIns.length;idx++){yahooDebug("retrieving Partner data from Partner PlugIn.....");try{var buttonData=new Object();var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);this.plugIns[idx].GetData(this.headerInfo,"buttoninfo",buttonData);this.parseData(this_clsid.value,buttonData.value);}catch(e1){yahooError(e1);}}
this.attributeMap=this.attributeMap.substr(0,this.attributeMap.length-1);this.attributeMap+="]}";this.yLocalStorage.putString("yDOMAttributes",this.attributeMap);this.buttonMap=this.buttonMap.substr(0,this.buttonMap.length-1);this.buttonMap+="]}";this.yLocalStorage.putString("yPtnrBtnMap",this.buttonMap);yahooDebug("Attribute MAP : "+this.attributeMap);yahooDebug("Button MAP : "+this.buttonMap);yahooDebug("Notifying observers about 'yahoo-partner-ui-updated'");yahooUtils.setTimeout(function(){var yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);yObsSvc.notifyObservers(null,"yahoo-partner-ui-updated",null);},500);}catch(e){yahooError(e);}},parseData:function(CLSID,buttonXML){try{yahooDebug("inside praseData.......");var xmlParser=yahooCC["@mozilla.org/xmlextras/domparser;1"].createInstance(yahooCI.nsIDOMParser);var xmlButton=xmlParser.parseFromString(buttonXML,"text/xml");if(xmlButton.tagName==="parserError"){yahooDebug("Error in parsing Button XML");return;}
var buttons=xmlButton.getElementsByTagName("YButton");yahooDebug(buttons.length+" YButton elements found in the XML");for(var idx=0;idx<buttons.length;idx++)
{var button=buttons[idx];this.addToAttributeMap(CLSID,button);var menus=button.getElementsByTagName("YMenu");for(var idxMenu=0;idxMenu<menus.length;idxMenu++){var menu=menus[idxMenu];var parentId=menu.parentNode.getAttribute("id");this.buttonMap+="{ 'id' : 'yahoo-toolbar-"+parentId+"' , 'childNodes' : [";var menuitems=menu.getElementsByTagName("YMenuItem");var menuitemIds="";for(var idy=0;idy<menuitems.length;idy++){var menuitem=menuitems[idy];if(parentId==menuitem.parentNode.parentNode.getAttribute("id")){if(idy>0)menuitemIds+=",";var mType=menuitem.getAttribute("type");if(mType==null||mType==""){mType="item";}
menuitemIds+="'"+mType+"&&"+"yahoo-toolbar-"+menuitem.getAttribute("id")+"'";this.addToAttributeMap(CLSID,menuitem);}}
menuitemIds=(menuitemIds!="")?menuitemIds:"'null'";this.buttonMap+=menuitemIds+"]},";}}}catch(e){yahooError(e);}},addToAttributeMap:function(CLSID,node){var attMap="";var yURL="";var yFunc="31";var yEvent="";var yTrack="";try{if(node.tagName=="YButton"||node.tagName=="YMenuItem"){attMap="{ 'id' : 'yahoo-toolbar-"+node.getAttribute("id")+"' , 'attmap' : [";yahooDebug("adding to AttributeMAP for node id:=> "+node.getAttribute("id"));attMap+="'"+"icon"+"%%"+node.getAttribute("icon")+"'";attMap+=",'"+"label"+"%%"+node.getAttribute("text")+"'";attMap+=",'"+"tooltiptext"+"%%"+node.getAttribute("tooltip")+"'";attMap+=",'"+"visible"+"%%"+node.getAttribute("visible")+"'";var handler=node.getElementsByTagName("handler")[0];if(handler){yahooDebug("appending yhandler = "+handler.getAttribute("type"));if(handler.getAttribute("type")=="YTB"){yFunc="36";}else{yFunc="31";}
var customArgs="";var eventArgs=handler.getElementsByTagName("eventArgs")[0];if(eventArgs){var Args=eventArgs.getElementsByTagName("Arg");for(var idx=0;idx<Args.length;idx++){var Arg=Args[idx];customArgs+=Arg.getAttribute("name")+"^";customArgs+=Arg.getAttribute("value")+"^^";if(Arg.getAttribute("name")=="url"){yURL=Arg.getAttribute("value");}}
customArgs=customArgs.substr(0,customArgs.length-2);attMap+=",'"+"yevntArgs"+"%%"+customArgs+"'";}}else{yahooDebug("No handler found in UI id = '"+node.getAttribute("id")+"'");}
yTrack="178060853/"+node.getAttribute("id");yEvent=","+yFunc+","+yTrack+","+yURL;attMap+=",'"+"oncommand"+"%%"+"yahooButtonHandler(event);"+"'";attMap+=",'"+"yevent"+"%%"+yEvent+"'";attMap+=",'"+"ytrack"+"%%"+yTrack+"'";attMap+=",'"+"yurl"+"%%"+yURL+"'";attMap+=",'"+"yfunc"+"%%"+yFunc+"'";attMap+=",'"+"yplgin"+"%%"+CLSID+"'";attMap+="]},";this.attributeMap+=attMap;}}catch(e){yahooError(e);}},getInterface:function(InterfaceID){var XPCOMObject=null;try{yahooDebug("Interface requested by bridge:"+InterfaceID);var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);yahooDebug("created a nsIWindowMediator");var navWin=null;var navNav=null;switch(InterfaceID)
{case"nsIDOMWindowInternal":navWin=wm.getMostRecentWindow("navigator:browser");XPCOMObject=navWin;break;case"nsIDOMWindow":navWin=wm.getMostRecentWindow("navigator:browser");if(navWin.top==null){yahooDebug("got a null nsIDOMWindow");}
XPCOMObject=navWin.top;break;case"nsIWebNavigation":navWin=wm.getMostRecentWindow("navigator:browser");navNav=navWin.QueryInterface(nsIInterfaceRequestor).getInterface(nsIWebNavigation);XPCOMObject=navNav;break;default:XPCOMObject=null;break;}}catch(e){yahooError(e);}
return XPCOMObject;},handleAction:function(ButtonID,CLSID,EventArgs){try{var xmlEventArgs="";xmlEventArgs+="<?xml version='1.0' encoding='UTF-8'?>";xmlEventArgs+="<YTBRoot id='EventArgs' version='1.0'>";xmlEventArgs+="<YTBEvent>";xmlEventArgs+="<eventSource>"+ButtonID+"</eventSource>";xmlEventArgs+="<eventType>BROWSER</eventType>";xmlEventArgs+="<eventID>ONCLICK</eventID>";if(EventArgs!==null&&EventArgs!==""){xmlEventArgs+="<eventArgs>";var customArgs=EventArgs.split("^^");for(idx=0;idx<customArgs.length;idx++){xmlEventArgs+="<Arg name='"+customArgs[idx].split("^")[0]+"' value='"+customArgs[idx].split("^")[1]+"' />"}
xmlEventArgs+="</eventArgs>";}
xmlEventArgs+="</YTBEvent></YTBRoot>";var oPlugIn=this.getPlugIn(CLSID);if(oPlugIn){yahooDebug("passing event to Partner Plugin with data :"+xmlEventArgs);var retVal=oPlugIn.HandleAction(this.headerInfo,xmlEventArgs);}}catch(e){yahooError(e);}},onBeforeNavigate:function(URL){try{yahooDebug("PluginManager.OnBeforeNavigate()");var retVal=true;var xmlEventArgs="";xmlEventArgs+="<?xml version='1.0' encoding='UTF-8'?>";xmlEventArgs+="<YTBRoot id='EventArgs' version='1.0'>";xmlEventArgs+="<YTBEvent>";xmlEventArgs+="<eventSource>BROWSER</eventSource>";xmlEventArgs+="<eventType>BROWSER</eventType>";xmlEventArgs+="<eventID>BROWSER_BEFORENAVIGATE</eventID>";xmlEventArgs+="<eventArgs><Arg name='url' value="+URL+"></eventArgs>";xmlEventArgs+="</YTBEvent></YTBRoot>";for(var idx=0;idx<this.plugIns.length;idx++){var this_clsid=new Object();this.plugIns[idx].GetPartnerID(this_clsid);var key=this_clsid+"_BROWSEREVENTS";var browser_events=(this.yLocalStorage.getString(key)==null)?false:this.yLocalStorage.getString(key);if(browser_events){retVal=this.plugIns[idx].HandleAction(this.headerInfo,xmlEventArgs);}
if(!retVal){break;}}
return retVal;}catch(e){yahooError(e);}},addToPlugInMap:function(ButtonID,ButtonHash){try{if(this.yLocalStorage.getString("ypluginids")==null){this.yLocalStorage.putString("ypluginids","");}
var oBtnHash=yahooUtils.JSON.parse(ButtonHash);var _clsID=oBtnHash.yclsid;var pluginIDs=this.yLocalStorage.getString("ypluginids");if(pluginIDs!=""){if(!(pluginIDs.indexOf(_clsID)>0))
pluginIDs+=","+_clsID;}else{pluginIDs+=_clsID;}
yahooDebug("rewriting CLSIDs to localstorage with value = "+pluginIDs);this.yLocalStorage.putString("ypluginids",pluginIDs);var _interfaces=(this.yLocalStorage.getString(_clsID)==null)?"":this.yLocalStorage.getString(_clsID);if(oBtnHash.yinterface){_interfaces+=","+oBtnHash.yinterface;this.yLocalStorage.putString(_clsID,_interfaces);}}catch(e){yahooError(e);}},QueryInterface:function(iid){if(!iid.equals(Components.interfaces.nsIYahooPluginManager)&&!iid.equals(Components.interfaces.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function NSGetModule(compMgr,fileSpec){return{myCID:Components.ID("{E6CB70A7-53C7-49F0-81B7-08D08220B362}"),myProgID:"@yahoo.com/ypluginmanager;1",firstTime:true,registerSelf:function(compMgr,fileSpec,location,type){if(this.firstTime){this.firstTime=false;throw Components.results.NS_ERROR_FACTORY_REGISTER_AGAIN;}
compMgr=compMgr.QueryInterface(Components.interfaces.nsIComponentRegistrar);compMgr.registerFactoryLocation(this.myCID,"Yahoo! PluginManager",this.myProgID,fileSpec,location,type);yahooDebug("Registered ["+this.myProgID+"] >----> "+this.myCID);},getClassObject:function(compMgr,cid,iid){if(!cid.equals(this.myCID)){throw Components.results.NS_ERROR_NO_INTERFACE;}
if(!iid.equals(Components.interfaces.nsIFactory)){throw Components.results.NS_ERROR_NOT_IMPLEMENTED;}
return this.myFactory;},myFactory:{createInstance:function(outer,iid){if(outer!==null){throw Components.results.NS_ERROR_NO_AGGREGATION;}
return new YahooPluginManager().QueryInterface(iid);}},canUnload:function(compMgr){return true;}};}