/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */var EXPORTED_SYMBOLS=["UninstallManager"];const Cc=Components.classes;const Ci=Components.interfaces;const Cu=Components.utils;Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/constants.js");const TOPIC_ACTION_REQUESTED="em-action-requested";const TOPIC_QUIT_APPLICATION="quit-application";var UninstallManager={_observerService:null,_shouldUninstall:false,_init:function(){this._observerService=Cc["@mozilla.org/observer-service;1"].getService(Ci.nsIObserverService);this._observerService.addObserver(this,TOPIC_QUIT_APPLICATION,false);this._observerService.addObserver(this,TOPIC_ACTION_REQUESTED,false);try{Cu.import("resource://gre/modules/AddonManager.jsm");AddonManager.addAddonListener(this);}catch(ex){}},_cleanUp:function(){this._reportUninstall();this._deleteShortcut();this._removeDatabase();this._removeExtensionFolder();Constants.prefBranch.deleteBranch();},_uninit:function(){try{Cu.import("resource://gre/modules/AddonManager.jsm");AddonManager.removeAddonListener(this);}catch(ex){}},_removeExtensionFolder:function(){let installFolder;if(typeof(GlaxEbay)=="undefined"){Cu.import("resource://glaxebay/gsCommon.js");}
try{installFolder=GlaxEbay.getProfileDirectory();if(installFolder.exists()&&installFolder.isDirectory()){installFolder.remove(true);}}catch(e){Logger.error("_cleanUp. Error:\n"+e);if(installFolder.exists()){let directoryEntries=installFolder.directoryEntries;let entry=null;while(directoryEntries.hasMoreElements()){entry=directoryEntries.getNext();entry.QueryInterface(Ci.nsIFile);try{entry.remove(true);}catch(e){Logger.error("_cleanUp. Error:\n"+e);}}
try{installFolder.remove(true);}catch(e){Logger.error("_cleanUp. Error:\n"+e);}}}},_removeDatabase:function(){if(typeof(StorageHelper)=="undefined"){Cu.import("resource://ebaycompanion/helpers/storageHelper.js");}
try{StorageHelper.removeDatabase();}catch(e){if(typeof(ObjectsStorage)=="undefined"){Cu.import("resource://ebaycompanion/storage/objectsStorage.js");}
ObjectsStorage.removeTables();if(typeof(PropertiesStorage)=="undefined"){Cu.import("resource://ebaycompanion/storage/propertiesStorage.js");}
PropertiesStorage.removeTables();StorageHelper.doStatement("VACUUM");}},_reportUninstall:function(){if(typeof(Datasource)=="undefined"){Cu.import("resource://ebaycompanion/datasource.js");}
let activeAccount=Datasource.activeAccount();if(!activeAccount){Logger.log("No user signed in, using the first local account to send "+
"the uninstall request");if(typeof(ObjectsStorage)=="undefined"){Cu.import("resource://ebaycompanion/storage/objectsStorage.js");}
let localAccounts=ObjectsStorage.getAllAccounts();if(localAccounts.length>0){activeAccount=localAccounts[0];}}
if(activeAccount){let ebayAuthToken=activeAccount.get("token");let credentialsArray={eBayAuthToken:ebayAuthToken};if(typeof(TradingApi)=="undefined"){Cu.import("resource://ebaycompanion/apis/tradingApi.js");}
TradingApi.reportToolbarActivity("Uninstall",credentialsArray,activeAccount.get("isSandboxAccount"),reportUninstallCallback);}
let reportUninstallCallback=let(that=this)function(result){try{if(result.error){Logger.warning("Extension uninstall report reported errors");}else{Logger.log("Uninstall reported successfully");}}
catch(e){Logger.exception(e);}}},_deleteShortcut:function(){let directoryService=Cc["@mozilla.org/file/directory_service;1"].getService(Ci.nsIProperties);let shortcutFile=directoryService.get("Desk",Ci.nsIFile);let shortcutName=Constants.prefBranch.get("common.iconName");if(!Constants.prefBranch.get("common.icon")){shortcutName=Constants.stringBundle.getString("extensions.{62760FD6-B943-48C9-AB09-F99C6FE96088}.name");}
switch(Constants.getOperatingSystem()){case"MAC":shortcutFile.append(shortcutName+".app");break;case"WINDOWS":case"VISTA":case"WIN7":shortcutFile.append(shortcutName+".lnk");break;case"LINUX":shortcutFile.append(shortcutName);break;}
if(shortcutFile.exists()){shortcutFile.remove(true);}},onUninstalling:function(aItem){if(Constants.extensionId==aItem.id){this._shouldUninstall=true;}},onOperationCancelled:function(aItem){if(Constants.extensionId==aItem.id){this._shouldUninstall=false;}},observe:function(aSubject,aTopic,aData){switch(aTopic){case TOPIC_QUIT_APPLICATION:if(this._shouldUninstall){this._cleanUp();this._uninit();}
break;case TOPIC_ACTION_REQUESTED:aSubject.QueryInterface(Ci.nsIUpdateItem);if(Constants.extensionId==aSubject.id){switch(aData){case"item-cancel-action":if(this._shouldUninstall){this._shouldUninstall=false;}
break;case"item-uninstalled":this._shouldUninstall=true;break;}}
break;}}};(function(){this._init();}).apply(UninstallManager);