
var CI=Components.interfaces;var CC=Components.classes;var yahooCC=CC;var yahooCI=CI;var loader=yahooCC["@mozilla.org/moz/jssubscript-loader;1"].getService(yahooCI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/yprefs.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");var yahooDebug=ytbDebug;function YahooCnaManager(){try{this.localstorage=yahooCC["@yahoo.com/localstorage;1"].getService(yahooCI.nsIYahooLocalStorage);this.yahooConfMgr=yahooCC["@yahoo.com/configmanager;1"].getService(yahooCI.nsIYahooConfigManager),this.yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);this.timer=yahooCC["@mozilla.org/timer;1"].createInstance(yahooCI.nsITimer);this.mFileIO=yahooCC["@yahoo.com/fileio;1"].getService(yahooCI.nsIYahooFileIO2);this.VITALITY_ALERT_ID="206";this.alertCount=50;this.glowCNAButton=false;this.init();}catch(e){yahooError("Error in YahooCnaManager"+e);}}
YahooCnaManager.prototype={_mCNADataList:[],_mIndex:-1,_mIsTimerOn:false,_mIsOpenBar:true,_mIsCloseBar:false,_mCNAOpenbar:0,_mCNAEnableticker:true,_mCNAScrollinterval:5,_mCNAClosebarinterval:5,_mCNASource:true,glow:false,_mHasData:false,_mMaxTimestamp:0,_mIsNewMessage:false,init:function(){try{this._mCNAOpenbar=this.yahooConfMgr.getIntValue('cna.openbar');this._mCNAEnableticker=this.yahooConfMgr.getBoolValue('cna.enableticker');this._mCNAScrollinterval=this.yahooConfMgr.getIntValue('cna.scrollinterval');this._mCNAClosebarinterval=this.yahooConfMgr.getIntValue('cna.closebarinterval');this._mCNASource=this.yahooConfMgr.getBoolValue('cna.source.yahoo');this.yObsSvc.addObserver(this,"yahoo-feed-alerts-updated",false);this.yObsSvc.addObserver(this,"CNAButton-state-changed",false);this.yahooConfMgr.addOnChangeListener("cna",this);switch(this._mCNAOpenbar){case 0:this._mIsOpenBar=true;this._mIsCloseBar=false;break;case 1:this._mIsOpenBar=true;this._mIsCloseBar=true;break;default:this._mIsOpenBar=false;this._mIsCloseBar=false
break;}
this.showTicker=this._mIsOpenBar;if(this._mIsCloseBar){this.tickerCloseTime=this._mCNAClosebarinterval;}else{this.tickerCloseTime=0;}
this._refreshCNAdata();}catch(e){yahooError("YahooCnaManager::init()::"+e);}},getTicker:function(){try{this.tickerObject={};if(ytbCookieUtils.getBlindYID()=="default"){this.tickerObject.tickerURL=(this.dataObj&&this.dataObj.naglink)||"login.yahoo.com";this.tickerObject.tickertText=(this.dataObj&&this.dataObj.nagmsg)||'Sign in to see your messages &gt;&gt;';this.tickerObject.tickerIcon="chrome://ytoolbar/skin/standardinfo.png";this.tickerObject.isFade=false;}else{if(this._mCNASource&&((this._mIsNewMessage)||(!this._mCNAEnableticker&&this.glowCNAButton))){this.tickerObject.tickertText=(this.dataObj&&this.dataObj.ctanewmsg)||'You have new messages &gt;&gt;';this.tickerObject.tickerURL="don't open a new tab & direct navigate to CNA slideout"
this.tickerObject.tickerIcon="chrome://ytoolbar/skin/standardinfo.png";this._mIsNewMessage=false;this.tickerObject.isFade=false;}else{if(this._mIndex>=0&&this._mCNASource&&this._mCNAEnableticker&&this._mHasData){this.tickerObject.tickertText=this._mCNADataList[this._mIndex].mText;this.tickerObject.tickerURL=this._mCNADataList[this._mIndex].mUrl;this.tickerObject.tickerIcon=this._mCNADataList[this._mIndex].mIcon;this.tickerObject.isFade=true;}else{this.tickerObject.tickertText=(this.dataObj&&this.dataObj.ctaoldmsg)||'Click to view messages &gt;&gt;';this.tickerObject.tickerURL="don't open a new tab & direct navigate to CNA slideout";this.tickerObject.tickerIcon="chrome://ytoolbar/skin/standardinfo.png";this.tickerObject.isFade=false;}}}
return this.tickerObject;}catch(e){yahooError(e);}},observe:function(aSubject,aTopic,aData){try{if(aTopic==="yahoo-feed-alerts-updated"){this.dataObj=this.localstorage.getObject("yahoo-toolbar-popticker"+".yhash");if(this.dataObj!==null){this.dataObj=this.dataObj.wrappedJSObject.object;}
this._refreshCNAdata();if(ytbCookieUtils.getBlindYID()=="default"){this.CNAButtonStateChange(false);this.glow=false;}}
if(aTopic=="nsPref:changed"){this._mCNAOpenbar=this.yahooConfMgr.getIntValue('cna.openbar'),this._mCNAEnableticker=this.yahooConfMgr.getBoolValue('cna.enableticker'),this._mCNAScrollinterval=this.yahooConfMgr.getIntValue('cna.scrollinterval');this._mCNAClosebarinterval=this.yahooConfMgr.getIntValue('cna.closebarinterval');this._mCNASource=this.yahooConfMgr.getBoolValue('cna.source.yahoo');switch(this._mCNAOpenbar){case 0:this._mIsOpenBar=true;this._mIsCloseBar=false;break;case 1:this._mIsOpenBar=true;this._mIsCloseBar=true;break;default:this._mIsOpenBar=false;this._mIsCloseBar=false
break;}
this.showTicker=this._mIsOpenBar;if(this._mIsCloseBar){this.tickerCloseTime=this._mCNAClosebarinterval;}else{this.tickerCloseTime=0;}
if(this.glow){if(!this._mCNASource){this.CNAButtonStateChange(false);}else{this._mIsNewMessage=true;this.CNAButtonStateChange(true);}}
if(this._mCNASource&&this._mCNAEnableticker){this.timer.cancel();this._mIsTimerOn=false;this._startTimer();}else{this.timer.cancel();this._mIsTimerOn=false;this.yObsSvc.notifyObservers(null,"ticker-data-ready",null);}}}catch(e){yahooError("YahooCnaManager::observe::"+e);}},_refreshCNAdata:function(){this._mIndex=-1;try{if(ytbCookieUtils.getBlindYID()!="default"){var vObj=null;var vJSONObj=null;var vitalitydata;vObj=this.localstorage.getObject(this.VITALITY_ALERT_ID);if(vObj!=null){vObj=vObj.wrappedJSObject.object;if(vObj!=null){vitalitydata=vObj[1];}}
if(vitalitydata){vJSONObj=vitalitydata;}
if(vJSONObj&&vJSONObj.content.updates.length!=0){this._mCNADataList=[];this._mHasData=true;for(var i=0;i<vJSONObj.content.updates.length;i++){var _mdata={};_mdata.mUrl=vJSONObj.content.updates[i].link;try{_mdata.mText=vJSONObj.content.updates[i].description;if(_mdata.mText==null||_mdata.mText==""){_mdata.mText=vJSONObj.content.updates[i].title;}}catch(e){_mdata.mText=vJSONObj.content.updates[i].title;}
_mdata.mTimeStamp=parseInt(vJSONObj.content.updates[i].lastUpdated);_mdata.mIcon="http://us.i1.yimg.com/us.yimg.com/i/tb/icons/e/vitaevent.gif";this._mCNADataList.push(_mdata);}
if(this._mCNADataList.length>1)
{function sortByTimeStamp(a,b){return b.mTimeStamp-a.mTimeStamp;}
this._mCNADataList.sort(sortByTimeStamp);}
this.alertCount=this._mCNADataList.length;if(this._mCNADataList.length>10){this._mMaxNum=10;}else{this._mMaxNum=this._mCNADataList.length}
this._mMaxTimestamp=this._mCNADataList[0].mTimeStamp;this._saveMaxTimestamp();if(parseInt(this._mMaxNum)==1){this._changeTickerData();}else{if(!this._mIsTimerOn){this.timer.cancel();this._mIsTimerOn=false;this._startTimer();}}}else{this._mHasData=false;this._mCNADataList=[];this._mMaxTimestamp=0;if(this._mIsTimerOn){this.timer.cancel();this._mIsTimerOn=false;}
this.alertCount=this._mCNADataList.length;}}
else
{this._mHasData=false;this._mCNADataList=[];this._mMaxTimestamp=0;if(this._mIsTimerOn){this.timer.cancel();this._mIsTimerOn=false;}
this.alertCount=-1;}}catch(e){yahooError("YahooCnaManager::refresh_data()::"+e);}},_saveMaxTimestamp:function(){try{var maxTimeStamp=0;var userPrefFile=this.mFileIO.getUserCacheDir();userPrefFile.appendRelativePath("cnatimestamp");var fileContent=this.mFileIO.readFile(userPrefFile);if(fileContent){var prefJsonObj=yahooUtils.JSON.parse(fileContent);}
if(prefJsonObj){try{maxTimeStamp=prefJsonObj.CNAmaxtimestamp;}catch(e){maxTimeStamp=0;yahooError(e);}}
this.CNASource=this.yahooConfMgr.getBoolValue('cna.source.yahoo')
if(maxTimeStamp<this._mMaxTimestamp||this.glow){this.glow=true;maxTimeStamp=this._mMaxTimestamp;var prefJsonObj={"CNAmaxtimestamp":maxTimeStamp};try{this.mFileIO.writeFile(userPrefFile,yahooUtils.JSON.stringify(prefJsonObj));}
catch(e){yahooError(e);}
if(this._mCNASource){this._mIsNewMessage=true;this.CNAButtonStateChange(true);this.yObsSvc.notifyObservers(null,"do-open-close-tickerbar",null);}}}catch(e){yahooError("Error in is_new_data()"+e);}},CNAButtonStateChange:function(state){if(state){if(!this.glowCNAButton){this.glowCNAButton=true;this.glow=true;this.yObsSvc.notifyObservers(null,"CNAButton-state-changed",null);}}else{if(this.glowCNAButton){this.glowCNAButton=false;this.yObsSvc.notifyObservers(null,"CNAButton-state-changed",null);}}},_changeTickerData:function(){try{if(this._mCNAEnableticker&&this.showTicker&&this._mCNASource){this.tickerScrollTime=this._mCNAScrollinterval;}else{this.tickerScrollTime=0;}
if(!this._mIsNewMessage){if(this._mIndex==this._mMaxNum-1){this._mIndex=0;}else{this._mIndex++;}}
this.yObsSvc.notifyObservers(null,"ticker-data-ready",null);}catch(e){yahooError(e);}},_startTimer:function(){try{if((!this._mIsTimerOn)&&(this._mCNAScrollinterval>0)&&(this._mCNAEnableticker)&&(this._mCNASource)){var self=this;var callback={notify:function(timer){try{self._changeTickerData();}catch(e){yahooError(e);}}};self._changeTickerData();this.timer.initWithCallback(callback,this._mCNAScrollinterval*1000,this.timer.TYPE_REPEATING_PRECISE);this._mIsTimerOn=true;}else{this.yObsSvc.notifyObservers(null,"ticker-data-ready",null);}}catch(e){yahooError(e);}},QueryInterface:function(iid){if(!iid.equals(CI.nsIYahooCnaManager)&&!iid.equals(CI.nsISupports)&&!iid.equals(CI.nsIRunnable)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}}
function NSGetModule(compMgr,fileSpec){return{myCID:Components.ID("{5cc52d91-c06c-11dd-ad8b-0800200c9a66}"),myProgID:"@yahoo.com/cnamanager;1",firstTime:true,registerSelf:function(compMgr,fileSpec,location,type){if(this.firstTime){this.firstTime=false;throw Components.results.NS_ERROR_FACTORY_REGISTER_AGAIN;}
compMgr=compMgr.QueryInterface(CI.nsIComponentRegistrar);compMgr.registerFactoryLocation(this.myCID,"Yahoo! CNA Manager",this.myProgID,fileSpec,location,type);},getClassObject:function(compMgr,cid,iid){if(!cid.equals(this.myCID)){throw Components.results.NS_ERROR_NO_INTERFACE;}
if(!iid.equals(CI.nsIFactory)){throw Components.results.NS_ERROR_NOT_IMPLEMENTED;}
return this.myFactory;},myFactory:{createInstance:function(outer,iid){if(outer!=null){throw Components.results.NS_ERROR_NO_AGGREGATION;}
return new YahooCnaManager().QueryInterface(iid);}},canUnload:function(compMgr){return true;}};}