
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var CI=Components.interfaces;var CC=Components.classes;var observerService=CC['@mozilla.org/observer-service;1'].getService(CI.nsIObserverService);var loader=CC["@mozilla.org/moz/jssubscript-loader;1"].getService(CI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");const daysToMilliSecFactor=24*60*60*1000;const notifyEventName="yahoo-show-eventtip";const computeTimeInterval=1*daysToMilliSecFactor;const lastTipTimestampConfigKey="etp.lasttiptimestamp";const __INFINITE__=999999;function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(Components.interfaces.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};var eTriggerTypes={ET_INVALID:0,ET_MESSENGER_EXTERNAL_SIGNIN:1,ET_NAVCOMPLETE_REGEX:2,ET_USER_HIGHLIGHT_RIGHTCLK:3,ET_BUTTON_SHOWN:4,ET_ADD_FAVORITES:5,ET_TOOLBAR_INACTIVE:6,ET_BUTTON_FIRST_CLICK:7,ET_GROUP_BUTTON_OPENED:8,ET_ELAPSED_SINCE_INSTALL:9,ET_OVERFLOWING:10,ET_METRO_SYNC:11,ET_FEED_PARAM:12};var eAcceptTypes={AT_IGNORE:0,AT_TRUE:1,AT_FALSE:2};var eEventTypes={ET_URL_NAV:0,ET_BTN_CLICK:1,ET_LAYOUT:2,ET_TIMEOUT:3,ET_METRO_SYNC:4,ET_MORE_MENU:5,ET_INVALID:6};function CommonObjects(){this.urlProbe=CC["@yahoo.com/urlprobe;1"].getService(CI.nsIYahooUrlProbe);this.localstorage=CC["@yahoo.com/localstorage;1"].getService(CI.nsIYahooLocalStorage);this.confMgr=CC["@yahoo.com/configmanager;1"].getService(CI.nsIYahooConfigManager);this.fileIO=CC["@yahoo.com/fileio;1"].getService(CI.nsIYahooFileIO2);this.toolbarManager=null;this.daysSinceLastTip=-1;this.daysSinceInstall=-1;this.daysTBIsInactive=-1;this.tbUpgraded=false;this.tipsEnabled=true;};function tipUIData(){this.buttonId="grp_fav";this.tipUrl="";this.autoClose=0;this.tipRoll=[];}
function EventTip(dataObj){var _dataObj=dataObj;var _self=this;var _eventType=eEventTypes.ET_INVALID;var _stateData={};_stateData.triggerCondHit=0;_stateData.tipShown=false;_stateData.clicked=eAcceptTypes.AT_FALSE;this.triggerType=eTriggerTypes.ET_INVALID;this.tipId="";this.tipRoll=[];this.position="grp_fav";this.regex="";this.messengerStatus=0;this.btnId="";this.btnAvail=0;this.btnClicked=0;this.installSilencePeriod=0;this.lastTipSilencePeriod=0;this.autoClosePeriod=0;this.triggerConditionHitCnt=3;this.trigDaysSinceInstall=1;this.toolbarUsed=0;this.ignoreSilentPeriod=0;this.inactivityPeriod=0;this.customized=0;this.toolbarUpgraded=0;this.installType=0;this.loginStatus=0;this.portability=0;this.metroSync=0;this.showAlways=0;this.ignoreUserPref=0;this.feedParamName="";this.tipUrlParam=null;function _checkExceptionConditions(){try{var bRetVal=_dataObj.tipsEnabled;if(_self.ignoreUserPref===eAcceptTypes.AT_TRUE){bRetVal=true;}
if(bRetVal&&_self.btnAvail!==eAcceptTypes.AT_IGNORE){var recentWin=CC['@mozilla.org/appshell/window-mediator;1'].getService(CI.nsIWindowMediator).getMostRecentWindow("navigator:browser");var btnPresent=eAcceptTypes.AT_FALSE;if(_self.btnId.indexOf(';')>0){btnIds=_self.btnId.split(';');for(var i=0;i<btnIds.length;i++){btnPresent=btnPresent=recentWin.document.getElementById("yahoo-toolbar-"+btnIds[i])?eAcceptTypes.AT_TRUE:eAcceptTypes.AT_FALSE;}}else{btnPresent=recentWin.document.getElementById("yahoo-toolbar-"+_self.btnId)?eAcceptTypes.AT_TRUE:eAcceptTypes.AT_FALSE;}
bRetVal=(btnPresent==_self.btnAvail)?true:false;}
if(bRetVal&&_self.btnClicked!==eAcceptTypes.AT_IGNORE){bRetVal=(_stateData.clicked==_self.btnClicked)?true:false;}
if(bRetVal&&_self.customized!==eAcceptTypes.AT_IGNORE){var never_cust=(_dataObj.confMgr.getCharValue("toolbar.lastcust"))?eAcceptTypes.AT_FALSE:eAcceptTypes.AT_TRUE;bRetVal=(never_cust==_self.customized)?true:false;}
if(bRetVal&&_self.toolbarUsed!==eAcceptTypes.AT_IGNORE){var tbUsed=(_dataObj.confMgr.getCharValue("toolbar.lastuse"))?eAcceptTypes.AT_TRUE:eAcceptTypes.AT_FALSE;bRetVal=(tbUsed==_self.toolbarUsed)?true:false;}
if(bRetVal&&_self.toolbarUpgraded!==eAcceptTypes.AT_IGNORE){bRetVal=(_dataObj.tbUpgraded==_self.toolbarUpgraded)?true:false;}
if(bRetVal&&_self.loginStatus!==eAcceptTypes.AT_IGNORE){var currentLoginStatus=_dataObj.toolbarManager.isGuestMode()===true?eAcceptTypes.AT_FALSE:eAcceptTypes.AT_TRUE;bRetVal=(currentLoginStatus==_self.loginStatus)?true:false;}
if(bRetVal&&_self.portability!==eAcceptTypes.AT_IGNORE){var portSet=_dataObj.localstorage.getString("port")==="-1"?eAcceptTypes.AT_FALSE:eAcceptTypes.AT_TRUE;bRetVal=(portSet==_self.portability)?true:false;}
if(bRetVal&&_self.metroSync!==eAcceptTypes.AT_IGNORE){var metroSyncSet=_dataObj.localstorage.getString("metroexp")==="-1"?eAcceptTypes.AT_FALSE:eAcceptTypes.AT_TRUE;bRetVal=(metroSyncSet==_self.metroSync)?true:false;}}catch(e){yahooError(e);}
return bRetVal;};function _serializeJSON(){try{var jsonFilePath=_dataObj.toolbarManager.isGuestMode()?_dataObj.fileIO.getCacheDir():_dataObj.fileIO.getUserCacheDir();jsonFilePath.appendRelativePath("etp-"+_self.tipId+".json");var json=yahooUtils.JSON.stringify(_stateData);_dataObj.fileIO.writeFile(jsonFilePath,json);}catch(e){yahooError(e);}};function _deserializeJSON(){try{var jsonFilePath=_dataObj.toolbarManager.isGuestMode()?_dataObj.fileIO.getCacheDir():_dataObj.fileIO.getUserCacheDir();jsonFilePath.appendRelativePath("etp-"+_self.tipId+".json");var json=_dataObj.fileIO.readFile(jsonFilePath);_stateData=json?yahooUtils.JSON.parse(json):_stateData;}catch(e){yahooError(e);}};this.init=function(){try{switch(_self.triggerType){case eTriggerTypes.ET_NAVCOMPLETE_REGEX:_eventType=eEventTypes.ET_URL_NAV;_dataObj.urlProbe.addUrlNotifier(_self.regex);break;case eTriggerTypes.ET_BUTTON_SHOWN:case eTriggerTypes.ET_FEED_PARAM:_eventType=eEventTypes.ET_LAYOUT;break;case eTriggerTypes.ET_BUTTON_FIRST_CLICK:case eTriggerTypes.ET_GROUP_BUTTON_OPENED:_eventType=eEventTypes.ET_BTN_CLICK;break;case eTriggerTypes.ET_ELAPSED_SINCE_INSTALL:case eTriggerTypes.ET_TOOLBAR_INACTIVE:_eventType=eEventTypes.ET_TIMEOUT;break;case eTriggerTypes.ET_OVERFLOWING:_eventType=eEventTypes.ET_MORE_MENU;break;case eTriggerTypes.ET_METRO_SYNC:_eventType=eEventTypes.ET_METRO_SYNC;break;}
_deserializeJSON();}catch(e){yahooError(e);}};this.do_triggerTip=function(occurredEventType,data){var bRetVal=false;if(occurredEventType===eEventTypes.ET_BTN_CLICK){if(_self.btnId!=""&&data===("yahoo-toolbar-"+_self.btnId)){_stateData.clicked=eAcceptTypes.AT_TRUE;}}
if(_eventType===occurredEventType&&_stateData.tipShown===false){switch(_eventType){case eEventTypes.ET_BTN_CLICK:_stateData.clicked=eAcceptTypes.AT_TRUE;break;case eEventTypes.ET_URL_NAV:if(data.match(_self.regex)){if(++_stateData.triggerCondHit>=_self.triggerConditionHitCnt){bRetVal=true;}}
break;case eEventTypes.ET_LAYOUT:var topWin=CC['@mozilla.org/appshell/window-mediator;1'].getService(CI.nsIWindowMediator).getMostRecentWindow("navigator:browser");if(_self.triggerType===eTriggerTypes.ET_BUTTON_SHOWN&&topWin.document.getElementById("yahoo-toolbar-"+_self.btnId)){bRetVal=true;}else if(_self.triggerType===eTriggerTypes.ET_FEED_PARAM&&_dataObj.localstorage.getString(_self.feedParamName)){bRetVal=true;}
break;case eEventTypes.ET_TIMEOUT:if(_self.triggerType===eTriggerTypes.ET_ELAPSED_SINCE_INSTALL&&_dataObj.daysSinceInstall>=_self.trigDaysSinceInstall){bRetVal=true;}else if(_self.triggerType===eTriggerTypes.ET_TOOLBAR_INACTIVE&&_dataObj.daysTBIsInactive>=_self.inactivityPeriod){bRetVal=true;}
break;}
if(bRetVal&&_self.ignoreSilentPeriod!==eAcceptTypes.AT_TRUE){bRetVal=((_self.installSilencePeriod>=_dataObj.daysSinceInstall)||(_self.lastTipSilencePeriod>=_dataObj.daysSinceLastTip)?false:bRetVal);}
bRetVal=bRetVal?_checkExceptionConditions():bRetVal;if(bRetVal){_stateData.tipShown=(this.showAlways==eAcceptTypes.AT_TRUE?false:bRetVal);var date=new Date().toUTCString();_dataObj.confMgr.setCharValue(lastTipTimestampConfigKey,date,true);}}
_serializeJSON();return bRetVal;}};function yEventTipManager(){var _self=this;var _dataObj=new CommonObjects();var _trigTimerEval=true;var _timer=CC['@mozilla.org/timer;1'].createInstance(CI.nsITimer);var eventTipsCollection=[];_notifyShowTip=function(tip){try{var data=new tipUIData();data.buttonId=tip.position?tip.position:"grp_fav";data.autoClose=tip.autoClosePeriod;var protocol="https://";if(_dataObj.confMgr.isKeyPresent("disablehttps")&&_dataObj.confMgr.getBoolValue("disablehttps")){protocol="http://";}
var server_base=_dataObj.localstorage.getString("yahoo.ytff.dataserver.url");_dataObj.confMgr.isYahooKey=false;var debug_url=_dataObj.confMgr.getCharValue("yahoo.debug.slideoutUrl");if(debug_url){server_base=debug_url;}
data.tipUrl=protocol+server_base+"/bh/v8/tip/etp?.etp="+tip.tipId+"&.cv="+_dataObj.confMgr.getCharValue("installer.version.simple")+"&.intl="+_dataObj.confMgr.getCharValue("installer.language")+"&.pc="+_dataObj.confMgr.getCharValue("toolbar.pc");if(tip.tipUrlParam){var param=tip.tipUrlParam;var paramPos=param.indexOf("$PARAM_");var feedParam=_dataObj.localstorage.getString(param.substr(paramPos+7));param=param.substring(0,paramPos-1);data.tipUrl+="&"+param+feedParam;}
data.tipRoll=tip.tipRoll.slice();var recentTopWindow=CC['@mozilla.org/appshell/window-mediator;1'].getService(CI.nsIWindowMediator).getMostRecentWindow("navigator:browser");if(recentTopWindow.document.getElementById('yahoo-toolbar').getAttribute("collapsed")!="true")
{_dataObj.localstorage.putObject("yahoo-eventtip-"+tip.tipId,new WrapperClass(data));observerService.notifyObservers(null,notifyEventName,"yahoo-eventtip-"+tip.tipId);}}catch(e){yahooError(e);}};this.addEventTip=function(tipNode){try{var yhash=yahooUtils.JSON.parse(tipNode.hash);var installSilencePeriod=parseInt(yhash.silw?yhash.silw:1);var lastTipSilencePeriod=parseInt(yhash.silt?yhash.silt:5);var signedMode=_dataObj.toolbarManager.isGuestMode()?"0":"1";var createTip=yhash.sign?false:true;createTip=(yhash.sign&&yhash.sign!==signedMode)?false:true;if(createTip){for(var i=0;i<tipNode.childSize;i++){var etp=tipNode.getChild(i);var hash=yahooUtils.JSON.parse(etp.hash);var params=etp.funcUrl.split(",");createTip=hash.sign?false:true;createTip=(hash.sign&&hash.sign!==signedMode)?false:true;if(createTip){var evtTip=new EventTip(_dataObj);evtTip.triggerType=parseInt(params[0]);evtTip.btnId=params[1];evtTip.tipId=params[2];if(evtTip.tipId==="wlp")continue;if(params[3]){var j=i;do{var child=tipNode.getChild(++j);var chash=yahooUtils.JSON.parse(child.hash);var cparams=child.funcUrl.split(",");if(parseInt(cparams[0])===eTriggerTypes.ET_INVALID){var data=new tipUIData();data.buttonId=chash.pos?chash.pos:data.buttonId;var protocol="https://";if(_dataObj.confMgr.isKeyPresent("disablehttps")&&_dataObj.confMgr.getBoolValue("disablehttps")){protocol="http://";}
var server_base=_dataObj.localstorage.getString("yahoo.ytff.dataserver.url");_dataObj.confMgr.isYahooKey=false;var debug_url=_dataObj.confMgr.getCharValue("yahoo.debug.slideoutUrl");if(debug_url){server_base=debug_url;}
data.tipUrl=protocol+server_base+"/bh/v8/tip/etp?.etp="+cparams[2]+"&.cv="+_dataObj.confMgr.getCharValue("installer.version.simple")+"&.intl="+_dataObj.confMgr.getCharValue("installer.language")+"&.pc="+_dataObj.confMgr.getCharValue("toolbar.pc");data.autoClose=parseInt(chash.to?chash.to:data.autoClose);evtTip.tipRoll.unshift(data);i=j;}}while(parseInt(cparams[0])===eTriggerTypes.ET_INVALID);}
evtTip.position=(hash.pos?hash.pos:evtTip.position);evtTip.regex=(hash.rgx?hash.rgx.replace(/\/\//g,"\\/\\/"):evtTip.regex);evtTip.regex.replace(/__Domain_Prefix__/g,_dataObj.confMgr.getCharValue("installer.language"));evtTip.messengerStatus=parseInt(hash.msgr?hash.msgr:evtTip.messengerStatus);evtTip.btnAvail=parseInt(hash.avail?hash.avail:evtTip.btnAvail);evtTip.btnClicked=parseInt(hash.rep?hash.rep:evtTip.btnClicked);evtTip.installSilencePeriod=parseInt(hash.silw?hash.silw:installSilencePeriod);evtTip.lastTipSilencePeriod=parseInt(hash.silt?hash.silt:lastTipSilencePeriod)+parseInt(hash.silnt?hash.silnt:0);evtTip.autoClosePeriod=parseInt(hash.to?hash.to:evtTip.autoClosePeriod);evtTip.triggerConditionHitCnt=parseInt(hash.rghc?hash.rghc:evtTip.triggerConditionHitCnt);evtTip.trigDaysSinceInstall=parseInt(hash.elad?hash.elad:evtTip.trigDaysSinceInstall);evtTip.toolbarUsed=parseInt(hash.nu?hash.nu:evtTip.toolbarUsed);evtTip.ignoreSilentPeriod=parseInt(hash.igns?hash.igns:evtTip.ignoreSilentPeriod);evtTip.inactivityPeriod=parseInt(hash.inad?hash.inad:evtTip.inactivityPeriod);evtTip.customized=parseInt(hash.nc?hash.nc:evtTip.customized);evtTip.toolbarUpgraded=parseInt(hash.etup?hash.etup:evtTip.toolbarUpgraded);evtTip.installType=parseInt(hash.etbndl?hash.etbndl:evtTip.installType);evtTip.loginStatus=parseInt(hash.etsign?hash.etsign:evtTip.loginStatus);evtTip.portability=parseInt(hash.etportset?hash.etportset:evtTip.portability);evtTip.metroSync=parseInt(hash.metroexp?hash.metroexp:evtTip.metroSync);evtTip.showAlways=parseInt(hash.alshow?hash.alshow:evtTip.showAlways);evtTip.ignoreUserPref=parseInt(hash.etignoro?hash.etignoro:evtTip.ignoreUserPref);evtTip.feedParamName=(hash.etfeedpm?hash.etfeedpm:evtTip.feedParamName);evtTip.tipUrlParam=unescape(hash.etparam?hash.etparam:evtTip.tipUrlParam);evtTip.init();eventTipsCollection.push(evtTip);}}}}catch(e){yahooError(e);}};this.clear=function(){eventTipsCollection.splice(0,eventTipsCollection.length);};this.observe=function(aSubject,aTopic,aData){_dataObj.daysSinceLastTip=Math.round(((new Date())-(new Date(_dataObj.confMgr.getCharValue("etp.lasttiptimestamp"))))/daysToMilliSecFactor);if(aTopic==="yahoo-feed-updated"){for(var i=0;i<eventTipsCollection.length;i++){if(eventTipsCollection[i].do_triggerTip(eEventTypes.ET_LAYOUT,aData)){_notifyShowTip(eventTipsCollection[i]);break;}}
if(_trigTimerEval){_trigTimerEval=false;_self.observe(_timer,"timer-callback",null);}}else if(aTopic==="yahoo-probe-url"){for(var i=0;i<eventTipsCollection.length;i++){if(eventTipsCollection[i].do_triggerTip(eEventTypes.ET_URL_NAV,aData)){_notifyShowTip(eventTipsCollection[i]);break;}}}else if(aTopic==="yahoo-probe-click"){for(var i=0;i<eventTipsCollection.length;i++){if(eventTipsCollection[i].do_triggerTip(eEventTypes.ET_BTN_CLICK,aData)){_notifyShowTip(eventTipsCollection[i]);break;}}}else if(aTopic==="timer-callback"){for(var i=0;i<eventTipsCollection.length;i++){if(eventTipsCollection[i].do_triggerTip(eEventTypes.ET_TIMEOUT,aData)){_notifyShowTip(eventTipsCollection[i]);break;}}}else if(aTopic==="yahoo-metro-sync"){for(var i=0;i<eventTipsCollection.length;i++){if(eventTipsCollection[i].do_triggerTip(eEventTypes.ET_METRO_SYNC,aData)){_notifyShowTip(eventTipsCollection[i]);break;}}}else if(aTopic==="nsPref:changed"){_dataObj.tipsEnabled=_dataObj.confMgr.getBoolValue("general.eventtips");}};this.init=function(tb_manager){observerService.addObserver(_self,"yahoo-feed-updated",false);observerService.addObserver(_self,"yahoo-probe-url",false);observerService.addObserver(_self,"yahoo-probe-click",false);observerService.addObserver(_self,"yahoo-metro-sync",false);_dataObj.confMgr.addOnChangeListener("general.eventtips",_self);_timer.init(_self,computeTimeInterval,CI.nsITimer.TYPE_REPEATING_SLACK);_dataObj.toolbarManager=tb_manager;_dataObj.daysSinceInstall=Math.round(((new Date())-new Date(_dataObj.confMgr.getCharValue("installer.installdate")))/daysToMilliSecFactor);_dataObj.daysSinceLastTip=Math.round(((new Date())-new Date(_dataObj.confMgr.getCharValue("etp.lasttiptimestamp")))/daysToMilliSecFactor);_dataObj.daysTBIsInactive=Math.round(((new Date())-new Date(_dataObj.confMgr.getCharValue("toolbar.lastuse")))/daysToMilliSecFactor);_dataObj.daysSinceLastTip=isNaN(_dataObj.daysSinceLastTip)?__INFINITE__:_dataObj.daysSinceLastTip;_dataObj.daysTBIsInactive=isNaN(_dataObj.daysTBIsInactive)?_dataObj.daysSinceInstall:_dataObj.daysTBIsInactive;_dataObj.tbUpgraded=_dataObj.confMgr.getBoolValue("toolbar.upgraded")?eAcceptTypes.AT_TRUE:eAcceptTypes.AT_FALSE;_dataObj.tipsEnabled=_dataObj.confMgr.getBoolValue("general.eventtips");};};yEventTipManager.prototype={classID:Components.ID("{F753E8BB-EB63-4487-BA4D-1DB514C7C1E3}"),contractID:"@yahoo.com/eventtipmanager;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIObserver,Components.interfaces.nsIYahooEventTipManager])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([yEventTipManager]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([yEventTipManager]);