
var CI=Components.interfaces;var CC=Components.classes;var yahooPrefService=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefBranch);var loader=CC["@mozilla.org/moz/jssubscript-loader;1"].getService(CI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");var eLoadType={NOT_LOADED:0x01,CACHE_LOADED:0x02,LIVE_LOADED:0x03};function YahooFeedFetcher(){var _self=this;var mFileIO=CC["@yahoo.com/fileio;1"].getService(CI.nsIYahooFileIO2);var localstorage=CC["@yahoo.com/localstorage;1"].getService(CI.nsIYahooLocalStorage);var mConfigMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var FEED_URL="http:\/\/us.update2.toolbar.yahoo.com/slv/v4/2.html?&.pc=&t=1123627243899&.ta=cgnone,cc,cius,cv1_5_4,cp,cbm,cjs";var loading=false;var loadedType=eLoadType.NOT_LOADED;var serverRaw="";var raw="";var callBackFunc=null;var secureKey="AvadaKedavra";var alertManager=CC["@yahoo.com/alertmanager;1"].getService(CI.nsIYahooAlertManager);var notifier=CC["@mozilla.org/observer-service;1"].getService(CI.nsIObserverService);var stream=CC["@mozilla.org/intl/converter-input-stream;1"].createInstance(CI.nsIConverterInputStream);buildFeedUrl=function(isGuestMode){var url="";try{var param;var prefs=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefBranch);var time=new Date().getTime();var cc=mConfigMgr.getCharValue("installer.country")||"us";var pc=mConfigMgr.getCharValue("toolbar.pc")||"";var tid=mConfigMgr.getCharValue("installer.toolbarID")||"";var cid=mConfigMgr.getCharValue("installer.corpID")||"";var lang=mConfigMgr.getCharValue("installer.language")||cc.substr(0,2);var cver=mConfigMgr.getCharValue("installer.version")||"2.0.0";var d_url="";var protocol="https:\/\/";var ep=alertManager.getExtraParams();if(mConfigMgr.isKeyPresent("dataserver.url")){d_url=mConfigMgr.getCharValue("dataserver.url");d_url=d_url.replace("$CONFIG_INTL$",cc);}else{d_url=cc+".data.toolbar.yahoo.com";}
var layout="def";if(mConfigMgr.isKeyPresent("disablehttps")&&mConfigMgr.getBoolValue("disablehttps")){protocol="http:\/\/";}
if(prefs.prefHasUserValue("yahoo.ytff.toolbar.layout")&&prefs.getCharPref("yahoo.ytff.toolbar.layout")){layout=mConfigMgr.getCharValue("toolbar.layout");}
if(!isGuestMode&&(param=localstorage.getString("lang"))){lang=param;}
if(tid===""){tid="none";}
if(cver!==""){cver=cver.split(".");if(cver.length>3){cver.length=3;}
cver=cver.join("_");}
url=protocol+d_url+"/bh/v8/1.html"+"?&.pc="+pc+"&.a=0"+"&.ta=cg"+tid+",cc"+cid+",ci"+lang+",cv"+cver+",cp"+pc+",cbm,cjs"+"&.lo="+layout+"&t="+time;if(!isGuestMode){url+="&.crumb="+feedCrumb();}
if(isGuestMode){var lu=elapsedDays(mConfigMgr.getCharValue('toolbar.lastuse'));var lc=elapsedDays(mConfigMgr.getCharValue('toolbar.lastcust'));var nf=mConfigMgr.getIntValue('toolbar.numfeed');url+="&.lu="+lu+"&.lc="+lc+"&.nf="+nf;}
var sig=calculateCacheSig();if(sig!=null){url+="&.cv=000.000&.cs=p,"+sig;var ybSig=calculateYBCacheSig();if(ybSig!=null){url+=",yb,"+ybSig;}}
if(ep!==null){url+="&ep="+ep;}
yahooDebug("Feed URL "+url);}catch(e){yahooError("Error in buildFeedUrl : "+e);}
return url;};elapsedDays=function(date){if(date){return Math.round((new Date().getTime()-new Date(date).getTime())/86400000);}else{return 999999;}};feedCrumb=function(){var crumb='';var found=false;var cookies=CC["@mozilla.org/cookiemanager;1"].getService(CI.nsICookieManager2);cookies=cookies.enumerator;while(cookies.hasMoreElements()&&!found){var cookie=cookies.getNext().QueryInterface(CI.nsICookie);if(cookie.host==".yahoo.com"&&cookie.name=="T"){found=true;var value=cookie.value;var hash=yahooUtils.MD5Hash(value);crumb=hash.substring(0,32);}}
return crumb;};stripKey=function(){var strip={begin:',{"e":["Y!","sck"," ","0","',end:"}",sKeyEnd:"\""};var ret=["",secureKey];var praw=serverRaw.split(strip.begin);var kraw=praw[1];if(praw[0]&&praw[1]){yahooDebug("Stripping sck");var index=praw[1].indexOf(strip.end);praw[1]=praw[1].substr(index+1);ret[0]=praw[0]+praw[1];}else{ret[0]=serverRaw;}
if(kraw){var key=kraw.split(strip.sKeyEnd)[0];ret[1]=key;yahooDebug("Secure Key found");}
return ret;};calculateYBCacheSig=function(){try{var cacheblobfile=mFileIO.getUserCacheDir();cacheblobfile.appendRelativePath("ybcache");if(cacheblobfile.exists()){var fileContent=mFileIO.readFile(cacheblobfile);var sig=yahooUtils.MD5Hash(fileContent);return sig;}
return null;}catch(e){yahooError("Error in calculateYBCacheSig"+e);}},calculateCacheSig=function(){try{var cacheblobfile=mFileIO.getUserCacheDir();cacheblobfile.appendRelativePath("cachesection");if(cacheblobfile.exists()){var fileContent=mFileIO.readFile(cacheblobfile);var sig=yahooUtils.MD5Hash(fileContent);return sig;}else{}
return null;}catch(e){yahooError("Error in calculateCacheSig"+e);}},toolbarLoadRestart=function(seconds){yahooUtils.setTimeout(function(){_self.loadServerFeed();},1000*seconds);};this.setSecureKey=function(key){secureKey=key;}
this.loadServerFeed=function(isGuestMode){if(loading){return"";}
try{var retVal="";if(isGuestMode===undefined||isGuestMode===null)
throw"Invalid parameters";loading=true;FEED_URL=buildFeedUrl(isGuestMode);var request=CC["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance(CI.nsIXMLHttpRequest);request.open("GET",FEED_URL,false);request.send(null);if(request.status!==200){throw"Error in Fetching Feed from server";}
serverRaw=request.responseText;var stripped=stripKey();var strippedServerRaw=stripped[0];secureKey=stripped[1];if(raw!=strippedServerRaw){yahooDebug("Cached Feed and Server Feed are not equal");raw=serverRaw;loadedType=eLoadType.LIVE_LOADED;retVal=raw;raw=strippedServerRaw;}else{retVal=raw;yahooDebug("Cached Feed == Server Feed");}
var val=mConfigMgr.getIntValue('toolbar.numfeed');val++;mConfigMgr.setIntValue('toolbar.numfeed',val,true);}catch(e){raw="";loadedType=eLoadType.NOT_LOADED;yahooError(e);notifier.notifyObservers(null,"yahoo-feed-error","405: "+e);}finally{loading=false;return retVal;}};this.asyncLoadServerFeed=function(isGuestMode,cbFunc){if(loading){return"";}
if(isGuestMode===undefined||isGuestMode===null)
throw"Invalid parameters";callBackFunc=cbFunc.wrappedJSObject.object;loading=true;FEED_URL=buildFeedUrl(isGuestMode);var iosvc=CC["@mozilla.org/network/io-service;1"].getService(CI.nsIIOService);var channel=iosvc.newChannel(FEED_URL,0,null);yahooDebug("Getting feed from URL :"+FEED_URL);channel.asyncOpen(this,null);};this.onStartRequest=function(request,context){serverRaw="";};this.onDataAvailable=function(request,context,inputStream,offset,count){stream.init(inputStream,"UTF-8",1024,CI.nsIConverterInputStream.DEFAULT_REPLACEMENT_CHARACTER);var str={};if(stream.readString(count,str)!==0)
serverRaw+=str.value;};this.onStopRequest=function(request,context,statusCode){try{if(stream){try{stream.close();}catch(e){}}
var http=request.QueryInterface(CI.nsIHttpChannel);if(serverRaw===""){throw"Error in Fetching Feed from server";}
var stripped=stripKey();var strippedServerRaw=stripped[0];secureKey=stripped[1];if(raw!=strippedServerRaw){yahooDebug("Cached Feed and Server Feed are not equal");raw=serverRaw;loadedType=eLoadType.LIVE_LOADED;var retVal=raw;raw=strippedServerRaw;}else{var retVal=raw;yahooDebug("Cached Feed == Server Feed");}
var val=mConfigMgr.getIntValue('toolbar.numfeed');val++;mConfigMgr.setIntValue('toolbar.numfeed',val,true);}catch(e){raw="";loadedType=eLoadType.NOT_LOADED;yahooError(e);notifier.notifyObservers(null,"yahoo-feed-error","405: "+e);}finally{loading=false;if(callBackFunc)
callBackFunc(retVal);}}
this.loadCachedFeed=function(localCacheFile){if(loading){return;}
yahooDebug("Entering loadCachedFeed");var inStream,handle;var success=false;loading=true;try{if(localCacheFile!=null){loadedType=eLoadType.CACHE_LOADED;var fileRaw=mFileIO.readFile(localCacheFile);if(!fileRaw||fileRaw===""){throw"Empty Cache File";}
raw=fileRaw;success=true;}}catch(e){raw="";loadedType=eLoadType.NOT_LOADED;yahooError(e);notifier.notifyObservers(null,"yahoo-feed-error","403: "+e);}finally{loading=false;if(!success)raw="";return raw;}};this.QueryInterface=function(iid){if(!iid.equals(CI.nsIYahooFeedFetcher)&&!iid.equals(CI.nsISupports)&&!iid.equals(CI.nsIStreamListener))
throw Components.results.NS_ERROR_NO_INTERFACE;return this;};this.pushLayoutToServer=function(userSave,layout,isGuestMode)
{try{if(isGuestMode){return 0;}
var intl=mConfigMgr.getCharValue("installer.country")+""||"us";var pc=mConfigMgr.getCharValue("toolbar.pc")||"";var port=mConfigMgr.getCharValue("layout.portable");var metroExp=localstorage.getString("metroexp");var cver=mConfigMgr.getCharValue("installer.version")||"2.0.0";if(cver!==""){cver=cver.split(".");if(cver.length>3)cver.length=3;cver=cver.join("_");}
var lo=layout;var crumb=localstorage.getString("crumb");var yob=CC['@yahoo.com/feed/localbutton;1'].getService(CI.nsIYahooLocalButtonProcessor).getLocalButtonsJSON(layout);var syob="";var toolbarConfigServer=localstorage.getString("yahoo.ytff.configserver.url");var pslayURL="http:\/\/"+toolbarConfigServer
+"/config/pslay/?"
+"&.pc="+pc
+"&.intl="+intl
+"&.cver="+"8_0_0"
+"&.lo="+lo
+"&.crumb="+crumb
+"&usave="+userSave
+"&.port="+port
+"&.metroexp="+metroExp
+"&.merge=1";var postData="";if(yob!=null&&yob.length>0)postData=".yob="+encodeURIComponent(yob);if(syob!=null&&syob.length>0)postData+="&.syob="+syob;yahooDebug("pslay URL is "+pslayURL);var request=CC["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance(CI.nsIXMLHttpRequest);request.open("POST",pslayURL,false);request.setRequestHeader("Content-Type","application/x-www-form-urlencoded");request.send(postData);return request.status;}catch(e){yahooError("Exception in pushLayoutToServer "+e)}};}
function NSGetModule(compMgr,fileSpec){return{myCID:Components.ID("{4138788A-68DF-4cb5-B6F9-E50DE9C70708}"),myProgID:"@yahoo.com/feed/fetcher;1",firstTime:true,registerSelf:function(compMgr,fileSpec,location,type){if(this.firstTime){this.firstTime=false;throw Components.results.NS_ERROR_FACTORY_REGISTER_AGAIN;}
compMgr=compMgr.QueryInterface(CI.nsIComponentRegistrar);compMgr.registerFactoryLocation(this.myCID,"Yahoo! Feed Processor",this.myProgID,fileSpec,location,type);},getClassObject:function(compMgr,cid,iid){if(!cid.equals(this.myCID))throw Components.results.NS_ERROR_NO_INTERFACE;if(!iid.equals(CI.nsIFactory))throw Components.results.NS_ERROR_NOT_IMPLEMENTED;return this.myFactory;},myFactory:{createInstance:function(outer,iid){if(outer!=null)throw Components.results.NS_ERROR_NO_AGGREGATION;return(new YahooFeedFetcher()).QueryInterface(iid);}},canUnload:function(compMgr){return true;}};}