/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */const EXPORTED_SYMBOLS=["ObjectsStorage"];const Cc=Components.classes;const Ci=Components.interfaces;const Ce=Components.Exception;const Cr=Components.results;const Cu=Components.utils;Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/helpers/storageHelper.js");Cu.import("resource://ebaycompanion/objects/account.js");Cu.import("resource://ebaycompanion/objects/item.js");Cu.import("resource://ebaycompanion/objects/transaction.js");Cu.import("resource://ebaycompanion/objects/favoriteSeller.js");Cu.import("resource://ebaycompanion/objects/favoriteSearch.js");Cu.import("resource://ebaycompanion/objects/trackingCode.js");Cu.import("resource://ebaycompanion/objects/systemMessage.js");var ObjectsStorage={_tables:[{objectType:Account,tableName:"accounts",primaryKeys:["userId","isSandboxAccount"]},{objectType:Item,tableName:"items",primaryKeys:["itemId"]},{objectType:Transaction,tableName:"transactions",primaryKeys:["itemId","transactionId"]},{objectType:FavoriteSeller,tableName:"favoriteSellers",primaryKeys:["userId","isSandboxAccount","sellerId"]},{objectType:FavoriteSearch,tableName:"favoriteSearches",primaryKeys:["userId","isSandboxAccount","searchName"]},{tableName:"account_items",columns:["userId","isSandboxAccount","itemId"],primaryKeys:["userId","isSandboxAccount","itemId"]},{objectType:TrackingCode,tableName:"trackingCodes",primaryKeys:["country","isRover"]},{objectType:SystemMessage,tableName:"systemMessages",primaryKeys:["messageId","userId"]}],_init:function(){try{for(let i=0;i<this._tables.length;i++){let table=this._tables[i];if(!StorageHelper.connection.tableExists(table.tableName)){let schema;if(table.objectType){schema=this._buildSchemaForObject(table.objectType,table.primaryKeys);}else{schema=table.columns.join(",")+","+
"PRIMARY KEY("+table.primaryKeys.join(",")+")";}
StorageHelper.connection.createTable(table.tableName,schema);}}}
catch(e){Logger.exception(e);}},removeTables:function(){for(let i=0;i<this._tables.length;i++){let statement="DROP TABLE IF EXISTS #{table}; ";statement=statement.replace(/#{table}/g,this._tables[i].tableName);StorageHelper.doStatement(statement);}},store:function(object){let className=object.constructor.name.toLowerCase();let tableName=className+"s";if(className.indexOf("search")!=-1){tableName=className+"es";}
let objectProperties=object.constructor.prototype.propertyTypes;let columnNames="";let numValues=0;let placeholders="";let values=[];for each(let[property,]in Iterator(objectProperties)){columnNames+=property+",";placeholders+="?"+ ++numValues+",";values.push(object.get(property));}
columnNames=columnNames.slice(0,-1);placeholders=placeholders.slice(0,-1);let statement="INSERT OR REPLACE INTO #{table} (#{columns}) VALUES (#{placeholders})";statement=statement.replace(/#{table}/g,tableName).replace(/#{columns}/g,columnNames).replace(/#{placeholders}/g,placeholders);let params=values;StorageHelper.doStatement(statement,params,true);},activeAccount:function(){if(typeof(PropertiesStorage)=="undefined"){Cu.import("resource://ebaycompanion/storage/propertiesStorage.js");}
let accountProperty=PropertiesStorage.get("activeAccount");let account;if(accountProperty){let statement="SELECT * FROM accounts WHERE userId == ?1 AND isSandboxAccount == ?2";let params=accountProperty.split(",");let rows=StorageHelper.doStatement(statement,params);account=this._accountFromRow(rows[0]);}
return account;},getAccount:function(username,isSandboxAccount){let statement="SELECT * FROM accounts WHERE userId == ?1 AND isSandboxAccount == ?2";let rows=StorageHelper.doStatement(statement,[username,isSandboxAccount]);let account;if(rows.length>0){account=this._accountFromRow(rows[0]);}
return account;},setActiveAccount:function(account){if(account){let userId=account.get("userId");let isSandboxAccount=account.get("isSandboxAccount");let accountProperty=[userId,isSandboxAccount].join(",");PropertiesStorage.set("activeAccount",accountProperty);}else{PropertiesStorage.remove("activeAccount");}},getAllAccounts:function(){let statement="SELECT accounts.* FROM accounts";let rows=StorageHelper.doStatement(statement);let accounts=[];for(let i=0;i<rows.length;i++){accounts.push(this._accountFromRow(rows[i]));}
return accounts;},addItemToAccount:function(item,account){this.store(item);let statement="INSERT OR REPLACE INTO account_items "+
"(userId, isSandboxAccount, itemId) "+
"VALUES (?1, ?2, ?3)";let params=[account.get("userId"),account.get("isSandboxAccount"),item.get("itemId")];StorageHelper.doStatement(statement,params,true);},removeItemFromAccount:function(item,account){let statement="DELETE FROM account_items WHERE "+
"userId == ?1 AND isSandboxAccount == ?2 AND itemId == ?3";let params=[account.get("userId"),account.get("isSandboxAccount"),item.get("itemId")];StorageHelper.doStatement(statement,params,true);statement="DELETE FROM items WHERE itemId NOT IN "+
"(SELECT itemId FROM account_items)";StorageHelper.doStatement(statement,null,true);statement="DELETE FROM transactions WHERE itemId NOT IN "+
"(SELECT itemId FROM account_items)";StorageHelper.doStatement(statement,null,true);},itemsForAccount:function(account){let statement="SELECT items.* FROM account_items,items "+
"WHERE account_items.itemId == items.itemId AND "+
"userId == ?1 AND isSandboxAccount == ?2";let params=[account.get("userId"),account.get("isSandboxAccount")];let rows=StorageHelper.doStatement(statement,params);let items=[];for(let i=0;i<rows.length;i++){items.push(this._itemFromRow(rows[i]));}
return items;},transactionsForAccount:function(account){let statement="SELECT transactions.* FROM account_items,transactions "+
"WHERE account_items.itemId == transactions.itemId AND "+
"userId == ?1 AND isSandboxAccount == ?2";let params=[account.get("userId"),account.get("isSandboxAccount")];let rows=StorageHelper.doStatement(statement,params);let transactions=[];for(let i=0;i<rows.length;i++){transactions.push(this._transactionFromRow(rows[i]));}
return transactions;},removeTransaction:function(aTransaction){let statement="DELETE FROM transactions WHERE "+
"itemId == ?1 AND transactionId == ?2";let params=[aTransaction.get("itemId"),aTransaction.get("transactionId")];StorageHelper.doStatement(statement,params,true);},favoriteSellersForAccount:function(account){let statement="SELECT favoriteSellers.* FROM favoriteSellers "+
"WHERE userId == ?1 AND isSandboxAccount == ?2";let params=[account.get("userId"),account.get("isSandboxAccount")];let rows=StorageHelper.doStatement(statement,params);let favoriteSellers=[];for(let i=0;i<rows.length;i++){favoriteSellers.push(this._favoriteSellerFromRow(rows[i]));}
return favoriteSellers;},removeFavoriteSellersFromAccount:function(aAccount){let statement="DELETE FROM favoriteSellers WHERE "+
"userId == ?1 AND isSandboxAccount == ?2";let params=[aAccount.get("userId"),aAccount.get("isSandboxAccount")];StorageHelper.doStatement(statement,params,true);},favoriteSearchesForAccount:function(account){let statement="SELECT favoriteSearches.* FROM favoriteSearches "+
"WHERE userId == ?1 AND isSandboxAccount == ?2";let params=[account.get("userId"),account.get("isSandboxAccount")];let rows=StorageHelper.doStatement(statement,params);let favoriteSearches=[];for(let i=0;i<rows.length;i++){favoriteSearches.push(this._favoriteSearchFromRow(rows[i]));}
return favoriteSearches;},removeFavoriteSearchesFromAccount:function(aAccount){let statement="DELETE FROM favoriteSearches WHERE "+
"userId == ?1 AND isSandboxAccount == ?2";let params=[aAccount.get("userId"),aAccount.get("isSandboxAccount")];StorageHelper.doStatement(statement,params,true);},getRoverIds:function(){let statement="SELECT trackingCodes.* FROM trackingCodes WHERE isRover == ?1";let params=["true"];let rows=StorageHelper.doStatement(statement,params);let roverIds=new Array();let trackingCode;for(let i=0;i<rows.length;i++){trackingCode=this._trackingCodeFromRow(rows[i]);roverIds[i]=trackingCode;}
return roverIds;},getInstallTrackingCodes:function(){let statement="SELECT trackingCodes.* FROM trackingCodes WHERE isRover == ?1";let params=["false"];let rows=StorageHelper.doStatement(statement,params);let trackingCodes=new Array();let trackingCode;for(let i=0;i<rows.length;i++){trackingCode=this._trackingCodeFromRow(rows[i]);trackingCodes[i]=trackingCode;}
return trackingCodes;},getSystemMessage:function(aMessageId,aUserId){let statement="SELECT systemMessages.* FROM systemMessages WHERE "+
"messageId = ?1 AND userId = ?2";let rows=StorageHelper.doStatement(statement,[aMessageId,aUserId]);let systemMessage;if(rows.length>0){systemMessage=this._systemMessageFromRow(rows[0]);}
return systemMessage;},removeSystemMessages:function(aTime){let statement="DELETE FROM systemMessages WHERE validToTime < ?1";StorageHelper.doStatement(statement,[aTime],true);},_accountFromRow:function(row){let account;try{account=new Account(row.userId,row.isSandboxAccount);let propertyTypes=Account.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){account.set(property,row[property]);}}
catch(e){Logger.error("Unable to create Account object from database row.",Logger.DUMP_STACK);}
return account;},_itemFromRow:function(row){let item;try{item=new Item(row.itemId);let propertyTypes=Item.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){item.set(property,row[property]);}}
catch(e){Logger.error("Unable to create Item object from database row.",Logger.DUMP_STACK);}
return item;},_transactionFromRow:function(row){let transaction;try{transaction=new Transaction(row.itemId,row.transactionId);let propertyTypes=Transaction.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){transaction.set(property,row[property]);}}
catch(e){Logger.error("Unable to create Transaction object from database row.",Logger.DUMP_STACK);}
return transaction;},_favoriteSellerFromRow:function(row){let favoriteSeller;try{favoriteSeller=new FavoriteSeller(row.userId,row.isSandboxAccount,row.sellerId);let propertyTypes=FavoriteSeller.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){favoriteSeller.set(property,row[property]);}}
catch(e){Logger.error("Unable to create FavoriteSeller object from database row.",Logger.DUMP_STACK);}
return favoriteSeller;},_favoriteSearchFromRow:function(row){let favoriteSearch;try{favoriteSearch=new FavoriteSearch(row.userId,row.isSandboxAccount,row.searchName);let propertyTypes=FavoriteSearch.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){favoriteSearch.set(property,row[property]);}}
catch(e){Logger.error("Unable to create FavoriteSearch object from database row.",Logger.DUMP_STACK);}
return favoriteSearch;},_trackingCodeFromRow:function(row){let trackingCode;try{trackingCode=new TrackingCode(row.country,row.isRover,row.value);let propertyTypes=TrackingCode.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){trackingCode.set(property,row[property]);}}
catch(e){Logger.error("Unable to create TrackingCode object from database row.",Logger.DUMP_STACK);}
return trackingCode;},_systemMessageFromRow:function(row){let systemMessage;try{systemMessage=new SystemMessage(row.messageId,row.userId);let propertyTypes=SystemMessage.prototype.propertyTypes;for(let[property,]in Iterator(propertyTypes)){systemMessage.set(property,row[property]);}}
catch(e){Logger.error("Unable to create SystemMessage object from database row.",Logger.DUMP_STACK);}
return systemMessage;},_buildSchemaForObject:function(object,primaryKeys){let schema="";for(let[property,type]in Iterator(object.prototype.propertyTypes)){schema+=property+",";}
schema+="PRIMARY KEY("+primaryKeys.join(",")+")";return schema;}};ObjectsStorage._init();