
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var CI=Components.interfaces;var CC=Components.classes;var observerService=CC['@mozilla.org/observer-service;1'].getService(CI.nsIObserverService);var loader=CC["@mozilla.org/moz/jssubscript-loader;1"].getService(CI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(Components.interfaces.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};var eInjectoTriggerTypes={Injecto_Error:-2,Injecto_Unset:-1,Injecto_PageLoad:0,Injecto_PageClick:1,Injecto_PageSelectText:2,Injecto_MaxTriggerType:2};function InjectoCommonObjects(){this.urlProbe=CC["@yahoo.com/urlprobe;1"].getService(CI.nsIYahooUrlProbe);this.localstorage=CC["@yahoo.com/localstorage;1"].getService(CI.nsIYahooLocalStorage);this.confMgr=CC["@yahoo.com/configmanager;1"].getService(CI.nsIYahooConfigManager);this.toolbarManager=null;this.injectoEnabled=false;this.getDocument=function(){var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);var _Win=wm.getMostRecentWindow("navigator:browser");var _gBrowser=_Win.getBrowser();return _gBrowser.contentDocument;}};function InjectoItem(dataObj)
{var _dataObj=dataObj;var _self=this;_self.triggerType=eInjectoTriggerTypes.Injecto_Unset;_self.btnId="";_self.regex=null;_self.hash=null;_self.init=function(){};this.do_triggerInjecto=function(occurredTriggerType,pageUrl,_dataObj){var bRetVal=false;if(occurredTriggerType==_self.triggerType){if(pageUrl.indexOf("http")!=0){return false;}
var optId="button."+_self.btnId;var bEnabled=false;if(_dataObj.confMgr.isKeyPresent(optId)){bEnabled=_dataObj.confMgr.getBoolValue(optId);}
else if(_self.hash.dv&&(_self.hash.dv!="0")){bEnabled=true;}
if(!bEnabled){return false;}
if(_self.regex!=null)
{if(!pageUrl.match(_self.regex)){return false;}}}
return true;};this.buildUrl=function(_dataObj){if(_self.hash.jsinjpath==null){return null;}
var injHost="l.yimg.com",injDir="\/nt\/lib\/tb\/inj\/";if(_dataObj.localstorage.getString("j")!=null){injHost=_dataObj.localstorage.getString("j");}
if(_dataObj.localstorage.getString("ju")!=null){injDir=_dataObj.localstorage.getString("ju");}
return"http://"+injHost+injDir+_self.hash.jsinjpath;};this.injectJS=function(_dataObj,doc){var url=_self.buildUrl(_dataObj);if(url==null){return;}
var id="ytb_inject_"+_self.btnId;var scripto=doc.getElementById(id);if(scripto!=null){return;}
var request=CC["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance(CI.nsIXMLHttpRequest);request.open("GET",url,true);request.onreadystatechange=function(aEvt){if(request.readyState==4){if(request.status==200){var scriptTxt=request.responseText;var jcrumb=_dataObj.localstorage.getString("injcrumb");scriptTxt+="\n setTimeout(\"YTBInjecto."+_self.btnId+".triggered('"+jcrumb+"')\", 3000);";_self.injectJSRaw(_dataObj,scriptTxt);}
else{yahooError("Error loading JS");}}}
request.send(null);};this.injectJSRaw=function(_dataObj,code){try{var doc=_dataObj.getDocument();var id="ytb_inject_"+_self.btnId;var head=doc.getElementsByTagName('head')[0];var script=doc.createElement('script');script.id=id;script.type='text/javascript';var trigger=doc.createTextNode(code);script.appendChild(trigger);var el=head.appendChild(script);}
catch(e){yahooError(e);}};};function yInjectoManager(){var _self=this;var _dataObj=new InjectoCommonObjects();var _currentUrl;var injectoCollection=[];this.addInjecto=function(injectoNode){try{var injectoItem=new InjectoItem(_dataObj);injectoItem.hash=yahooUtils.JSON.parse(injectoNode.hash);injectoItem.btnId=injectoItem.hash.id;injectoItem.triggerType=injectoItem.hash.injtrigger;if(injectoItem.hash.injregex){injectoItem.regex=injectoItem.hash.injregex;}
injectoItem.init();injectoCollection.push(injectoItem);}catch(e){yahooError(e);}};this.clear=function(){injectoCollection.splice(0,injectoCollection.length);};this.pageLoaded=function(){if(!_dataObj.injectoEnabled){return;}
var doc=_dataObj.getDocument();_currentUrl=doc.documentURI;for(var i=0;i<injectoCollection.length;i++){if(injectoCollection[i].do_triggerInjecto(eInjectoTriggerTypes.Injecto_PageLoad,_currentUrl,_dataObj)){injectoCollection[i].injectJS(_dataObj,doc);break;}}};this.init=function(tb_manager){_dataObj.injectoEnabled=_dataObj.confMgr.getBoolValue("general.injecto.debug");_dataObj.toolbarManager=tb_manager;};};yInjectoManager.prototype={classID:Components.ID("{86944522-4715-49d7-8666-6C2818B14114}"),contractID:"@yahoo.com/injectomanager;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIObserver,Components.interfaces.nsIYahooInjectoManager])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([yInjectoManager]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([yInjectoManager]);