
var CI=Components.interfaces;var CC=Components.classes;var yahooCC=CC;var yahooCI=CI;var yahooPrefService=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefBranch);var loader=CC["@mozilla.org/moz/jssubscript-loader;1"].getService(CI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");loader.loadSubScript("chrome://ytoolbar/content/utils.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(Components.interfaces.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooAlertManager(){try{this.localstorage=Components.classes["@yahoo.com/localstorage;1"].getService(Components.interfaces.nsIYahooLocalStorage);this.notifier=CC["@mozilla.org/observer-service;1"].getService(CI.nsIObserverService);this.pollinterval=7*60*1000;this.ep={};}catch(e){yahooError(e);}}
YahooAlertManager.prototype={timer:null,notifier:null,currentpollids:null,pollinterval:null,ep:null,toolbarmanager:null,initAlerts:function(toolbarManager){try{yahooDebug("Initializing alerts .. ");this.toolbarmanager=toolbarManager;if(this.timer!==null&&this.timer.delay!=this.pollinterval){this.stopAlertTimer(this);}
var alertmgr=this;var callback={notify:function(timer){try{alertmgr.retrieveAlerts();}catch(e){yahooError(e);}}};this.timer=CC["@mozilla.org/timer;1"].createInstance(CI.nsITimer);this.timer.initWithCallback(callback,this.pollinterval,this.timer.TYPE_REPEATING_PRECISE);}catch(e){yahooError(e);}},clearSignedinData:function(){try{yahooDebug("AlertManager ClearSignedindata :");var alertD=this.localstorage.getObject("alert");if(alertD!=null){alertD=alertD.wrappedJSObject.object;if(alertD!==undefined){for(x in alertD){if(alertD[x].algst===undefined||alertD[x].algst==0){var alertObj=this.localstorage.getObject(alertD[x].alrt);if(alertObj!==null){alertObj=alertObj.wrappedJSObject.object;if(alertObj!==null){alertObj=undefined;this.localstorage.putObject(alertD[x].alrt,new WrapperClass(alertObj));}}}}}}}catch(e){yahooError("Exception in AlertManager:refreshOnCookieChange"+e);}},refreshAlert:function(alertids,refresh)
{yahooDebug("Refresh Alert"+alertids.toString());if(!refresh){var alertids=alertids.wrappedJSObject.object;for(x in alertids){alertObj=this.localstorage.getObject(alertids[x]);if(alertObj!==null){alertObj=undefined;this.localstorage.putObject(alertids[x],new WrapperClass(alertObj));}}
this.notifier.notifyObservers(null,"yahoo-feed-alerts-updated","");}else{this.retrieveAlerts(alertids.wrappedJSObject.object);}},broadcastAlert:function(ids){this.notifier.notifyObservers(null,"yahoo-feed-alerts-updated",ids);},setExtraParam:function(key,value,persist){if(persist){var configManager=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);if(configManager){var eps=configManager.getCharValue("alertmanager.ep");var ep={};if(eps!==null&&eps!=""){ep=yahooUtils.JSON.parse(eps);}
ep[key]=value;var epstring=yahooUtils.JSON.stringify(ep);configManager.setCharValue("alertmanager.ep",epstring,true);}}else{if(this.ep===null){this.ep={};}
this.ep[key]=value;}},getExtraParams:function(){var ep={};if(this.ep!=null){ep=this.ep;}
var configManager=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var persistant_ep_string=configManager.getCharValue("alertmanager.ep");var persistant_ep={};if(persistant_ep_string!==null&&persistant_ep_string!=""){persistant_ep=yahooUtils.JSON.parse(persistant_ep_string);}
for(var e in ep){persistant_ep[e]=ep[e];}
var eps='';for(var i in persistant_ep){eps+="ep["+i+"]=";eps+=persistant_ep[i];eps+="&";}
this._resetExtraParams();return eps;},_resetExtraParams:function(){if(this.ep!=null){this.ep=null;}},retrieveAlerts:function(ids){try{yahooDebug("Retriving Alerts..");var alertIds=[];if(ids){alertIds=ids;}else{var alertD=this.localstorage.getObject("alert");if(alertD===null){return;}
alertD=alertD.wrappedJSObject.object;var alertids;var isGuestAlert;var alertints;if(alertD!==undefined){for(x in alertD){if((this.toolbarmanager.isGuestMode()!==true)||(this.toolbarmanager.isGuestMode()&&alertD[x].algst)){var pollthistime=false;if(alertD[x].slot===undefined||alertD[x].slot===0){if(alertD[x].alint!==undefined){alertD[x].slot=alertD[x].alint/this.pollinterval;}else{alertD[x].slot=0;}
pollthistime=true;}else{alertD[x].slot=alertD[x].slot-1;if(alertD[x].slot===0){pollthistime=true;}}
if(pollthistime===true){var aids=alertD[x].alrt;aids=aids.split(",");for(y in aids){alertIds.push(aids[y]);}}}}}else{yahooDebug("No Alert data");}}
if(alertIds===""){yahooDebug("No alert to fetch,");return;}
this.currentpollids=alertIds.toString();var url=this.buildAlertUrl(alertIds);yahooDebug("Alert URL :"+url);var alertmgr=this;var iosvc=CC["@mozilla.org/network/io-service;1"].getService(CI.nsIIOService);var channel=iosvc.newChannel(url,0,null);var channelListener={stream:null,alertFeed:"",onStartRequest:function(request,context){this.alertFeed="";},onDataAvailable:function(request,context,inputStream,offset,count){if(!this.stream){this.stream=CC["@mozilla.org/scriptableinputstream;1"].createInstance(CI.nsIScriptableInputStream);}
this.stream.init(inputStream);this.alertFeed+=this.stream.read(count);},onStopRequest:function(request,context,statusCode){try{if(this.stream){this.stream.close();}
request.QueryInterface(CI.nsIHttpChannel);if(this.alertFeed===""||request.status!==0){return;}
var haveAlerts=alertmgr.processJSONAlerts(this.alertFeed);if(haveAlerts){alertmgr.notifier.notifyObservers(null,"yahoo-feed-alerts-updated",alertmgr.currentpollids);}}catch(e){yahooError(e);}
this.stream=null;}};channel.asyncOpen(channelListener,null);}catch(e){yahooError(e);}},stopAlertTimer:function(mgr){mgr=mgr||this;if(mgr.timer!==null){mgr.timer.cancel();mgr.timer=null;}},addAlertData:function(alertid,index,value){var alertData=this.localstorage.getObject(alertid);if(alertData!=null){if(alertData.wrappedJSObject.object!=undefined){alertData=alertData.wrappedJSObject.object;}else{alertData=null;}}
if(alertData===null){alertData=[];}
alertData[index]=value;this.localstorage.putObject(alertid,new WrapperClass(alertData));},addAlertObject:function(alertid,index,value){var alertData=this.localstorage.getObject(alertid);if(alertData!=null){if(alertData.wrappedJSObject.object!=undefined){alertData=alertData.wrappedJSObject.object;}else{alertData=null;}}
if(alertData===null){alertData=[];}
alertData[index]=value.wrappedJSObject.object;this.localstorage.putObject(alertid,new WrapperClass(alertData));},processJSONAlerts:function(alertFeed){try{var alertJSON=yahooUtils.JSON.parse(alertFeed);for(fullalertid in alertJSON){var alertv=alertJSON[fullalertid];var keysplit=fullalertid.split('_');var alertid=parseInt(keysplit[1]);var index=parseInt(keysplit[2]);this.addAlertData(alertid,index,alertv);}
return true;}catch(e){yahooError("Error in processJSONAlerts"+e);}},processAlerts:function(alertFeed,processor){alertFeed=alertFeed.substr(alertFeed.indexOf(">")+2);alertFeed=alertFeed.slice(0,alertFeed.indexOf("<"));var keyValueList=alertFeed.split(' ');for(idx in keyValueList){var keyValue=keyValueList[idx];var keyValueArray=keyValue.split(' ');var alertid=null;var alert_data=[];for(x in keyValueArray){if(alertid===null){alertid=keyValueArray[x];}else{this.addAlertData(alertid,x,keyValueArray[x]);}}}
return true;},buildAlertUrl:function(alertids){var param;var url="";var _mConfigManager=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var fnum=2;var fver=8;var time=new Date().getTime();var cc=(_mConfigManager.getCharValue("installer.country")+".")||"us.";var pc=_mConfigManager.getCharValue("toolbar.pc")||"";var tid=_mConfigManager.getCharValue("installer.toolbarID")||"";var cid=_mConfigManager.getCharValue("installer.corpID")||"";var lang=_mConfigManager.getCharValue("installer.language")||cc.substr(0,2);var cver=_mConfigManager.getCharValue("installer.version")||"1.1.0";var crumb=this.localstorage.getString("crumb");var ep=this.getExtraParams();var protocol="https:\/\/";if(_mConfigManager.isKeyPresent("disablehttps")&&_mConfigManager.getBoolValue("disablehttps")){protocol="http:\/\/";}
if(!this.toolbarmanager.isGuestMode()&&(param=this.localstorage.getString("lang"))){lang=param;}
if(tid===""){tid="none";}
if(cver!==""){cver=cver.split(".");if(cver.length>3){cver.length=3;}
cver=cver.join("_");}
alertids=this.removedup(alertids);url=protocol+this.localstorage.getString("yahoo.ytff.dataserver.url")+"/slv/v"+fver+"/not?v="+cver+"&t="+time+"&.ta=cg"+tid+",cc"+cid+",ci"+lang+",cv"+cver+",cjs"+"&_ids=200,204"+alertids.toString()+",";if(crumb!==null){url+="&.crumb="+crumb;}
if(ep!==null){url+="&ep="+ep;}
return url;},removedup:function(alertids){alertids=alertids.sort();var uniqArr=[];var prev;for(x in alertids){if(prev!=alertids[x]&&alertids[x]!="200"&&alertids[x]!="204"){uniqArr.push(prev);prev=alertids[x];}}
return uniqArr;},QueryInterface:function(iid){if(!iid.equals(CI.nsIYahooAlertManager)&&!iid.equals(CI.nsISupports)&&!iid.equals(CI.nsIRunnable)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function NSGetModule(compMgr,fileSpec){return{myCID:Components.ID("{48dc5d59-2592-4bdb-8ed4-680c8ffc9f10}"),myProgID:"@yahoo.com/alertmanager;1",firstTime:true,registerSelf:function(compMgr,fileSpec,location,type){if(this.firstTime){this.firstTime=false;throw Components.results.NS_ERROR_FACTORY_REGISTER_AGAIN;}
compMgr=compMgr.QueryInterface(CI.nsIComponentRegistrar);compMgr.registerFactoryLocation(this.myCID,"Yahoo! Alert Manager",this.myProgID,fileSpec,location,type);},getClassObject:function(compMgr,cid,iid){if(!cid.equals(this.myCID)){throw Components.results.NS_ERROR_NO_INTERFACE;}
if(!iid.equals(CI.nsIFactory)){throw Components.results.NS_ERROR_NOT_IMPLEMENTED;}
return this.myFactory;},myFactory:{createInstance:function(outer,iid){if(outer!==null){throw Components.results.NS_ERROR_NO_AGGREGATION;}
return new YahooAlertManager().QueryInterface(iid);}},canUnload:function(compMgr){return true;}};}