/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */const EXPORTED_SYMBOLS=["InformationNotificationHelper"];const Cc=Components.classes;const Ci=Components.interfaces;const Ce=Components.Exception;const Cr=Components.results;const Cu=Components.utils;var InformationNotificationHelper={TERMS_CONDITIONS_CHANGED_NOTIFICATION:1,LOGIN_EXPLAIN_NOTIFICATION:2,FEEDBACK_NOTIFICATION:3,NEW_MESSAGES_NOTIFICATION:4,MARKETING_NOTIFICATION:5,BEST_OFFER_NOT_SUPPORTED_NOTIFICATION:6,TERMS_CONDITIONS_NOTIFICATION:7,INFO_NOTIFICATION_TOPIC:"ebay-information-notification",CLEAR_NOTIFICATION_BOX_TOPIC:"ebay-clear-information-notificationbox",INFO_NOTIFICATION_IMAGE:"chrome://ebaycompanion/skin/images/infoNotification.png",_infoNotifications:null,_currentInfoNotification:null,_observers:null,_init:function(){try{Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/helpers/observers.js");this._observers=new Observers;let(that=this){this._observers.add(function(){that.clearQueue()},"ebay-account-logged-out");this._observers.add(function(){that._uninit()},"quit-application-granted");}
this._infoNotifications=new Array();}
catch(e){Logger.exception(e);}},_uninit:function(){try{this._clearQueue();this._observers.removeAll();}
catch(e){Logger.exception(e);}},get currentInfoNotification(){return this._currentInfoNotification;},sortNotifications:function(aNotification1,aNotification2){return aNotification1.get("priority")-aNotification2.get("priority");},showPendingNotifications:function(){try{let nextNotification=this.getNextNotification();if(null!=nextNotification){Observers.notify(nextNotification,this.INFO_NOTIFICATION_TOPIC,null);}else{Observers.notify(null,this.CLEAR_NOTIFICATION_BOX_TOPIC,null);}}catch(e){Logger.exception(e);}},getNextNotification:function(aLevel){let next=null;let tmp=null;try{if(this._infoNotifications.length>0){tmp=this._infoNotifications[0];if(null!=this._currentInfoNotification){if(this._currentInfoNotification.get("priority")>tmp.get("priority")){next=tmp;}else{next=this._currentInfoNotification;}}else{next=tmp;}
if(!next.get("isPersistent")){this._removeNotificationsByType(next.get("type"));}
this._currentInfoNotification=next;}}catch(e){Logger.exception(e);return null;}
return next;},queueNotification:function(aNotification,aPreventImageOverwrite){try{this._removeNotificationsByType(aNotification.get("type"));if(!aPreventImageOverwrite){aNotification.set("imageURL",this.INFO_NOTIFICATION_IMAGE);}
this._infoNotifications.push(aNotification);this._infoNotifications.sort(this.sortNotifications);if(this._infoNotifications.length==1){this._currentInfoNotification=aNotification;}
this.showPendingNotifications();}catch(e){Logger.exception(e);}},dismissNotification:function(aNotificationType){this._removeNotificationsByType(aNotificationType);this.showPendingNotifications();},_removeNotificationsByType:function(aType){try{for(var i=0;i<this._infoNotifications.length;i++){if(aType==this._infoNotifications[i].get("type")){this._infoNotifications.splice(i,1);break;}}
this._currentInfoNotification=null;}catch(e){Logger.exception(e);}},removeCurrentNotification:function(aIsPersistent){try{if(null!=this._currentInfoNotification&&aIsPersistent){this._removeNotificationsByType(this._currentInfoNotification.get("type"));}
this.showPendingNotifications();}catch(e){Logger.exception(e);}},clearQueue:function(){this._clearQueue();this.showPendingNotifications();},_clearQueue:function(){try{this._infoNotifications.splice(0,this._infoNotifications.length);}catch(e){Logger.exception(e);}},clearCurrentNotification:function(){try{this._currentInfoNotification=null;}catch(e){Logger.exception(e);}}};InformationNotificationHelper._init();