/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */const EXPORTED_SYMBOLS=["ObjectHelper"];const Cc=Components.classes;const Ci=Components.interfaces;const Ce=Components.Exception;const Cr=Components.results;const Cu=Components.utils;Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/helpers/observers.js");var ObjectHelper={flags:{NO_NOTIFICATIONS:1},filterValue:function(property,type,value){const TYPE_MISMATCH="Type Mismatch: %1 (\"%2\") given for %3, which is of type %4";let reportError=function(){let str=TYPE_MISMATCH.replace(/%1/,typeof(value)).replace(/%2/,value).replace(/%3/,property).replace(/%4/,type);Logger.error(str,Logger.DUMP_STACK,Components.stack.caller.caller.caller);}
let newValue=value;switch(type){case"number":newValue=Number(value);if(isNaN(newValue)){reportError();}
break;case"listingFormat":switch(value){case"Chinese":case"Dutch":case"FixedPriceItem":case"StoresFixedPrice":case"LeadGeneration":case"AdType":case"Live":newValue=value;break;default:newValue="FixedPriceItem";reportError();}
break;case"boolean":switch(typeof(value)){case"boolean":newValue=value;break;case"string":if(value=="true"){newValue=true;}else if(value=="false"){newValue=false;}else{newValue=false;reportError();}
break;default:newValue=false;reportError();}
break;default:if(typeof(value)!=type){newValue=undefined;reportError();}}
return newValue;},updateObject:function(curObject,newObject,notificationName,flags,ignorePropertiesArray){let objectModified=false;for(let[property,value]in Iterator(newObject)){if(property.charAt(0)=="_"){let ignoreProperty=false;if(ignorePropertiesArray){for(let i=0;i<ignorePropertiesArray.length;i++){let tempProperty="_"+ignorePropertiesArray[i];if(property==tempProperty){ignoreProperty=true;break;}}}
if(!ignoreProperty){let curValue=curObject[property];curObject[property]=value;if(curValue!=value){objectModified=true;if(flags!=this.flags.NO_NOTIFICATIONS){let member=property.slice(1);let info={};info.object=curObject;info.oldValue=curValue;info.newValue=value;Observers.notify(info,notificationName,member);}}}}}
return objectModified;},updateProperty:function(curObject,property,value,notificationName){let curValue=curObject["_"+property];curObject.set(property,value);if(curValue!=value){let info={};info.object=curObject;info.oldValue=curValue;info.newValue=value;Observers.notify(info,notificationName,property);}},getProperty:function(object,property){let value=object["_"+property];if(value==undefined){Logger.warning("Attempt to get property \""+property+"\" of "+
object.constructor.name+" object, which is undefined.",Logger.DUMP_STACK);}
return value;},fromXML:function(aXMLNode,aObject){var object=this._getObjectFromName(aObject.constructor.name);var xmlName=null;var xmlValue=null;var that=this;let objectPropertyTypes=aObject.constructor.prototype.propertyTypes;let objectPropertyXML=aObject.constructor.prototype.propertyXML;for each(let[property,type]in Iterator(objectPropertyTypes)){xmlValue=that._getXMLValue(aXMLNode,type,objectPropertyXML[property]);if(xmlValue!=null){object.set(property,xmlValue);}}
return object;},_getXMLValue:function(aXMLNode,aType,aXMLName){let xmlNames=aXMLName.split("|");let xmlValue=null;for each(let[aIndex,aName]in Iterator(xmlNames)){let xmlFields=aName.split(".");let xmlNode=aXMLNode;for each(let[aFieldIndex,aField]in Iterator(xmlFields)){if(aField[0]!="@"){let arrayStart=aField.indexOf('[');if(arrayStart!=-1){let arrayIndex=aField.substring(arrayStart+1,aField.indexOf(']'));aField=aField.substring(0,arrayStart);xmlNode=xmlNode.children(aField)[arrayIndex];}else{xmlNode=xmlNode.descendants(aField);}}}
if(xmlNode.length()>0){if(xmlFields[(xmlFields.length-1)][0]=="@"){let xmlAttr=xmlFields[(xmlFields.length-1)].substring(1);if(aType=="number"){xmlValue=Number(xmlNode.attribute(xmlAttr));}else{xmlValue=String(xmlNode.attribute(xmlAttr));}}else{if(aType=="number"){xmlValue=Number(xmlNode.text());}else{xmlValue=String(xmlNode.text());}}
break;}};return xmlValue;},_getObjectFromName:function(aName){Cu.import("resource://ebaycompanion/objects/item.js");Cu.import("resource://ebaycompanion/objects/account.js");Cu.import("resource://ebaycompanion/objects/transaction.js");Cu.import("resource://ebaycompanion/objects/favoriteSearch.js");Cu.import("resource://ebaycompanion/objects/favoriteSeller.js");Cu.import("resource://ebaycompanion/objects/systemMessage.js");Cu.import("resource://ebaycompanion/objects/deal.js");var object;switch(aName.toLowerCase()){case"account":object=new Account();break;case"item":object=new Item();break;case"transaction":object=new Transaction();break;case"favoriteseller":object=new FavoriteSeller();break;case"favoritesearch":object=new FavoriteSearch();break;case"systemmessage":object=new SystemMessage();break;case"deal":object=new Deal();break;default:break;}
return object;}}