/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */const EXPORTED_SYMBOLS=["ApiAccessService"];const Cc=Components.classes;const Ci=Components.interfaces;const Ce=Components.Exception;const Cr=Components.results;const Cu=Components.utils;var ApiAccessService={_apiVersion:null,_siteId:null,_init:function(){try{Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/constants.js");Cu.import("resource://ebaycompanion/helpers/httpRequestHeaderVisitor.js");Cu.import("resource://ebaycompanion/helpers/accessKeysHelper.js");this._apiVersion=627;this._siteId=0;}
catch(e){Logger.exception(e);}},_uninit:function(){try{}catch(e){Logger.exception(e);}},get siteId(){return this._siteId;},set siteId(aValue){this._siteId=aValue;},get apiVersion(){return this._apiVersion;},set apiVersion(aValue){this._apiVersion=aValue;},visitRequestHeaders:function(aHttpChannel){let visitor=new HttpRequestHeaderVisitor(aHttpChannel);let requestHeaders=visitor.inspectRequest();let message="REQUEST HEADERS\n";for each(let[name,value]in Iterator(requestHeaders)){message+=name+": "+value+"\n";}
let postData=visitor.getPostData();if(postData){message+="POST DATA:\n";message+=postData+"\n";}
Logger.error(message);},doTradingAPICall:function(callName,body,useSandbox,callback){let url;if(!useSandbox){url="https://api.ebay.com/ws/api.dll";}else{url="https://api.sandbox.ebay.com/ws/api.dll";}
let keyset=AccessKeysHelper.getKeySet(useSandbox,this._siteId);let httpChannel=this.makeChannelForUrl(url);httpChannel.setRequestHeader("X-EBAY-API-COMPATIBILITY-LEVEL",this._apiVersion,false);httpChannel.setRequestHeader("X-EBAY-API-DEV-NAME",keyset.devName,false);httpChannel.setRequestHeader("X-EBAY-API-APP-NAME",keyset.appName,false);httpChannel.setRequestHeader("X-EBAY-API-CERT-NAME",keyset.certName,false);httpChannel.setRequestHeader("X-EBAY-API-CALL-NAME",callName,false);httpChannel.setRequestHeader("X-EBAY-API-SITEID",this._siteId,false);httpChannel.setRequestHeader("X-EBAY-SIDEBAR-VERSION",Constants.prefBranch.get("version"),false);this.setChannelPostData(httpChannel,body);let request=this.sendRequest(httpChannel,callback);return request;},doShoppingAPICall:function(callName,body,useSandbox,callback){let url;if(!useSandbox){url="http://open.api.ebay.com/shopping?";}else{url="http://open.api.sandbox.ebay.com/shopping?";}
let keyset=AccessKeysHelper.getKeySet(useSandbox,this._siteId);let httpChannel=this.makeChannelForUrl(url);httpChannel.setRequestHeader("X-EBAY-API-VERSION",this._apiVersion,false);httpChannel.setRequestHeader("X-EBAY-API-APP-ID",keyset.appName,false);httpChannel.setRequestHeader("X-EBAY-API-CALL-NAME",callName,false);httpChannel.setRequestHeader("X-EBAY-API-SITE-ID",this._siteId,false);httpChannel.setRequestHeader("X-EBAY-API-REQUEST-ENCODING","XML",false);httpChannel.setRequestHeader("X-EBAY-SIDEBAR-VERSION",Constants.prefBranch.get("version"),false);this.setChannelPostData(httpChannel,body);let request=this.sendRequest(httpChannel,callback);return request;},doClientAlertsAPICall:function(callName,parameterString,useSandbox,callback){let url;if(!useSandbox){url="http://clientalerts.ebay.com/ws/ecasvc/ClientAlerts?";}else{url="http://clientalerts.sandbox.ebay.com/ws/ecasvc/ClientAlerts?";}
let keyset=AccessKeysHelper.getKeySet(useSandbox,this._siteId);url+="callname="+callName;url+=parameterString;url+="&ApplicationID="+keyset.appName;url+="&siteid="+this._siteId;url+="&version="+this._apiVersion;let httpChannel=this.makeChannelForUrl(url);let request=this.sendRequest(httpChannel,callback);return request;},doMyEbayApplicationAPICall:function(callName,token,body,useSandbox,callback){let url;if(!useSandbox){url="https://svcs.ebay.com/ws/spf";}else{url="https://svcs.ebay.com/ws/spf";}
let keyset=AccessKeysHelper.getKeySet(useSandbox,this._siteId);let httpChannel=this.makeChannelForUrl(url);httpChannel.setRequestHeader("X-EBAY-SOA-SERVICE-NAME","MyEbayApplicationService",false);httpChannel.setRequestHeader("X-EBAY-SOA-OPERATION-NAME",callName,false);httpChannel.setRequestHeader("X-EBAY-SOA-SECURITY-TOKEN",token,false);httpChannel.setRequestHeader("X-EBAY-SOA-SECURITY-APPNAME",keyset.appName,false);httpChannel.setRequestHeader("X-EBAY-SIDEBAR-VERSION",Constants.prefBranch.get("version"),false);this.setChannelPostData(httpChannel,body);this.visitRequestHeaders(httpChannel);let request=this.sendRequest(httpChannel,callback);return request;},makeChannelForUrl:function(urlSpec){let ioService=Cc["@mozilla.org/network/io-service;1"]
.getService(Ci.nsIIOService);let uri=ioService.newURI(urlSpec,null,null);let channel=ioService.newChannelFromURI(uri);channel.QueryInterface(Ci.nsIHttpChannel);return channel;},setChannelPostData:function(channel,postData){let inputStream=Cc["@mozilla.org/io/string-input-stream;1"]
.createInstance(Ci.nsIStringInputStream);inputStream.setData(postData,postData.length);let uploadChannel=channel.QueryInterface(Ci.nsIUploadChannel);uploadChannel.setUploadStream(inputStream,"text/xml",-1);channel.requestMethod="POST";},sendRequest:function(channel,callback){let requestListener=new RequestListener();requestListener.addCallback(callback);channel.asyncOpen(requestListener,null);return requestListener;}};function RequestListener(){this._callbacks=new Array();this._abortWhenReady=false;this._buffer="";}
RequestListener.prototype={addCallback:function(callback){this._callbacks.push(callback);},onStartRequest:function(aRequest,aContext){this._buffer="";this._request=aRequest;if(this._abortWhenReady){this._request.cancel(Cr.NS_BINDING_ABORTED);}},onStopRequest:function(aRequest,aContext,aStatus){let err=0;let response;switch(aStatus){case Cr.NS_OK:err=0;response=this._buffer;break;default:err=aStatus;response="";break;}
this.callCallbacks(err,response);},onDataAvailable:function(aRequest,aContext,aStream,aSourceOffset,aLength){var scriptableInputStream=Components.classes["@mozilla.org/scriptableinputstream;1"]
.createInstance(Components.interfaces.nsIScriptableInputStream);scriptableInputStream.init(aStream);this._buffer+=scriptableInputStream.read(aLength);},cancel:function(){if(this._request){this._request.cancel(Cr.NS_BINDING_ABORTED);}else{this._abortWhenReady=true;}
return Cr.NS_OK;},callCallbacks:function(err,response){for(let[index,callback]in Iterator(this._callbacks)){callback.trigger(err,response);}
this._callbacks.splice(0,this._callbacks.length);},getInterface:function(aIID){try{return this.QueryInterface(aIID);}catch(e){throw Components.results.NS_NOINTERFACE;}},onProgress:function(aRequest,aContext,aProgress,aProgressMax){},onStatus:function(aRequest,aContext,aStatus,aStatusArg){},onRedirect:function(aOldChannel,aNewChannel){},QueryInterface:function(aIID){if(aIID.equals(Components.interfaces.nsISupports)||aIID.equals(Components.interfaces.nsIInterfaceRequestor)||aIID.equals(Components.interfaces.nsIChannelEventSink)||aIID.equals(Components.interfaces.nsIProgressEventSink)||aIID.equals(Components.interfaces.nsIHttpEventSink)||aIID.equals(Components.interfaces.nsIStreamListener)||aIID.equals(Components.interfaces.ecIEbayApiRequest))
return this;throw Components.results.NS_NOINTERFACE;}};ApiAccessService._init();