/* Copyright (C) 2007-2011 eBay Inc. All Rights Reserved. */const EXPORTED_SYMBOLS=["AutocompleteService"];const Cc=Components.classes;const Ci=Components.interfaces;const Cu=Components.utils;Cu.import("resource://glaxebay/gsCommon.js");Cu.import("resource://ebaycompanion/helpers/logger.js");Cu.import("resource://ebaycompanion/helpers/observers.js");Cu.import("resource://ebaycompanion/constants.js");Cu.import("resource://ebaycompanion/datasource.js");var AutocompleteService={_SEARCH_PARAM:"ebay-searchbox-history",ID_HISTORY_SEARCH:"0",ID_EBAY_SEARCH:"1",_autoCompleteSearch:null,_formHistoryService:null,_historyResults:null,_suggestionResults:null,_currentQuery:null,_request:null,get ID_SEARCH_HISTORY(){return"0";},get ID_BOOKMARKS(){return"1";},get TOPIC_RESULTS_RETURNED(){return"gs-ebay-search-results-returned";},_init:function(){this._autoCompleteSearch=Cc["@mozilla.org/autocomplete/search;1?name=form-history"].createInstance(Ci.nsIAutoCompleteSearch);this._formHistoryService=Cc["@mozilla.org/satchel/form-history;1"].getService(Ci.nsIFormHistory2);},storeSearch:function(aValue){this._formHistoryService.addEntry(this._SEARCH_PARAM,aValue);},clearSearchHistory:function(){this._formHistoryService.removeEntriesForName(this._SEARCH_PARAM);},search:function(aQuery){this._currentQuery=aQuery;this._historyResults=null;this._suggestionResults=null;this._getSearchHistory(aQuery);this._getSearchSuggestions(aQuery);},_getSearchHistory:function(aQuery){this._autoCompleteSearch.startSearch(aQuery,this._SEARCH_PARAM,null,this);},onSearchResult:function(aSearch,aResult){let historyResult=aResult;if(historyResult){let query=historyResult.searchString;let results=new Array();if(historyResult.searchResult==Ci.nsIAutoCompleteResult.RESULT_SUCCESS){let count=historyResult.matchCount;let result=null;for(let i=0;i<count;i++){result={};result.title=historyResult.getValueAt(i);result.type="History";results.push(result);}}
this._historyResults=results;this._resultsReturned();}else{this._historyResults=new Array();this._resultsReturned();}},_getSearchSuggestions:function(aQuery){let suggestionsEnabled=Constants.prefBranch.get("searchbox.showSuggestions");if(suggestionsEnabled){let that=this;let siteId=Constants.siteIdForSite(Datasource.homeSite());let queryParam={query:aQuery,site:siteId};let url=Constants.getUrl("autosuggest","autosuggest",queryParam);let callback=function(aRequest){if(aRequest.status==200){that._handleQueryResponse(aRequest.responseText);that._request=null;}else{that._suggestionResults=new Array();that._resultsReturned();}}
this._sendRequest(url,callback);}else{this._suggestionResults=new Array();this._resultsReturned();}},_handleQueryResponse:function(aResponse){let responseText=aResponse.replace(/<\?xml .*?>/,"").replace(/ xmlns=["'].*?["']/,"");let xmlTree=XML(responseText);this._suggestionResults=this._parseXMLResponse(xmlTree);this._resultsReturned();},_parseXMLResponse:function(aXMLTree){const ID_DELIMITER="_pid%3D";let results=new Array();let currentMatch=aXMLTree..Query.text();let trimmedSearchString=/^(.*?)\s*$/.exec(this._currentQuery)[1];if(currentMatch&&currentMatch==trimmedSearchString){let xmlSections=aXMLTree..Section;let result=null;for each(let xmlSection in xmlSections){if(""==xmlSection.@title){let xmlChildWalker=function(aXML){var i=0;var child=aXML.*[0];while(child!=undefined){yield child;child=aXML.*[++i];}
yield false;}
var xcw=xmlChildWalker(xmlSection);let child=null;let processingProducts=false;let nodeStyle=null;let itemId=null;while((child=xcw.next())!==false){if("Separator"==child.name()&&"Popular Products"==child.@title){processingProducts=true;}
if("Item"==child.name()){let itemURL=String(child.Url.text());result={};result.title=String(child.Text.text());result.url=itemURL;result.id=itemURL.substring(itemURL.indexOf(ID_DELIMITER)+ID_DELIMITER.length);result.type="Suggestion";if(processingProducts){result.style="popular-product";if(child.Image){result.image=String(child.Image.@source);}}
if(""!=result.title){results.push(result);}}}}}}
return results;},_resultsReturned:function(){if(this._historyResults&&this._suggestionResults){let obj=new Object();this._removeDuplicates();obj.wrappedJSObject=this._buildResultArray();GlaxEbay.ObserverService.notifyObservers(obj,this.TOPIC_RESULTS_RETURNED,this._currentQuery);}},_removeDuplicates:function(){let historyCount=this._historyResults.length;let suggestionCount=this._suggestionResults.length;let historyItem=null;let suggestionItem=null;for(let i=0;i<historyCount;i++){historyItem=this._historyResults[i];suggestionCount=this._suggestionResults.length;for(let j=suggestionCount-1;j>=0;j--){suggestionItem=this._suggestionResults[j];if(historyItem.title==suggestionItem.title){this._suggestionResults.splice(j,1);}}}},_buildResultArray:function(){const HISTORY_MAX=3;const SUGGESTION_MAX=7;let results=new Array();let historyCount=this._historyResults.length;let suggestionCount=this._suggestionResults.length;let historyDelta=historyCount-HISTORY_MAX;let suggestionDelta=suggestionCount-SUGGESTION_MAX;let historyTop=(historyCount<HISTORY_MAX?historyCount:HISTORY_MAX);let suggestionTop=(suggestionCount<SUGGESTION_MAX?suggestionCount:SUGGESTION_MAX);if(0>historyDelta&&0<suggestionDelta){let posHistoryDelta=Math.abs(historyDelta);suggestionTop+=(suggestionDelta>posHistoryDelta?posHistoryDelta:suggestionDelta);}
if(0>suggestionDelta&&0<historyDelta){let posSuggestionDelta=Math.abs(suggestionDelta);historyTop+=(historyDelta>posSuggestionDelta?posSuggestionDelta:historyDelta);}
for(let i=0;i<historyTop;i++){results.push(this._historyResults[i]);}
for(let i=0;i<suggestionTop;i++){results.push(this._suggestionResults[i]);}
return results;},_sendRequest:function(aURL,aCallback){let request=Cc["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance(Ci.nsIXMLHttpRequest);if(this._request){this._request.abort();}
this._request=request;request.open('GET',aURL,true);request.onreadystatechange=function(){if(request.readyState==4&&aCallback){aCallback(request);}};request.send(null);}};(function(){this._init();}).apply(AutocompleteService);