
Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");var CI=Components.interfaces;var CC=Components.classes;var yahooPrefService=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefBranch);var loader=CC["@mozilla.org/moz/jssubscript-loader;1"].getService(CI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/utils.js");loader.loadSubScript("chrome://ytoolbar/content/logger.js");var eLoadType={NOT_LOADED:0x01,CACHE_LOADED:0x02,LIVE_LOADED:0x03};function YahooFeedFetcher(){var _self=this;var mFileIO=CC["@yahoo.com/fileio;1"].getService(CI.nsIYahooFileIO2);var localstorage=CC["@yahoo.com/localstorage;1"].getService(CI.nsIYahooLocalStorage);var mConfigMgr=Components.classes["@yahoo.com/configmanager;1"].getService(Components.interfaces.nsIYahooConfigManager);var FEED_URL="http:\/\/us.update2.toolbar.yahoo.com/slv/v4/2.html?&.pc=&t=1123627243899&.ta=cgnone,cc,cius,cv1_5_4,cp,cbm,cjs";var loading=false;var loadedType=eLoadType.NOT_LOADED;var serverRaw="";var raw="";var callBackFunc=null;var secureKey="AvadaKedavra";var alertManager=CC["@yahoo.com/alertmanager;1"].getService(CI.nsIYahooAlertManager);var notifier=CC["@mozilla.org/observer-service;1"].getService(CI.nsIObserverService);var stream=CC["@mozilla.org/intl/converter-input-stream;1"].createInstance(CI.nsIConverterInputStream);buildFeedUrl=function(isGuestMode){var url="";try{var param;var prefs=CC["@mozilla.org/preferences-service;1"].getService(CI.nsIPrefBranch);var time=new Date().getTime();var cc=mConfigMgr.getCharValue("installer.country")||"us";var pc=mConfigMgr.getCharValue("toolbar.pc")||"";var dc=mConfigMgr.getCharValue("toolbar.dc")||"";var tid=mConfigMgr.getCharValue("installer.toolbarID")||"";var cid=mConfigMgr.getCharValue("installer.corpID")||"";var lang=mConfigMgr.getCharValue("installer.language")||cc.substr(0,2);var cver=mConfigMgr.getCharValue("installer.version")||"2.0.0";var d_url="";var protocol="https:\/\/";var ep=alertManager.getExtraParams();if(mConfigMgr.isKeyPresent("dataserver.url")){d_url=mConfigMgr.getCharValue("dataserver.url");d_url=d_url.replace("$CONFIG_INTL$",cc);}else{d_url=cc+".data.toolbar.yahoo.com";}
var layout="def";if(mConfigMgr.isKeyPresent("disablehttps")&&mConfigMgr.getBoolValue("disablehttps")){protocol="http:\/\/";}
if(prefs.prefHasUserValue("yahoo.ytff.toolbar.layout")&&prefs.getCharPref("yahoo.ytff.toolbar.layout")&&prefs.prefHasUserValue("yahoo.ytff.toolbar.lastcust")){layout=mConfigMgr.getCharValue("toolbar.layout");}
if(!isGuestMode&&(param=localstorage.getString("lang"))){lang=param;}
if(tid===""){tid="none";}
if(cver!==""){cver=cver.split(".");if(cver.length>3){cver.length=3;}
cver=cver.join("_");}
var vert=mConfigMgr.getCharValue('installer.activeVertical');var skinEnabled=mConfigMgr.getIntValue('general.enableskins');var skinrequest=mConfigMgr.getBoolValue('skin.request')||false;var showvert=mConfigMgr.getBoolValue('general.enableverticals');var userskininfo=mConfigMgr.getCharValue("toolbar.userskininfo");var jsonObj=null;if(userskininfo!=""){jsonObj=yahooUtils.JSON.parse(userskininfo);}
var skin="";if(skinEnabled==1){skin=mConfigMgr.getCharValue('general.selectedskincode');}else if(skinEnabled==2&&jsonObj&&jsonObj[vert]){skin=jsonObj[vert];}
var toolbar_guid="";mConfigMgr.isYahooKey=false;if(mConfigMgr.isKeyPresent('yahoo.ytffp.installer._u')){mConfigMgr.isYahooKey=false;toolbar_guid=mConfigMgr.getCharValue('yahoo.ytffp.installer._u');}
url=protocol+d_url+"/bh/v8/1.html"+"?&.pc="+pc+"&.dc="+dc+"&.a=0"+"&.ta=cg"+tid+",cc"+cid+",ci"+lang+",cv"+cver+",cp"+pc+",cbm,cjs"+"&.skinm="+skinEnabled+"&.skin="+skin+"&.lo="+layout+"&t="+time+"&.tguid="+toolbar_guid;if(showvert)
url+="&.vert="+vert;if(!isGuestMode){url+="&.crumb="+feedCrumb();}
if(isGuestMode){var lu=elapsedDays(mConfigMgr.getCharValue('toolbar.lastuse'));var lc=elapsedDays(mConfigMgr.getCharValue('toolbar.lastcust'));var nf=mConfigMgr.getIntValue('toolbar.numfeed');url+="&.lu="+lu+"&.lc="+lc+"&.nf="+nf;}
url+="&.cspb=1";if(skinrequest){url+="&alrt=2";mConfigMgr.setBoolValue('skin.request',false,true);}
if(ep!==null){url+="&"+ep;}
yahooDebug("Feed URL "+url);}catch(e){yahooError("Error in buildFeedUrl : "+e);}
return url;};elapsedDays=function(date){if(date){return Math.round((new Date().getTime()-new Date(date).getTime())/86400000);}else{return 999999;}};feedCrumb=function(){var crumb='';var found=false;var cookies=CC["@mozilla.org/cookiemanager;1"].getService(CI.nsICookieManager2);cookies=cookies.enumerator;while(cookies.hasMoreElements()&&!found){var cookie=cookies.getNext().QueryInterface(CI.nsICookie);if(cookie.host==".yahoo.com"&&cookie.name=="T"){found=true;var value=cookie.value;var hash=yahooUtils.MD5Hash(value);crumb=hash.substring(0,32);}}
return crumb;};stripKey=function(){var strip={begin:',{"e":["Y!","sck"," ","0","',end:"}",sKeyEnd:"\""};var ret=["",secureKey];var praw=serverRaw.split(strip.begin);var kraw=praw[1];if(praw[0]&&praw[1]){yahooDebug("Stripping sck");var index=praw[1].indexOf(strip.end);praw[1]=praw[1].substr(index+1);ret[0]=praw[0]+praw[1];}else{ret[0]=serverRaw;}
if(kraw){var key=kraw.split(strip.sKeyEnd)[0];ret[1]=key;yahooDebug("Secure Key found");}
return ret;};calculateYBCacheSig=function(){try{var cacheblobfile=mFileIO.getUserCacheDir();cacheblobfile.appendRelativePath("ybcache");if(cacheblobfile.exists()){var fileContent=mFileIO.readFile(cacheblobfile);var sig=yahooUtils.MD5Hash(fileContent);return sig;}
return null;}catch(e){yahooError("Error in calculateYBCacheSig"+e);}},calculateperButtonYBCacheSig=function(bid){try{var cacheblobfile=mFileIO.getUserCacheDir();cacheblobfile.appendRelativePath(bid);if(cacheblobfile.exists()){var fileContent=mFileIO.readFile(cacheblobfile);fileContent=fileContent.replace(/\\\"/g,"\"");var sig=yahooUtils.MD5Hash(fileContent);yahooDebug("in ybcache sig calc"+bid+":"+sig);return sig;}
return null;}catch(e){yahooError("Error in calculateperButtonYBCacheSig"+e);}},calculateCacheSig=function(){try{var cacheblobfile=mFileIO.getUserCacheDir();cacheblobfile.appendRelativePath("cachesection");if(cacheblobfile.exists()){var fileContent=mFileIO.readFile(cacheblobfile);var sig=yahooUtils.MD5Hash(fileContent);return sig;}else{}
return null;}catch(e){yahooError("Error in calculateCacheSig"+e);}},toolbarLoadRestart=function(seconds){yahooUtils.setTimeout(function(){_self.asyncLoadServerFeed();},1000*seconds);};this.setSecureKey=function(key){secureKey=key;}
this.asyncLoadServerFeed=function(isGuestMode,cbFunc){if(loading){return"";}
callBackFunc=cbFunc.wrappedJSObject.object;loading=true;FEED_URL=buildFeedUrl(isGuestMode);var iosvc=CC["@mozilla.org/network/io-service;1"].getService(CI.nsIIOService);var channel=iosvc.newChannel(FEED_URL,0,null);yahooDebug("Getting feed from URL :"+FEED_URL);channel.asyncOpen(this,null);};this.onStartRequest=function(request,context){serverRaw="";};this.onDataAvailable=function(request,context,inputStream,offset,count){stream.init(inputStream,"UTF-8",1024,CI.nsIConverterInputStream.DEFAULT_REPLACEMENT_CHARACTER);var str={};if(stream.readString(count,str)!==0)
serverRaw+=str.value;};this.onStopRequest=function(request,context,statusCode){try{if(stream){try{stream.close();}catch(e){}}
var retVal="";var http=request.QueryInterface(CI.nsIHttpChannel);if(serverRaw===""){}
var stripped=stripKey();var strippedServerRaw=stripped[0];secureKey=stripped[1];if(raw!=strippedServerRaw){yahooDebug("Cached Feed and Server Feed are not equal");raw=serverRaw;loadedType=eLoadType.LIVE_LOADED;retVal=raw;raw=strippedServerRaw;if(mConfigMgr.getCharValue('installer.activeVertical')!=""){var file=mFileIO.getUserCacheDir();file.appendRelativePath("feed-"+mConfigMgr.getCharValue('installer.activeVertical'));var ding=yahooUtils.JSON.parse(raw);var feed={};feed.v=ding.v;feed.p=ding.p;feed.y=ding.y;feed.u=ding.u;feed=yahooUtils.JSON.stringify(feed);mFileIO.writeFile(file,feed);yahooDebug("cached vertical feed");}
if(mConfigMgr.getBoolValue("feedcaching")===true){var file=mFileIO.getUserCacheDir();file.appendRelativePath("feed");var ding=yahooUtils.JSON.parse(raw);var feed={};feed.v=ding.v;feed.p=ding.p;feed.y=ding.y;feed.u=ding.u;feed=yahooUtils.JSON.stringify(feed);mFileIO.writeFile(file,feed);yahooDebug("cached normal feed");}}
else{var retVal=raw;yahooDebug("Cached Feed == Server Feed");}
var val=mConfigMgr.getIntValue('toolbar.numfeed');val++;mConfigMgr.setIntValue('toolbar.numfeed',val,true);}catch(e){raw="";loadedType=eLoadType.NOT_LOADED;yahooError(e);_self.SendFeedFailureErrorReport("405: "+e);notifier.notifyObservers(null,"yahoo-feed-error","405: "+e);}finally{loading=false;if(callBackFunc)
callBackFunc(retVal);}}
this.loadCachedFeed=function(localCacheFile){if(loading){return;}
yahooStartTrace("LoadCachedFeed");var inStream,handle;var success=false;loading=true;try{if(localCacheFile!=null){loadedType=eLoadType.CACHE_LOADED;var file=mFileIO.getUserCacheDir();file.appendRelativePath(localCacheFile);var fileRaw=mFileIO.readFile(file);if(!fileRaw||fileRaw===""){}
raw=fileRaw;success=true;}}catch(e){raw="";loadedType=eLoadType.NOT_LOADED;yahooError(e);_self.SendFeedFailureErrorReport("403: "+e);notifier.notifyObservers(null,"yahoo-feed-error","403: "+e);}finally{loading=false;if(!success)raw="";yahooStopTrace("LoadCachedFeed");return raw;}};this.pushLayoutToServer=function(userSave,layout,isGuestMode)
{try{if(isGuestMode){return 0;}
var intl=mConfigMgr.getCharValue("installer.country")+""||"us";var pc=mConfigMgr.getCharValue("toolbar.pc")||"";var port=mConfigMgr.getCharValue("layout.portable");var metroExp=localstorage.getString("metroexp");var cver=mConfigMgr.getCharValue("installer.version")||"2.0.0";var tipShown=localstorage.getString("tipshown");if(cver!==""){cver=cver.split(".");if(cver.length>3)cver.length=3;cver=cver.join("_");}
var lo=layout;var crumb=localstorage.getString("crumb");var yob=CC['@yahoo.com/feed/localbutton;1'].getService(CI.nsIYahooLocalButtonProcessor).getLocalButtonsJSON(layout);var syob="";var toolbarConfigServer=localstorage.getString("yahoo.ytff.configserver.url");var pslayURL="http:\/\/"+toolbarConfigServer
+"/config/pslay/?"
+"&.pc="+pc
+"&.intl="+intl
+"&.cver="+"8_0_0"
+"&.lo="+lo
+"&.crumb="+crumb
+"&usave="+userSave
+"&.port="+port
+"&.metroexp="+metroExp
+"&.merge=1";if(tipShown=="1"){pslayURL+="&.yapbtnclear=1";localstorage.putString("tipshown","0");}
var postData="";if(yob!=null&&yob.length>0)postData=".yob="+encodeURIComponent(yob);if(syob!=null&&syob.length>0)postData+="&.syob="+syob;yahooDebug("pslay URL is "+pslayURL);var request=CC["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance(CI.nsIXMLHttpRequest);request.open("POST",pslayURL,true);request.setRequestHeader("Content-Type","application/x-www-form-urlencoded");request.onreadystatechange=function(aEvt){if(request.readyState==4){return request.status;}};request.send(postData);}catch(e){yahooError("Exception in pushLayoutToServer "+e)}};this.SendFeedFailureErrorReport=function(data)
{try{var cc=mConfigMgr.getCharValue("installer.country")||"us";var d_url="";var protocol="http:\/\/";if(mConfigMgr.isKeyPresent("dataserver.url")){d_url=mConfigMgr.getCharValue("dataserver.url");d_url=d_url.replace("$CONFIG_INTL$",cc);}else{d_url=cc+".data.toolbar.yahoo.com";}
var reportData=protocol+d_url+"/cltrpt.html";reportData+="?&.layout=";reportData+=mConfigMgr.getCharValue('toolbar.layout');reportData+="&.errorcode=";reportData+=encodeURIComponent(data);reportData+="&.isCachedFeed=";var cachedfile=mFileIO.getUserCacheDir();cachedfile.appendRelativePath("feed");if(cachedfile.exists())
reportData+="true";else
reportData+="false"
reportData+="&.intl=";reportData+=mConfigMgr.getCharValue('installer.language');reportData+="&.cv=";if(mConfigMgr.isKeyPresent("installer.version"))
{reportData+=mConfigMgr.getCharValue('installer.version').replace(/\./g,'_');}
reportData+="&.pc=";reportData+=mConfigMgr.getCharValue("toolbar.pc")||"";var request=Components.classes["@mozilla.org/xmlextras/xmlhttprequest;1"].createInstance(Components.interfaces.nsIXMLHttpRequest);request.open("GET",reportData,true);request.send(null);yahooDebug("SendFeedFailureErrorReport=============================="+reportData);}
catch(e){yahooDebug("error in SendFeedFailureErrorReport:"+e);}};};YahooFeedFetcher.prototype={classID:Components.ID("{4138788A-68DF-4cb5-B6F9-E50DE9C70708}"),contractID:"@yahoo.com/feed/fetcher;1",QueryInterface:XPCOMUtils.generateQI([Components.interfaces.nsIStreamListener,Components.interfaces.nsIYahooFeedFetcher])};if(XPCOMUtils.generateNSGetFactory)
var NSGetFactory=XPCOMUtils.generateNSGetFactory([YahooFeedFetcher]);else
var NSGetModule=XPCOMUtils.generateNSGetModule([YahooFeedFetcher]);