
var yahooCI=Components.interfaces;var yahooCC=Components.classes;var loader=yahooCC["@mozilla.org/moz/jssubscript-loader;1"].getService(yahooCI.mozIJSSubScriptLoader);loader.loadSubScript("chrome://ytoolbar/content/logger.js");loader.loadSubScript("chrome://ytoolbar/content/utils.js");function WrapperClass(object){this.wrappedJSObject=this;this.object=object;}
WrapperClass.prototype={QueryInterface:function(iid){if(!iid.equals(yahooCI.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function YahooPluginCallback(){try{this.ACTIONTYPE_NAVIGATE="NAVIGATE";this.ACTIONTYPE_SHOW_DROPDOWN="SHOW_DROPDOWN";this.EVENTTYPE_BROWSER="BROWSER";this.EVENTTYPE_UI="UI";this.yObsSvc=yahooCC["@mozilla.org/observer-service;1"].getService(yahooCI.nsIObserverService);this.yLocalStorage=yahooCC["@yahoo.com/localstorage;1"].getService(yahooCI.nsIYahooLocalStorage);yahooDebug("YahooPluginCallback::constructor....");}catch(e){yahooError(e);}}
YahooPluginCallback.prototype={test_xml:"",observe:function(aSubject,aTopic,aData){try{yahooDebug("YahooPluginCallback::observe()");}catch(e){yahooError("YahooPluginCallback::observe::"+e);}},getObject:function(InterfaceID){var XPCOMObject=null;try{if(!this.isInterfaceAccessible(InterfaceID,CLSID)){return null;}
yahooDebug("Interface requested by bridge:"+InterfaceID);var wm=Components.classes["@mozilla.org/appshell/window-mediator;1"].getService(Components.interfaces.nsIWindowMediator);yahooDebug("created a nsIWindowMediator");var navWin=null;var navNav=null;switch(InterfaceID)
{case"nsIDOMWindowInternal":navWin=wm.getMostRecentWindow("navigator:browser");XPCOMObject=navWin;break;case"nsIDOMWindow":navWin=wm.getMostRecentWindow("navigator:browser");if(navWin.top==null){yahooDebug("got a null nsIDOMWindow");}
XPCOMObject=navWin.top;break;case"nsIWebNavigation":navWin=wm.getMostRecentWindow("navigator:browser");navNav=navWin.QueryInterface(nsIInterfaceRequestor).getInterface(nsIWebNavigation);XPCOMObject=navNav;break;default:XPCOMObject=null;break;}}catch(e){yahooError(e);}
return XPCOMObject;},UpdateUI:function(CLSID){try{yahooDebug("YahooPluginCallback::UpdateUI()");this.yObsSvc.notifyObservers(null,"yahoo-partner-update-call",CLSID);}catch(e){yahooError("YahooPluginCallback.UpdateUI()::"+e);}},getValue:function(keyXML){try{yahooDebug("YahooPluginCallback::getValue()");}catch(e){yahooError("YahooPluginCallback.getValue()::"+e);}},setValue:function(keyXML){try{yahooDebug("YahooPluginCallback::setValue()");}catch(e){yahooError("YahooPluginCallback.setValue()::"+e);}},handleAction:function(eventArgXML){try{yahooDebug("YahooPluginCallback::handleAction()");}catch(e){yahooError("YahooPluginCallback.handleAction()::"+e);}
return true;},requentAction:function(actionType,eventArgXML){try{yahooDebug("YahooPluginCallback::requentAction()");var xmlParser=yahooCC["@mozilla.org/xmlextras/domparser;1"].createInstance(yahooCI.nsIDOMParser);var xmlArgs=xmlParser.parseFromString(eventArgXML,"text/xml");if(xmlArgs.tagName==="parserError"){yahooDebug("YahooPluginCallback.requentAction()::Error in parsing Argument XML");return;}
switch(actionType)
{case this.ACTIONTYPE_NAVIGATE:var navigationURL="";var navigationWin="";var Args=xmlArgs.getElementsByTagName("arg");for(var idx=0;idx<Args.length;idx++){var Arg=Args[idx];if(Arg.getAttribute("name")=="url"){navigationURL=Arg.getAttribute("value");}
if(Arg.getAttribute("name")=="flags"){navigationWin=Arg.getAttribute("value");}}
break;case this.ACTIONTYPE_SHOW_DROPDOWN:break;default:break;}}catch(e){yahooError("YahooPluginCallback.requentAction()::"+e);}},subscribeEvent:function(eventType,CLSID){try{yahooDebug("YahooPluginCallback::subscribeEvent()");if(eventType==this.EVENTTYPE_BROWSER){this.yLocalStorage.putString(CLSID+"_BROWSEREVENTS",true);}}catch(e){yahooError("YahooPluginCallback.subscribeEvent()::"+e);}},isInterfaceAccessible:function(InterfaceID,CLSID){try{var supportedInterface="nsIDOMWindowInternal,nsIDOMWindow,nsIWebNavigation";if(this.yLocalStorage.getString(CLSID)!=null&&this.yLocalStorage.getString(CLSID)!=""){supportedInterface=this.yLocalStorage.getString(CLSID)}
if(supportedInterface.indexOf(InterfaceID)>-1){return true;}else{return false;}}catch(e){yahooError("YahooPluginCallback.isInterfaceAccessible()::"+e);}},QueryInterface:function(iid){if(!iid.equals(Components.interfaces.nsIYahooPluginCallback)&&!iid.equals(Components.interfaces.nsISupports)){throw Components.results.NS_ERROR_NO_INTERFACE;}
return this;}};function NSGetModule(compMgr,fileSpec){return{myCID:Components.ID("{a5178fa0-7838-11de-8a39-0800200c9a66}"),myProgID:"@yahoo.com/yplugincallback;1",firstTime:true,registerSelf:function(compMgr,fileSpec,location,type){if(this.firstTime){this.firstTime=false;throw Components.results.NS_ERROR_FACTORY_REGISTER_AGAIN;}
compMgr=compMgr.QueryInterface(Components.interfaces.nsIComponentRegistrar);compMgr.registerFactoryLocation(this.myCID,"Yahoo! PluginCallback",this.myProgID,fileSpec,location,type);yahooDebug("Registered ["+this.myProgID+"] >----> "+this.myCID);},getClassObject:function(compMgr,cid,iid){if(!cid.equals(this.myCID)){throw Components.results.NS_ERROR_NO_INTERFACE;}
if(!iid.equals(Components.interfaces.nsIFactory)){throw Components.results.NS_ERROR_NOT_IMPLEMENTED;}
return this.myFactory;},myFactory:{createInstance:function(outer,iid){if(outer!==null){throw Components.results.NS_ERROR_NO_AGGREGATION;}
return new YahooPluginCallback().QueryInterface(iid);}},canUnload:function(compMgr){return true;}};}