pref('extensions.rambler_toolbar.options.birthday', '0000-00-00');
pref('extensions.rambler_toolbar.stat.lastusage', '1970-01-01');
pref('extensions.rambler_toolbar.options.city.list', 'Москва (Московская область, Россия)');
pref('extensions.rambler_toolbar.options.geoid.list', '54118936');
pref('extensions.rambler_toolbar.options.finance.list', 'USD,EUR');
pref('extensions.rambler_toolbar.scheme.lastupdate', '1970-01-01');
pref('extensions.rambler_toolbar.license.accepted', true);
pref('extensions.rambler_toolbar.partner.code', 'r02');
pref('extensions.rambler_toolbar.options.facebook.alerts', true);
pref('extensions.rambler_toolbar.options.vk.alerts', true);
pref('extensions.rambler_toolbar.options.odnoklassniki.alerts', true);
